import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { chmod, mkdir, mkdtemp, readFile, rm, symlink, writeFile } from "node:fs/promises";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

import { at } from "./source-offsets.mjs";

/*
 * THE CANARY WEARER CREDENTIAL, AND THE COVERAGE IT BUYS.
 *
 * Two 100%-wearer-facing outages passed every deploy gate. Both had the same
 * shape: Center answered every request with 200 and an honest `degraded` body
 * while every wearer saw an empty dashboard, and nothing in the canary held a
 * credential capable of telling the difference. The canary said so — it printed
 * "a 100%-degraded wearer plane would pass this canary" — and shipped anyway,
 * because a warning is not a gate.
 *
 * What closes it is one sealed Keycloak bearer for a DEDICATED canary identity,
 * obtained through Center's own POST /api/auth/login, which is the only path in
 * this system that produces the `carry_tokens` cookie set. These tests cover the
 * two halves that can be tested without a VPS:
 *
 *   1. THE CREDENTIAL CONTRACT, executed. assert_wearer_canary_secret,
 *      write_wearer_canary_login_body, normalize_wearer_canary_jar,
 *      wearer_canary_jar_subject and write_wearer_canary_jar are real functions
 *      in common.sh with no VPS dependency beyond `curl`, so they are driven
 *      here against fixtures and a stubbed Center, including every refusal.
 *
 *   2. THE SHAPE OF THE GATE, pinned. Whether the coverage runs by DEFAULT,
 *      whether the escape hatch stays out of the automation, and whether the
 *      credential can leak into an evidence file — none of which a fixture can
 *      demonstrate, all of which are how the previous version failed.
 *
 * FILE RULE, inherited from deploy-gates.test.mjs and for the same reason: every
 * positive source pin is line-anchored (`^…$` with the `m` flag). These scripts
 * explain themselves in prose, so a substring pin over this subject matter is
 * satisfied by the comment describing the check as readily as by the check.
 */

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..");
const remote = path.join(root, "platform/deploy/vps/remote");
const common = path.join(remote, "common.sh");

const canary = fs.readFileSync(path.join(remote, "canary.sh"), "utf8");
const deploy = fs.readFileSync(path.join(remote, "deploy.sh"), "utf8");
const rollback = fs.readFileSync(path.join(remote, "rollback.sh"), "utf8");
const preflight = fs.readFileSync(path.join(remote, "preflight.sh"), "utf8");
const commonSource = fs.readFileSync(common, "utf8");

/*
 * A password that is a real one in every respect that matters here: long enough
 * to clear the weak-credential refusal, and containing the shell and JSON
 * metacharacters that a naive interpolation would mangle or, worse, execute.
 * It is a fixture value for a Keycloak user that does not exist; nothing in this
 * repository provisions it and nothing on any host accepts it.
 */
const FIXTURE_PASSWORD = String.raw`fixture-"pw'$(echo no)\backslash|&;<>`;
const FIXTURE_USERNAME = "canary@fixture.invalid";

function bash(script, args = []) {
  return spawnSync("bash", ["-c", script, "fixture", common, ...args], {
    encoding: "utf8",
    maxBuffer: 8 * 1024 * 1024,
  });
}

async function workspace(t) {
  const directory = await mkdtemp(path.join(os.tmpdir(), "revival-canary-wearer-"));
  t.after(() => rm(directory, { recursive: true, force: true }));
  return directory;
}

async function secretFile(directory, { username = FIXTURE_USERNAME, password = FIXTURE_PASSWORD, mode = 0o600, body = null } = {}) {
  const file = path.join(directory, "canary-wearer.secret");
  await writeFile(
    file,
    body ?? `REVIVAL_CANARY_WEARER_USERNAME=${username}\nREVIVAL_CANARY_WEARER_PASSWORD=${password}\n`,
    { mode },
  );
  await chmod(file, mode);
  return file;
}

/* The raw jar shape normalize_wearer_canary_jar consumes: session, manifest, chunks. */
function curlJar({ chunks = 2, manifest = null, session = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjYW5hcnktc3ViamVjdCJ9.c2ln" } = {}) {
  const rows = ["# Netscape HTTP Cookie File", "# This file was generated by libcurl!"];
  const push = (name, value) => rows.push(`#HttpOnly_127.0.0.1\tFALSE\t/\tTRUE\t0\t${name}\t${value}`);
  push("carry_session", session);
  if (manifest !== "none") push("carry_tokens", manifest ?? `v1:${chunks}`);
  for (let index = 0; index < chunks; index += 1) push(`carry_tokens.${index}`, `chunk${index}${"A".repeat(40)}`);
  return `${rows.join("\n")}\n`;
}

/*
 * What Center ACTUALLY answers a successful login with, down to the two details
 * that broke the first real run of this gate against production:
 *
 *   * every cookie is `Secure`, because NODE_ENV=production sets it, while the
 *     login is loopback http — curl stores none of them, which is why the mint
 *     reads Set-Cookie itself instead of using --cookie-jar;
 *   * Next.js percent-encodes the value, so the `v1:N` manifest arrives as
 *     `v1%3AN`.
 *
 * The fixture carries both, so a rewrite that reinstates either assumption fails
 * here instead of inside a cutover window.
 */
function loginHeaders({ chunks = 2, manifest = null, session = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjYW5hcnktc3ViamVjdCJ9.c2ln", cookies = true } = {}) {
  const lines = ["HTTP/1.1 200 OK", "content-type: application/json"];
  const push = (name, value) =>
    lines.push(`set-cookie: ${name}=${value}; Path=/; Max-Age=43200; Secure; HttpOnly; SameSite=lax`);
  if (cookies) {
    push("carry_session", session);
    if (manifest !== "none") push("carry_tokens", encodeURIComponent(manifest ?? `v1:${chunks}`));
    for (let index = 0; index < chunks; index += 1) push(`carry_tokens.${index}`, `chunk${index}${"A".repeat(40)}`);
  }
  return `${lines.join("\r\n")}\r\n\r\n`;
}

test("the credential contract accepts exactly one well-formed provisioning", async (t) => {
  const directory = await workspace(t);
  const file = await secretFile(directory);
  const accepted = bash(`source "$1"; assert_wearer_canary_secret "$2"`, [file]);
  assert.equal(accepted.status, 0, accepted.stderr);
  // Nothing about the credential may reach stdout or stderr, not even a length:
  // this function runs inside preflight, whose output is captured into a deploy
  // log an operator pastes into an issue.
  assert.equal(accepted.stdout.trim(), "");
  assert.equal(accepted.stderr.trim(), "");
  assert.ok(!(accepted.stdout + accepted.stderr).includes(FIXTURE_PASSWORD));
});

test("every unsafe provisioning is refused, and the refusal names the property", async (t) => {
  const directory = await workspace(t);

  /*
   * Each case is a real way this gets provisioned wrong. The mode and ownership
   * ones are not ceremony: this file is a live wearer credential sitting in the
   * same directory as center.env, and a 0644 copy of it is readable by every
   * process on the host.
   */
  const cases = [
    ["absent", async () => path.join(directory, "not-provisioned")],
    ["group-readable", async () => secretFile(await sub(directory, "mode"), { mode: 0o640 })],
    ["world-readable", async () => secretFile(await sub(directory, "world"), { mode: 0o644 })],
    ["a symlink", async () => {
      const nested = await sub(directory, "link");
      const real = await secretFile(nested);
      const link = path.join(nested, "linked.secret");
      await symlink(real, link);
      return link;
    }],
    ["an extra key", async () => secretFile(await sub(directory, "extra"), {
      body: `REVIVAL_CANARY_WEARER_USERNAME=${FIXTURE_USERNAME}\nREVIVAL_CANARY_WEARER_PASSWORD=${FIXTURE_PASSWORD}\nCARRY_ADMIN_TOKEN=something-else\n`,
    })],
    ["a missing key", async () => secretFile(await sub(directory, "missing"), {
      body: `REVIVAL_CANARY_WEARER_USERNAME=${FIXTURE_USERNAME}\n`,
    })],
    ["an empty value", async () => secretFile(await sub(directory, "empty"), { password: "" })],
    ["a placeholder password", async () => secretFile(await sub(directory, "short"), { password: "changeme" })],
    ["the username reused as the password", async () => secretFile(await sub(directory, "same"), {
      username: "reused-credential-value",
      password: "reused-credential-value",
    })],
    ["a control character", async () => secretFile(await sub(directory, "control"), {
      body: `REVIVAL_CANARY_WEARER_USERNAME=${FIXTURE_USERNAME}\nREVIVAL_CANARY_WEARER_PASSWORD=with\ttab-and-more-length\n`,
    })],
    ["a line that is not KEY=VALUE", async () => secretFile(await sub(directory, "garbage"), {
      body: `REVIVAL_CANARY_WEARER_USERNAME=${FIXTURE_USERNAME}\nREVIVAL_CANARY_WEARER_PASSWORD=${FIXTURE_PASSWORD}\nnot an assignment\n`,
    })],
  ];

  for (const [label, build] of cases) {
    const file = await build();
    const result = bash(`source "$1"; assert_wearer_canary_secret "$2"`, [file]);
    assert.notEqual(result.status, 0, `an unsafe credential was accepted: ${label}`);
    assert.ok(result.stderr.trim().length > 0, `the refusal for ${label} said nothing`);
    assert.ok(
      !(result.stdout + result.stderr).includes(FIXTURE_PASSWORD),
      `the refusal for ${label} echoed the credential`,
    );
  }

  async function sub(base, name) {
    const nested = path.join(base, name);
    await mkdir(nested, { recursive: true, mode: 0o700 });
    await chmod(nested, 0o700);
    return nested;
  }
});

test("a credential in a group-accessible directory is refused even at mode 0600", async (t) => {
  // 0600 on the file is not enough if the directory can be traversed and the
  // file replaced. $PRIVATE_DIR is 0700 for this reason, and a credential
  // provisioned somewhere looser must not be silently accepted.
  const directory = await workspace(t);
  const open = path.join(directory, "open");
  await mkdir(open, { recursive: true, mode: 0o755 });
  await chmod(open, 0o755);
  const file = await secretFile(open);
  const result = bash(`source "$1"; assert_wearer_canary_secret "$2"`, [file]);
  assert.notEqual(result.status, 0);
});

test("the login body is the exact JSON Center's login route parses, and stays 0600", async (t) => {
  const directory = await workspace(t);
  const file = await secretFile(directory);
  const output = path.join(directory, "login.json");
  const result = bash(`source "$1"; write_wearer_canary_login_body "$2" "$3"`, [file, output]);
  assert.equal(result.status, 0, result.stderr);

  const body = JSON.parse(await readFile(output, "utf8"));
  // Exactly the two fields center/src/app/api/auth/login/route.ts reads. An
  // extra field would be ignored there and is therefore invisible drift.
  assert.deepEqual(Object.keys(body).sort(), ["password", "username"]);
  assert.equal(body.username, FIXTURE_USERNAME);
  // The metacharacters survive verbatim: this is what proves the value is
  // carried as data rather than pasted into a shell word.
  assert.equal(body.password, FIXTURE_PASSWORD);
  assert.equal(fs.statSync(output).mode & 0o777, 0o600);
  assert.ok(!(result.stdout + result.stderr).includes(FIXTURE_PASSWORD));
});

test("a jar with a session and no sealed tokens is refused — that jar is the blind spot", async (t) => {
  /*
   * THE CENTRAL REGRESSION. write_owner_canary_cookie mints a `carry_session`
   * and deliberately no bearer, and a wearer-plane gate handed that jar reports
   * `degraded` as the CORRECT answer — which is exactly how a genuinely
   * 100%-degraded deployment passed twice. Accepting a session-only jar here
   * would reinstate the blind spot with the new code's name on it.
   */
  const directory = await workspace(t);
  const raw = path.join(directory, "raw.cookies");
  await writeFile(raw, curlJar({ manifest: "none", chunks: 0 }), { mode: 0o600 });
  const result = bash(`source "$1"; normalize_wearer_canary_jar "$2" "$3"`, [raw, path.join(directory, "out.cookies")]);
  assert.notEqual(result.status, 0);
  assert.match(result.stderr, /sealed token cookie/);
  assert.equal(fs.existsSync(path.join(directory, "out.cookies")), false);
});

test("an incomplete or malformed sealed token set is refused", async (t) => {
  const directory = await workspace(t);
  const output = path.join(directory, "out.cookies");

  // A manifest that promises four chunks and delivers two: Center never writes
  // this, but a truncated Set-Cookie block at any hop produces it, and the
  // reassembled JWE would fail to decrypt as a silent `degraded` later.
  const truncated = path.join(directory, "truncated.cookies");
  await writeFile(truncated, curlJar({ chunks: 2, manifest: "v1:4" }), { mode: 0o600 });
  const missingChunk = bash(`source "$1"; normalize_wearer_canary_jar "$2" "$3"`, [truncated, output]);
  assert.notEqual(missingChunk.status, 0);
  assert.match(missingChunk.stderr, /missing a chunk/);

  // A manifest in a format Center does not write at all.
  const strange = path.join(directory, "strange.cookies");
  await writeFile(strange, curlJar({ manifest: "v2:1" }), { mode: 0o600 });
  const badManifest = bash(`source "$1"; normalize_wearer_canary_jar "$2" "$3"`, [strange, output]);
  assert.notEqual(badManifest.status, 0);
  assert.match(badManifest.stderr, /chunk format/);

  assert.equal(fs.existsSync(output), false);
});

test("a complete jar is normalized to every host the canary dials, without the Secure flag", async (t) => {
  const directory = await workspace(t);
  const raw = path.join(directory, "raw.cookies");
  const output = path.join(directory, "out.cookies");
  await writeFile(raw, curlJar({ chunks: 3 }), { mode: 0o600 });
  const result = bash(`source "$1"; normalize_wearer_canary_jar "$2" "$3"`, [raw, output]);
  assert.equal(result.status, 0, result.stderr);

  const rows = (await readFile(output, "utf8")).trimEnd().split("\n").slice(1).map((line) => line.split("\t"));
  const hosts = new Set(rows.map((row) => row[0]));
  // The quiesced canary reaches Center on 127.0.0.1 while sending a dashboard
  // Host header, and the public run uses the canonical origin; a jar missing
  // either host is silently empty on that run rather than failing.
  assert.deepEqual(
    [...hosts].sort(),
    ["#HttpOnly_carry.andersmadsen.dk", "#HttpOnly_center.andersmadsen.dk", "127.0.0.1"],
  );
  const names = rows.filter((row) => row[0] === "127.0.0.1").map((row) => row[5]);
  assert.deepEqual(names, ["carry_session", "carry_tokens", "carry_tokens.0", "carry_tokens.1", "carry_tokens.2"]);
  // Secure=FALSE on purpose: the quiesced window speaks plain HTTP to loopback
  // and curl withholds a Secure cookie there.
  assert.ok(rows.every((row) => row[3] === "FALSE"));
  assert.equal(fs.statSync(output).mode & 0o777, 0o600);
});

test("the canary's own subject is readable, so it can prove it is not the paired wearer", async (t) => {
  const directory = await workspace(t);
  const jar = path.join(directory, "jar.cookies");
  const raw = path.join(directory, "raw.cookies");
  await writeFile(raw, curlJar(), { mode: 0o600 });
  assert.equal(bash(`source "$1"; normalize_wearer_canary_jar "$2" "$3"`, [raw, jar]).status, 0);
  const subject = bash(`source "$1"; wearer_canary_jar_subject "$2"`, [jar]);
  assert.equal(subject.status, 0, subject.stderr);
  assert.equal(subject.stdout.trim(), "canary-subject");
});

/*
 * The end-to-end mint, against a stubbed Center.
 *
 * `curl` is shadowed by a shell function after common.sh is sourced, so the real
 * write_wearer_canary_jar runs: it validates the secret, writes the body,
 * "posts" it, and normalizes what comes back. The stub records the arguments it
 * was handed, which is how the argv claim in the comment above that function is
 * checked rather than believed.
 */
const stubbedCurl = String.raw`
curl() {
  local previous="" argument headers="" body=""
  printf '%s\n' "$@" >"$SPY_ARGV"
  for argument in "$@"; do
    # -D, not --cookie-jar: curl's cookie engine discards a Secure cookie that
    # arrived over http, so the mint reads the response headers directly. A stub
    # that answered --cookie-jar would be a more permissive curl than the real
    # one, which is exactly the gap that let this ship broken.
    if [[ "$previous" == -D ]]; then headers="$argument"; fi
    if [[ "$previous" == --cookie-jar ]]; then echo 'the mint asked curl to store cookies it will not store' >&2; return 1; fi
    if [[ "$previous" == --data ]]; then body="$(printf '%s' "$argument" | sed 's/^@//')"; fi
    previous="$argument"
  done
  if [[ -n "$body" ]]; then cp -- "$body" "$SPY_BODY"; fi
  if [[ -n "$headers" ]]; then cp -- "$STUB_HEADERS" "$headers"; fi
  printf '%s' "$STUB_STATUS"
}
`;

/*
 * A seam into the mint's private workspace.
 *
 * write_wearer_canary_jar does its work in a `mktemp -d` it removes on the way
 * out, so nothing the caller can name survives to be inspected — which is
 * correct, and which is also why the "the body file is deleted" claim has to be
 * observed from INSIDE. normalize_wearer_canary_jar is the first thing to run
 * after the request, and its first argument lives in that workspace, so
 * wrapping it lists the directory at exactly the instant the credential body
 * must already be gone. The real function still runs, so nothing else about the
 * case is stubbed out.
 */
const spiedNormalize = String.raw`
eval "spied_original_normalize() $(declare -f normalize_wearer_canary_jar | tail -n +2)"
normalize_wearer_canary_jar() {
  ls -A -- "$(dirname -- "$1")" >"$SPY_WORK"
  spied_original_normalize "$@"
}
`;

test("a successful sign-in yields a jar, and the credential never reaches argv", async (t) => {
  const directory = await workspace(t);
  const secret = await secretFile(directory);
  const stubHeaders = path.join(directory, "stub.headers");
  await writeFile(stubHeaders, loginHeaders({ chunks: 2 }), { mode: 0o600 });
  const output = path.join(directory, "wearer.cookies");
  const spyArgv = path.join(directory, "argv.txt");
  const spyBody = path.join(directory, "body.json");
  const spyWork = path.join(directory, "workspace.txt");

  const result = bash(
    `source "$1"
${stubbedCurl}
${spiedNormalize}
WEARER_CANARY_SECRET="$2"
export STUB_HEADERS="$3" STUB_STATUS=200 SPY_ARGV="$4" SPY_BODY="$5" SPY_WORK="$7"
write_wearer_canary_jar "$6"`,
    [secret, stubHeaders, spyArgv, spyBody, output, spyWork],
  );
  assert.equal(result.status, 0, result.stderr);
  assert.equal(fs.statSync(output).mode & 0o777, 0o600);

  const argv = await readFile(spyArgv, "utf8");
  // The whole point of `--data @path`: the request carries the credential and
  // the process table does not. A future rewrite that builds an inline body
  // fails here.
  assert.ok(!argv.includes(FIXTURE_PASSWORD), "the credential appeared in curl's arguments");
  assert.ok(!argv.includes(FIXTURE_USERNAME), "the canary identity appeared in curl's arguments");
  assert.match(argv, /^--data$/m);
  // Loopback only. A credential that traverses the public edge is a credential
  // in somebody's access log, and the quiesced window has no public edge at all.
  assert.match(argv, /^http:\/\/127\.0\.0\.1:14000\/api\/auth\/login$/m);

  const body = JSON.parse(await readFile(spyBody, "utf8"));
  assert.equal(body.password, FIXTURE_PASSWORD);
  assert.ok(!(result.stdout + result.stderr).includes(FIXTURE_PASSWORD));

  // The body file is removed as soon as the request is made, rather than living
  // for the length of the canary run.
  //
  // Observed inside write_wearer_canary_jar's own `mktemp -d` workspace, which
  // is where the body actually is. Looking for it beside the fixture directory
  // asserted nothing at all: that path is never written, so the check passed
  // whether or not the `rm -f` existed.
  const workspaceEntries = (await readFile(spyWork, "utf8")).split("\n").filter(Boolean);
  assert.ok(workspaceEntries.includes("raw.cookies"), "the mint's workspace was not observed");
  assert.ok(
    !workspaceEntries.includes("login.json"),
    "the credential body outlived the request that carried it",
  );
});

test("a rejected credential fails the mint instead of producing an empty jar", async (t) => {
  const directory = await workspace(t);
  const secret = await secretFile(directory);
  const stubHeaders = path.join(directory, "stub.headers");
  await writeFile(stubHeaders, loginHeaders(), { mode: 0o600 });
  const output = path.join(directory, "wearer.cookies");

  for (const status of ["401", "503", "000"]) {
    const result = bash(
      `source "$1"
${stubbedCurl}
WEARER_CANARY_SECRET="$2"
export STUB_HEADERS="$3" STUB_STATUS="$4" SPY_ARGV="$5" SPY_BODY="$6"
write_wearer_canary_jar "$7"`,
      [secret, stubHeaders, status, path.join(directory, "argv.txt"), path.join(directory, "body.json"), output],
    );
    assert.notEqual(result.status, 0, `HTTP ${status} was treated as a successful sign-in`);
    assert.match(result.stderr, new RegExp(`could not sign in to Center \\(HTTP ${status}\\)`));
    assert.ok(!(result.stdout + result.stderr).includes(FIXTURE_PASSWORD));
    assert.equal(fs.existsSync(output), false, `HTTP ${status} still left a jar behind`);
  }
});

test("a Center that answers 200 with no sealed tokens fails the mint", async (t) => {
  // The failure mode with no obvious symptom: login succeeds, the session is
  // set, and sealTokens produced nothing usable. Center reports 200 either way.
  const directory = await workspace(t);
  const secret = await secretFile(directory);
  const stubHeaders = path.join(directory, "stub.headers");
  await writeFile(stubHeaders, loginHeaders({ manifest: "none", chunks: 0 }), { mode: 0o600 });
  const output = path.join(directory, "wearer.cookies");
  const result = bash(
    `source "$1"
${stubbedCurl}
WEARER_CANARY_SECRET="$2"
export STUB_HEADERS="$3" STUB_STATUS=200 SPY_ARGV="$4" SPY_BODY="$5"
write_wearer_canary_jar "$6"`,
    [secret, stubHeaders, path.join(directory, "argv.txt"), path.join(directory, "body.json"), output],
  );
  assert.notEqual(result.status, 0);
  assert.equal(fs.existsSync(output), false);
});

test("the mint survives the Secure cookies Center actually sets over loopback http", async (t) => {
  /*
   * THE DEFECT THIS FILE WAS WRITTEN AROUND AND DID NOT CATCH.
   *
   * The first time this gate ever executed against production it failed with
   * "Center's login could not obtain a sealed bearer" — not because anything in
   * the deployment was wrong, but because curl DISCARDS a `Secure` cookie that
   * arrived over an http URL, and the login is loopback http by design. Center
   * sets all four cookies Secure under NODE_ENV=production, so curl's jar came
   * back empty on every possible run, quiesced or not. Observed on the host with
   * curl 8.5.0, against both http://127.0.0.1:14000 and http://localhost:14000:
   * four Set-Cookie headers received, zero cookies stored.
   *
   * The old stub hid it exactly: it honoured --cookie-jar, which real curl
   * would not have. This drives the mint against the real response headers.
   */
  const directory = await workspace(t);
  const secret = await secretFile(directory);
  const stubHeaders = path.join(directory, "stub.headers");
  await writeFile(stubHeaders, loginHeaders({ chunks: 3 }), { mode: 0o600 });
  const output = path.join(directory, "wearer.cookies");
  const result = bash(
    `source "$1"
${stubbedCurl}
WEARER_CANARY_SECRET="$2"
export STUB_HEADERS="$3" STUB_STATUS=200 SPY_ARGV="$4" SPY_BODY="$5"
write_wearer_canary_jar "$6"`,
    [secret, stubHeaders, path.join(directory, "argv.txt"), path.join(directory, "body.json"), output],
  );
  assert.equal(result.status, 0, result.stderr);
  const rows = (await readFile(output, "utf8")).trimEnd().split("\n").slice(1).map((line) => line.split("\t"));
  const loopback = rows.filter((row) => row[0] === "127.0.0.1");
  assert.deepEqual(
    loopback.map((row) => row[5]),
    ["carry_session", "carry_tokens", "carry_tokens.0", "carry_tokens.1", "carry_tokens.2"],
  );
  // The manifest keeps the percent-encoded form Next.js emits, because that is
  // what a browser sends back; decoding it here would rewrite the cookie.
  assert.equal(loopback[1][6], "v1%3A3");
  assert.equal(fs.statSync(output).mode & 0o777, 0o600);
});

test("a login that sets no cookie is refused, and a cleared cookie is not a credential", async (t) => {
  const directory = await workspace(t);

  // 200 with no Set-Cookie at all: the shape a misrouted or cached response
  // takes, and the one that must not be mistaken for the Secure-cookie defect.
  const empty = path.join(directory, "empty.headers");
  await writeFile(empty, loginHeaders({ cookies: false }), { mode: 0o600 });
  const refused = bash(`source "$1"; write_login_cookie_jar "$2" "$3"`, [empty, path.join(directory, "empty.cookies")]);
  assert.notEqual(refused.status, 0);
  assert.match(refused.stderr, /set no cookie at all/);

  // Center clears with Max-Age=0. A jar that stored the clearing cookie would
  // present an emptied session as a complete one.
  const cleared = path.join(directory, "cleared.headers");
  await writeFile(
    cleared,
    "HTTP/1.1 200 OK\r\nset-cookie: carry_session=; Path=/; Max-Age=0; Secure; HttpOnly\r\n" +
      "set-cookie: carry_tokens=v1%3A1; Path=/; Max-Age=43200; Secure; HttpOnly\r\n\r\n",
    { mode: 0o600 },
  );
  const jar = path.join(directory, "cleared.cookies");
  assert.equal(bash(`source "$1"; write_login_cookie_jar "$2" "$3"`, [cleared, jar]).status, 0);
  const names = (await readFile(jar, "utf8")).trimEnd().split("\n").slice(1).map((line) => line.split("\t")[5]);
  assert.deepEqual(names, ["carry_tokens"]);
  const normalized = bash(`source "$1"; normalize_wearer_canary_jar "$2" "$3"`, [jar, path.join(directory, "out.cookies")]);
  assert.notEqual(normalized.status, 0);
  assert.match(normalized.stderr, /set no session cookie/);
});

test("an unprovisioned credential fails the mint before any request is made", async (t) => {
  const directory = await workspace(t);
  const result = bash(
    `source "$1"
${stubbedCurl}
WEARER_CANARY_SECRET="$2"
export STUB_HEADERS=/dev/null STUB_STATUS=200 SPY_ARGV="$3" SPY_BODY="$4"
write_wearer_canary_jar "$5"`,
    [
      path.join(directory, "absent.secret"),
      path.join(directory, "argv.txt"),
      path.join(directory, "body.json"),
      path.join(directory, "wearer.cookies"),
    ],
  );
  assert.notEqual(result.status, 0);
  assert.equal(fs.existsSync(path.join(directory, "argv.txt")), false, "curl was called without a credential");
});

/* ── The shape of the gate ──────────────────────────────────────────────── */

test("the wearer plane is proven by DEFAULT, with no flag required to arm it", () => {
  /*
   * The single most important property here. The previous gate was opt-in behind
   * --require-wearer-plane, armed on two of roughly a dozen canary invocations,
   * and warned-and-passed everywhere else — which is how a run that never asked
   * Center for wearer data reported success. Default-on is what makes the two
   * outages that shipped green impossible to repeat by forgetting a flag.
   */
  assert.match(canary, /^if wearer_canary_secret_present; then$/m);
  assert.match(
    canary,
    /^  write_wearer_canary_jar "\$wearer_jar" \\$/m,
    "the canary must mint its own sealed bearer rather than depend on a caller's jar",
  );
  // The request loop, not the route names: the same five routes are named in the
  // prose above it and in the sentence emitted when the plane is waived, so an
  // unanchored pin over a route name is satisfied by a comment.
  assert.match(canary, /^  for surface in health:\/api\/health notes:\/api\/capture\/notes \\$/m);
  assert.match(
    canary,
    /^    memories:\/api\/capture\/memories features:\/api\/settings\/features wifi:\/api\/settings\/wifi; do$/m,
  );
  assert.match(
    canary,
    /^      \|\| fail "Center wearer surface must answer 200 for a sealed-bearer session: \$route \(\$surface_status\)"$/m,
  );
});

test("a missing credential fails the canary rather than warning past it", () => {
  // The old default WAS the warning. It named the consequence precisely — "a
  // 100%-degraded wearer plane would pass this canary" — and then passed. The
  // refusal is what changed; the flag that overrides it is a separate decision
  // an operator has to type.
  assert.match(
    canary,
    /^    \|\| fail "the canary wearer credential is absent \(\$WEARER_CANARY_SECRET\)/m,
    "an absent credential must fail the canary by default",
  );
  assert.match(canary, /^    --wearer-plane-optional\) wearer_plane_optional=1; shift ;;$/m);
  // The waiver must be loud in the run it applies to, not merely accepted.
  assert.match(canary, /^  warn "RUNNING WITHOUT WEARER-PLANE COVERAGE by explicit request:/m);
});

test("the escape hatch is reachable by an operator and by no automation", () => {
  /*
   * A default-safe gate with an escape hatch wired into the deploy path is the
   * warn-and-pass default again, spelled differently. deploy.sh and rollback.sh
   * must never pass it; the operator wrapper must, or the next person under
   * pressure edits the deploy path instead of typing a flag.
   */
  assert.doesNotMatch(deploy, /--wearer-plane-optional/);
  assert.doesNotMatch(rollback, /--wearer-plane-optional/);
  const wrapper = fs.readFileSync(path.join(root, "platform/deploy/vps/canary.sh"), "utf8");
  assert.match(wrapper, /^    --wearer-plane-optional\) wearer_plane_optional=1; shift ;;$/m);
  assert.match(wrapper, /^\(\(wearer_plane_optional\)\) && args\+=\(--wearer-plane-optional\)$/m);
});

test("a changed canary can be proven against production before a deploy needs it", () => {
  /*
   * THE GAP THIS CLOSES. `./revival canary` dispatches through
   * run_current_release_operation, which runs the DEPLOYED release's canary.sh.
   * So every assertion above — the whole reason this file exists — could not
   * execute even once until a deploy was already underway, with public ingress
   * quiesced. A gate whose first run is inside the outage window it is meant to
   * prevent is not yet a gate; a typo in it lengthens the outage instead of
   * failing a check.
   *
   * --from-tree is the escape hatch, and it is held to exactly the same rule as
   * --wearer-plane-optional: reachable by an operator at a terminal, reachable
   * by no automation. It skips release verification by construction (there is
   * no release to verify — that is the point), so a deploy that could reach it
   * would be running an unverified gate against a live cutover.
   */
  const wrapper = fs.readFileSync(path.join(root, "platform/deploy/vps/canary.sh"), "utf8");
  assert.match(wrapper, /^    --from-tree\) from_tree=1; shift ;;$/m);
  assert.match(wrapper, /^  run_working_tree_canary "\$\{args\[@\]\}"$/m);
  assert.match(wrapper, /^  run_current_release_operation canary\.sh "\$\{args\[@\]\}"$/m);

  for (const [name, source] of [
    ["platform/deploy/vps/remote/deploy.sh", deploy],
    ["platform/deploy/vps/remote/rollback.sh", rollback],
    ["platform/deploy/vps/deploy.sh", fs.readFileSync(path.join(root, "platform/deploy/vps/deploy.sh"), "utf8")],
    ["platform/deploy/vps/rollback.sh", fs.readFileSync(path.join(root, "platform/deploy/vps/rollback.sh"), "utf8")],
  ]) {
    assert.doesNotMatch(source, /--from-tree|run_working_tree_canary/, `${name} must not reach the working-tree canary`);
  }

  /*
   * The two properties the release bootstrap would have supplied and the
   * streamed path has to restate. The lock is the one that matters on a live
   * host: run_current_release_operation holds deploy.lock for canary.sh, and a
   * from-tree run that did not would be the one canary capable of racing a
   * deploy.
   */
  const localLib = fs.readFileSync(path.join(root, "platform/deploy/vps/lib/local.sh"), "utf8");
  assert.match(localLib, /^flock -n 9 \|\| \{ echo "stateful operation lock is held" >&2; exit 1; \}$/m);
  assert.match(
    localLib,
    /^\[\[ "\$\(hostname -s\)" == anders-server && "\$\(id -un\)" == anders \]\] \|\| \{ echo "working-tree canary target identity mismatch" >&2; exit 1; \}$/m,
  );
  // Every other run_remote_impl caller must be unaffected by the hook that makes
  // the guard possible.
  assert.match(localLib, /^REMOTE_IMPL_GUARD=""$/m);
});

test("the new option is not smuggled across a release boundary", () => {
  /*
   * canary.sh is invoked out of a PENDING release's tree by whichever deploy.sh
   * is running, so its interface is whatever it was when that release was cut.
   * Deploy 14 deadlocked an armed cutover exactly this way. The wearer-plane
   * coverage therefore arrives WITHOUT an interface change: the canary mints its
   * own jar, so no caller has to learn a new option, and the baseline list is
   * untouched.
   */
  const baseline = commonSource.slice(at(commonSource, "cross_release_baseline_options()"));
  assert.doesNotMatch(baseline.slice(0, 2000), /--wearer-plane-optional/);
  assert.match(
    commonSource,
    /^        --require-owner-spotify --require-wearer-plane --quiesced-loopback \\$/m,
    "the frozen canary baseline must keep the options older releases already accept",
  );
});

test("preflight refuses before the cutover window, not inside it", () => {
  // The canaries that matter run with public ingress down and the live mutation
  // begun. Discovering an unprovisioned credential there stops a deploy at the
  // worst possible moment; preflight is where the same answer is free.
  assert.match(
    preflight,
    /^assert_wearer_canary_secret "\$WEARER_CANARY_SECRET" \\$/m,
  );
  assert.ok(
    at(preflight, "assert_wearer_canary_secret") < at(preflight, "preflight passed on anders-server"),
  );
});

test("the credential is proven least-privilege at runtime, not merely in the runbook", () => {
  /*
   * A gate that assumes its own credential is scoped correctly is a gate that
   * hands an attacker the paired wearer's account the first time somebody
   * provisions it lazily. Both refusals are cheap and both are absolute: the
   * canary identity may not be the paired Pin owner, and it may not be an
   * operator.
   *
   * THE CONDITION IS PINNED WITH THE SENTENCE, NOT INSTEAD OF IT. A `|| fail
   * "…"` line survives every relaxation of the test above it: widening the
   * status check to `403 || 200` — which is exactly what accepting an
   * operator-privileged canary looks like — leaves the message byte-identical
   * and a message-only assertion green. The refusal text is the part a reader
   * greps for; the test above it is the part that decides.
   */
  assert.match(
    canary,
    /^  \[\[ -n "\$wearer_owner_sub" && "\$wearer_subject" != "\$wearer_owner_sub" \]\] \\\n    \|\| fail "the canary wearer credential is the paired Pin owner; provision a dedicated canary identity"$/m,
  );
  // 403 and nothing else. 401 would mean the jar is never read, so the whole
  // block below proves nothing; 200 would mean the operator provisioned an
  // operator, and a canary that can reach /api/admin is a canary whose stolen
  // jar is worth the admin plane.
  assert.match(
    canary,
    /^  \[\[ "\$wearer_admin_status" == 403 \]\] \\\n    \|\| fail "the canary wearer is not a least-privilege wearer: \/api\/admin\/overview answered \$wearer_admin_status \(403 is the only correct answer\)"$/m,
  );
  // `live` has to be earned by the bearer. CARRY_PRINCIPAL is cosmos.ts's
  // identity fallback; a deployment that set it would satisfy every assertion
  // below while proving nothing about the token chain. `exit found?1:0` is the
  // whole check — an awk that always exits 0 makes the `|| fail` unreachable.
  assert.match(
    canary,
    /^    \| awk -F= '\$1=="CARRY_PRINCIPAL" && length\(\$2\)>0 \{found=1\} END\{exit found\?1:0\}' \\\n    \|\| fail "Center injects CARRY_PRINCIPAL, so a live wearer plane would prove nothing about the bearer chain"$/m,
  );
});

test("the assertions are about substance, so a 200 with an empty or error body fails", () => {
  /*
   * Every route in the loop answers 200 whether the read succeeded or collapsed
   * — that is Center's honest-degradation contract and it is correct. Status is
   * therefore not evidence of anything, which is why the previous credential-free
   * gate could pass a deployment where every wearer saw nothing.
   */
  // The status gate that gets the bodies at all. Pinned as the comparison and
  // not as its message, for the reason given in the least-privilege test above:
  // `[[ "$surface_status" != 999 ]]` keeps the sentence and refuses nothing.
  assert.match(
    canary,
    /^    \[\[ "\$surface_status" == 200 \]\] \\\n      \|\| fail "Center wearer surface must answer 200 for a sealed-bearer session: \$route \(\$surface_status\)"$/m,
  );
  assert.match(canary, /^        assert "error" not in payload, f"\{name\} answered 200 with an error body: \{payload\.get\('error'\)\}"$/m);
  assert.match(canary, /^    assert plane\.get\("state"\)=="live", f"the \{half\} wearer plane is not live: \{plane\.get\('detail'\)\}"$/m);
  assert.match(canary, /^assert state\("notes"\)=="live", "the notes REST projection is not live for a sealed-bearer session"$/m);
  assert.match(canary, /^assert state\("memories"\)=="live", "the memories aggregate is not live for a sealed-bearer session"$/m);
  assert.match(canary, /^    assert detail\.get\("state"\)=="live", f"a wearer data part is not live: \{part\} \(\{detail\.get\('degraded'\)\}\)"$/m);
  assert.match(canary, /^assert state\("wifi"\)=="live", "the Wi-Fi pane did not resolve for a sealed-bearer session"$/m);
  // An empty `networks` is the CORRECT live answer — Center cannot open
  // device-sealed envelopes — so the substance is the count, which only a real
  // backend answer produces.
  assert.match(canary, /^assert isinstance\(wifi\.get\("sealedCount"\),int\) and wifi\["sealedCount"\]>=0, \($/m);
});

test("the canary still says which link in the chain it cannot reach", () => {
  /*
   * refreshTokens is only entered inside the last 60 seconds of an access
   * token's life (center/src/server/cosmos.ts), and this jar is seconds old. The
   * bearer, JWKS and edge-token links are now proven; rotation is not, and the
   * habit of saying so out loud is the only reason the previous gap was ever
   * found.
   */
  assert.match(canary, /^  warn "the token REFRESH path is not exercised:/m);
});

test("nothing that survives the run can carry the credential", () => {
  /*
   * The credential must not widen what reading a log, an evidence file or a
   * deployment record is worth. The secret lives in $PRIVATE_DIR and is
   * deliberately absent from the protected-configuration inventory, because
   * fingerprinting it there would make a routine credential rotation trip the
   * config-drift gate and deadlock a deploy.
   */
  assert.match(commonSource, /^WEARER_CANARY_SECRET="\$PRIVATE_DIR\/canary-wearer.secret"$/m);
  const inventory = commonSource.slice(at(commonSource, "edge.envoy\t$PRIVATE_DIR/edge/envoy.yaml"));
  assert.doesNotMatch(inventory.slice(0, 4000), /canary-wearer/);
  // It is not an env-file key either: those are interpolated into Compose and
  // land in container environments, where a workload could read it.
  for (const source of [commonSource, canary, deploy, preflight]) {
    assert.doesNotMatch(source, /REVIVAL_CANARY_WEARER_PASSWORD=/);
  }
  // The jar lives in the canary's own mktemp workspace, which the EXIT trap
  // removes, and is deleted explicitly as soon as the assertions are done.
  assert.match(canary, /^  wearer_jar="\$work\/wearer.cookies"$/m);
  assert.match(
    canary,
    /^  rm -f -- "\$work"\/sealed-\*\.json "\$work"\/sealed-\*\.headers "\$wearer_cookie_header" "\$wearer_jar"$/m,
  );
});

test("the JSON result cannot be read as wearer coverage it does not have", () => {
  // A machine reader that treats ok:true as "wearers are fine" is the original
  // failure one level up. The field says which of the two it is, in words.
  assert.match(canary, /^    "wearerPlane":"sealed-bearer" if sys\.argv\[3\]=="1" else "unproven",$/m);
  // And argv[3] has to be the flag the assertions set. Pinning the ternary
  // alone leaves `python3 - "$release_id" "$crud" 1` green — a literal that
  // makes every run claim sealed-bearer coverage, which is the same lie this
  // field exists to prevent, told through the one input the field reads.
  assert.match(
    canary,
    /^  python3 - "\$release_id" "\$crud" "\$wearer_plane_proven" <<'PY'$/m,
    "the JSON verdict must be fed the flag the wearer-plane assertions set, not a literal",
  );
});
