//! @generated by platform/containers/pin-builder/tier-a-registry.mjs. Do not edit.
//! Authored sources: contracts/tier-a/registry.json, contracts/tier-a/native-actions.tsv,
//! and the referenced runtime/core/proto files.

#![allow(dead_code)]

pub mod packages {
    pub const BORT: &str = "hu.ma.ne.bort";
    pub const BORT_OTA: &str = "hu.ma.ne.bort.ota";
    pub const DIALER: &str = "humane.experience.dialer";
    pub const ESIM_LPA: &str = "humane.connectivity.esimlpa";
    pub const FOOD: &str = "humane.experience.food";
    pub const IRONMAN: &str = "hu.ma.ne.ironman";
    pub const KRYPTO: &str = "hu.ma.ne.krypto";
    pub const MEMFAULT_USAGE_REPORTER: &str = "com.memfault.usagereporter";
    pub const MESSAGES: &str = "humane.experience.messages";
    pub const METRIC_REPORTER: &str = "hu.ma.ne.metricreporter";
    pub const MUSIC: &str = "humane.experience.music";
    pub const ONBOARDING: &str = "humane.experience.onboarding";
    pub const OTA: &str = "humane.ota";
    pub const PHOTOGRAPHY: &str = "humane.experience.photography";
    pub const SETTINGS: &str = "humane.experience.settings";
    pub const SYSTEM_NAVIGATION: &str = "humane.experience.systemnavigation";
    pub const TICKLE: &str = "humane.experience.tickle";
    pub const VOICE_TTS: &str = "humane.voice.tts";

    pub const ALL: &[&str] = &[
        BORT,
        BORT_OTA,
        DIALER,
        ESIM_LPA,
        FOOD,
        IRONMAN,
        KRYPTO,
        MEMFAULT_USAGE_REPORTER,
        MESSAGES,
        METRIC_REPORTER,
        MUSIC,
        ONBOARDING,
        OTA,
        PHOTOGRAPHY,
        SETTINGS,
        SYSTEM_NAVIGATION,
        TICKLE,
        VOICE_TTS,
    ];
}

pub mod rpc_paths {
    pub const AIBUS_ENCRYPTED_LOADING_MESSAGE: &str =
        "/humane.aibus.AIBusService/EncryptedLoadingMessage";
    pub const AIBUS_ENCRYPTED_UNDERSTAND: &str = "/humane.aibus.AIBusService/EncryptedUnderstand";
    pub const AIBUS_UNDERSTAND: &str = "/humane.aibus.AIBusService/Understand";
    pub const AIBUS_UPLOAD_FILE: &str = "/humane.aibus.AIBusService/UploadFile";
    pub const CAPTURE_UPLOAD_FILE: &str = "/humane.capture.CaptureService/UploadFile";

    pub const ALL: &[&str] = &[
        AIBUS_ENCRYPTED_LOADING_MESSAGE,
        AIBUS_ENCRYPTED_UNDERSTAND,
        AIBUS_UNDERSTAND,
        AIBUS_UPLOAD_FILE,
        CAPTURE_UPLOAD_FILE,
    ];
}

pub mod proto_kids {
    pub const ACTION_BASED_INTERSTITIAL_REQUEST: &str =
        "humane.aibus.ActionBasedInterstitialRequest";
    pub const ACTION_BASED_INTERSTITIAL_RESPONSE: &str =
        "humane.aibus.ActionBasedInterstitialResponse";
    pub const AI_REQUEST: &str = "humane.aibus.AIRequest";
    pub const AI_RESPONSE: &str = "humane.aibus.AIResponse";
    pub const ANALYZE_FOOD_IMAGE_REQUEST: &str = "humane.aibus.AnalyzeFoodImageRequest";
    pub const ANALYZE_FOOD_IMAGE_RESPONSE: &str = "humane.aibus.AnalyzeFoodImageResponse";
    pub const ANALYZE_IMAGE_RESPONSE: &str = "humane.aibus.AnalyzeImageResponse";
    pub const CAN_TRANSLATE_REQUEST: &str = "humane.aibus.CanTranslateRequest";
    pub const CAN_TRANSLATE_RESPONSE: &str = "humane.aibus.CanTranslateResponse";
    pub const CHAT_COMPLETION_REQUEST: &str = "humane.aibus.ChatCompletionRequest";
    pub const CHAT_COMPLETION_RESPONSE: &str = "humane.aibus.ChatCompletionResponse";
    pub const COMPLETION_REQUEST: &str = "humane.aibus.CompletionRequest";
    pub const COMPLETION_RESPONSE: &str = "humane.aibus.CompletionResponse";
    pub const CONTACT: &str = "humane.contacts.Contact";
    pub const FOOD_LOG_SUMMARY: &str = "humane.common.food.FoodLogSummary";
    pub const FUNCTION_CALL: &str = "humane.aibus.FunctionCall";
    pub const FUNCTION_RESPONSE: &str = "humane.aibus.FunctionResponse";
    pub const GEO_LOCATE_REQUEST: &str = "humane.aibus.GeoLocateRequest";
    pub const GEO_LOCATE_RESPONSE: &str = "humane.aibus.GeoLocateResponse";
    pub const GET_FOOD_ITEM_REQUEST: &str = "humane.aibus.GetFoodItemRequest";
    pub const GET_FOOD_ITEM_RESPONSE: &str = "humane.aibus.GetFoodItemResponse";
    pub const LOADING_MESSAGE_REQUEST: &str = "humane.aibus.LoadingMessageRequest";
    pub const LOADING_MESSAGE_RESPONSE: &str = "humane.aibus.LoadingMessageResponse";
    pub const LOCATION_ENVELOPE: &str = "humane.common.encryption.LocationEnvelope";
    pub const MESSAGE_COMPOSITION_REQUEST: &str = "humane.aibus.MessageCompositionRequest";
    pub const MESSAGE_COMPOSITION_RESPONSE: &str = "humane.aibus.MessageCompositionResponse";
    pub const NAVIGATION_DIRECTIONS_REQUEST: &str = "humane.aibus.NavigationDirectionsRequest";
    pub const NAVIGATION_DIRECTIONS_RESPONSE: &str = "humane.aibus.NavigationDirectionsResponse";
    pub const NEARBY_SEARCH_REQUEST: &str = "humane.aibus.NearbySearchRequest";
    pub const NEARBY_SEARCH_RESPONSE: &str = "humane.aibus.NearbySearchResponse";
    pub const REVERSE_GEOCODE_RESPONSE: &str = "humane.aibus.ReverseGeocodeResponse";
    pub const SERVER_STATEFUL_UNDERSTAND_REQUEST: &str =
        "humane.aibus.ServerStatefulUnderstandRequest";
    pub const SERVER_STATEFUL_UNDERSTAND_RESPONSE: &str =
        "humane.aibus.ServerStatefulUnderstandResponse";
    pub const SMART_PLAYLIST_REQUEST: &str = "humane.aibus.SmartPlaylistRequest";
    pub const SMART_PLAYLIST_RESPONSE: &str = "humane.aibus.SmartPlaylistResponse";
    pub const STREAMING_UNDERSTAND_REQUEST: &str = "humane.aibus.StreamingUnderstandRequest";
    pub const STREAMING_UNDERSTAND_RESPONSE: &str = "humane.aibus.StreamingUnderstandResponse";
    pub const SUMMARIZATION_NETWORK_REQUEST: &str = "humane.aibus.SummarizationNetworkRequest";
    pub const SUMMARIZATION_NETWORK_RESPONSE: &str = "humane.aibus.SummarizationNetworkResponse";
    pub const SYNAPSE_UNDERSTANDING_REQUEST: &str = "humane.aibus.SynapseUnderstandingRequest";
    pub const SYNAPSE_UNDERSTANDING_RESPONSE: &str = "humane.aibus.SynapseUnderstandingResponse";
    pub const TEXT_TO_SPEECH_REQUEST: &str = "humane.aibus.TextToSpeechRequest";
    pub const TEXT_TO_SPEECH_RESPONSE: &str = "humane.aibus.TextToSpeechResponse";
    pub const TRANSLATE_CONVERSATION_REQUEST: &str = "humane.aibus.TranslateConversationRequest";
    pub const TRANSLATE_CONVERSATION_RESPONSE: &str = "humane.aibus.TranslateConversationResponse";
    pub const TRANSLATE_TEXT_REQUEST: &str = "humane.aibus.TranslateTextRequest";
    pub const TRANSLATE_TEXT_RESPONSE: &str = "humane.aibus.TranslateTextResponse";
    pub const WEATHER_RESPONSE: &str = "humane.aibus.WeatherResponse";

    pub const ALL: &[&str] = &[
        ACTION_BASED_INTERSTITIAL_REQUEST,
        ACTION_BASED_INTERSTITIAL_RESPONSE,
        AI_REQUEST,
        AI_RESPONSE,
        ANALYZE_FOOD_IMAGE_REQUEST,
        ANALYZE_FOOD_IMAGE_RESPONSE,
        ANALYZE_IMAGE_RESPONSE,
        CAN_TRANSLATE_REQUEST,
        CAN_TRANSLATE_RESPONSE,
        CHAT_COMPLETION_REQUEST,
        CHAT_COMPLETION_RESPONSE,
        COMPLETION_REQUEST,
        COMPLETION_RESPONSE,
        CONTACT,
        FOOD_LOG_SUMMARY,
        FUNCTION_CALL,
        FUNCTION_RESPONSE,
        GEO_LOCATE_REQUEST,
        GEO_LOCATE_RESPONSE,
        GET_FOOD_ITEM_REQUEST,
        GET_FOOD_ITEM_RESPONSE,
        LOADING_MESSAGE_REQUEST,
        LOADING_MESSAGE_RESPONSE,
        LOCATION_ENVELOPE,
        MESSAGE_COMPOSITION_REQUEST,
        MESSAGE_COMPOSITION_RESPONSE,
        NAVIGATION_DIRECTIONS_REQUEST,
        NAVIGATION_DIRECTIONS_RESPONSE,
        NEARBY_SEARCH_REQUEST,
        NEARBY_SEARCH_RESPONSE,
        REVERSE_GEOCODE_RESPONSE,
        SERVER_STATEFUL_UNDERSTAND_REQUEST,
        SERVER_STATEFUL_UNDERSTAND_RESPONSE,
        SMART_PLAYLIST_REQUEST,
        SMART_PLAYLIST_RESPONSE,
        STREAMING_UNDERSTAND_REQUEST,
        STREAMING_UNDERSTAND_RESPONSE,
        SUMMARIZATION_NETWORK_REQUEST,
        SUMMARIZATION_NETWORK_RESPONSE,
        SYNAPSE_UNDERSTANDING_REQUEST,
        SYNAPSE_UNDERSTANDING_RESPONSE,
        TEXT_TO_SPEECH_REQUEST,
        TEXT_TO_SPEECH_RESPONSE,
        TRANSLATE_CONVERSATION_REQUEST,
        TRANSLATE_CONVERSATION_RESPONSE,
        TRANSLATE_TEXT_REQUEST,
        TRANSLATE_TEXT_RESPONSE,
        WEATHER_RESPONSE,
    ];
}

pub mod wire_sentinels {
    pub const PLAINTEXT_ENVELOPE: &str = "plaintext";

    pub const ALL: &[&str] = &[PLAINTEXT_ENVELOPE];
}

pub mod binder {
    pub mod ai_bus_bridge {
        pub const DESCRIPTOR: &str = "humane.aibus.IAiBusBridge";
        pub const TRANSACTION_ANALYZE_IMAGE: i32 = 1;
        pub const WIRE_NAME_ANALYZE_IMAGE: &str = "analyzeImage";
        pub const TRANSACTION_SYNAPSE_UNDERSTANDING: i32 = 2;
        pub const WIRE_NAME_SYNAPSE_UNDERSTANDING: &str = "synapseUnderstanding";
        pub const TRANSACTION_ENCRYPTED_SMART_PLAYLIST: i32 = 3;
        pub const WIRE_NAME_ENCRYPTED_SMART_PLAYLIST: &str = "encryptedSmartPlaylist";
        pub const TRANSACTION_CAN_TRANSLATE: i32 = 4;
        pub const WIRE_NAME_CAN_TRANSLATE: &str = "canTranslate";
        pub const TRANSACTION_TRANSLATE_TEXT: i32 = 5;
        pub const WIRE_NAME_TRANSLATE_TEXT: &str = "translateText";
        pub const TRANSACTION_TRANSLATE_CONVERSATION: i32 = 6;
        pub const WIRE_NAME_TRANSLATE_CONVERSATION: &str = "translateConversation";
        pub const TRANSACTION_STREAM_AI_BUS: i32 = 7;
        pub const WIRE_NAME_STREAM_AI_BUS: &str = "streamAIBus";
        pub const TRANSACTION_FETCH_HOME_SCREEN_WEATHER: i32 = 8;
        pub const WIRE_NAME_FETCH_HOME_SCREEN_WEATHER: &str = "fetchHomeScreenWeather";
        pub const TRANSACTION_ENCRYPTED_NEARBY_SEARCH: i32 = 9;
        pub const WIRE_NAME_ENCRYPTED_NEARBY_SEARCH: &str = "encryptedNearbySearch";
        pub const TRANSACTION_ENCRYPTED_GEO_LOCATE_REQUEST: i32 = 10;
        pub const WIRE_NAME_ENCRYPTED_GEO_LOCATE_REQUEST: &str = "encryptedGeoLocateRequest";
        pub const TRANSACTION_CHAT_COMPLETION: i32 = 11;
        pub const WIRE_NAME_CHAT_COMPLETION: &str = "chatCompletion";
        pub const TRANSACTION_GENERATE_INTERSTITIAL: i32 = 12;
        pub const WIRE_NAME_GENERATE_INTERSTITIAL: &str = "generateInterstitial";
        pub const TRANSACTION_NAVIGATION_DIRECTIONS: i32 = 13;
        pub const WIRE_NAME_NAVIGATION_DIRECTIONS: &str = "navigationDirections";
        pub const TRANSACTION_TEXT_TO_SPEECH: i32 = 14;
        pub const WIRE_NAME_TEXT_TO_SPEECH: &str = "textToSpeech";
        pub const TRANSACTION_STREAMING_TEXT_TO_SPEECH: i32 = 15;
        pub const WIRE_NAME_STREAMING_TEXT_TO_SPEECH: &str = "streamingTextToSpeech";
        pub const TRANSACTION_EXECUTE_FUNCTION_CALL: i32 = 16;
        pub const WIRE_NAME_EXECUTE_FUNCTION_CALL: &str = "executeFunctionCall";
        pub const TRANSACTION_SERVER_STATEFUL_UNDERSTAND: i32 = 17;
        pub const WIRE_NAME_SERVER_STATEFUL_UNDERSTAND: &str = "serverStatefulUnderstand";
        pub const TRANSACTION_BIDIRECTIONAL_STREAMING_UNDERSTAND: i32 = 18;
        pub const WIRE_NAME_BIDIRECTIONAL_STREAMING_UNDERSTAND: &str =
            "bidirectionalStreamingUnderstand";
    }

    pub mod penumbra_feature_flag_apply_ack {
        pub const DESCRIPTOR: &str = "com.penumbraos.server.feature-flag-apply-ack.bridge.v1";
        pub const TRANSACTION_RECORD_APPLIED: i32 = 1;
        pub const WIRE_NAME_RECORD_APPLIED: &str = "recordApplied";
    }

    pub mod penumbra_fitness {
        pub const DESCRIPTOR: &str = "com.penumbraos.server.fitness.bridge.v2";
        pub const TRANSACTION_BEGIN_SESSION: i32 = 1;
        pub const WIRE_NAME_BEGIN_SESSION: &str = "beginSession";
        pub const TRANSACTION_FINISH_SESSION: i32 = 2;
        pub const WIRE_NAME_FINISH_SESSION: &str = "finishSession";
        pub const TRANSACTION_ABORT_SESSION: i32 = 3;
        pub const WIRE_NAME_ABORT_SESSION: &str = "abortSession";
    }

    pub mod penumbra_message_status {
        pub const DESCRIPTOR: &str = "com.penumbraos.server.message-status.bridge.v1";
        pub const TRANSACTION_RECORD_DELIVERED: i32 = 1;
        pub const WIRE_NAME_RECORD_DELIVERED: &str = "recordDelivered";
    }

    pub mod penumbra_spotify {
        pub const DESCRIPTOR: &str = "com.penumbraos.server.spotify.bridge.v1";
        pub const TRANSACTION_QUERY: i32 = 1;
        pub const WIRE_NAME_QUERY: &str = "query";
        pub const TRANSACTION_PLAYBACK: i32 = 2;
        pub const WIRE_NAME_PLAYBACK: &str = "playback";
        pub const TRANSACTION_SAVE: i32 = 3;
        pub const WIRE_NAME_SAVE: &str = "save";
    }

    pub mod stream_observer {
        pub const DESCRIPTOR: &str = "humane.grpc.IStreamObserver";
        pub const TRANSACTION_ON_NEXT: i32 = 1;
        pub const WIRE_NAME_ON_NEXT: &str = "onNext";
        pub const TRANSACTION_ON_ERROR: i32 = 2;
        pub const WIRE_NAME_ON_ERROR: &str = "onError";
        pub const TRANSACTION_ON_COMPLETED: i32 = 3;
        pub const WIRE_NAME_ON_COMPLETED: &str = "onCompleted";
    }
}

pub mod feature_flags {
    pub mod cloud {
        pub const ACCESSORY_FEATURE_FLAGS: &str = "accessory_feature_flags";
        pub const CMU_ULTRA_CHIME_ENABLED: &str = "cmu_ultra_chime_enabled";
        pub const CMU_ULTRA_ENABLED: &str = "cmu_ultra_enabled";
        pub const ESIM_QR_SCANNER_ENABLED: &str = "esim_qr_scanner_enabled";
        pub const FEATURE_FLAG_SUPPRESS_SYNC_ON_STARTUP: &str =
            "feature_flag_suppress_sync_on_startup";
        pub const FITNESS_TRACKER_ENABLED: &str = "fitness_tracker_enabled";
        pub const FITNESS_TRACKER_EXTRA_DATA_ENABLED: &str = "fitness_tracker_extra_data_enabled";
        pub const LASER_FINDING_GUIDE: &str = "laser_finding_guide";
        pub const MUSIC_INTERSTITIALS_ENABLED: &str = "music_interstitials_enabled";
        pub const NETWORK_RESET_ENABLED: &str = "network_reset_enabled";
        pub const QUICK_ACTIONS_REMAPPING_ENABLED: &str = "quick_actions_remapping_enabled";
        pub const SERVER_SIDE_SPEECH_SYNTHESIS_STREAMING_ENABLED: &str =
            "server_side_speech_synthesis_streaming_enabled";
        pub const SERVER_SIDE_SPEECH_SYNTHESIS_TIMEOUT_MILLIS: &str =
            "server_side_speech_synthesis_timeout_millis";
        pub const SERVER_SIDE_SPEECH_SYNTHESIS_VOICE_NAME: &str =
            "server_side_speech_synthesis_voice_name";
        pub const SERVER_SIDE_TRANSCRIPTION_SAVE_ENABLED: &str =
            "server_side_transcription_save_enabled";
        pub const SYNAPSE_BIDIRECTIONAL_STREAMING: &str = "synapse_bidirectional_streaming";
        pub const TICKLE: &str = "tickle";
        pub const TOUCHCODE_TIMEOUT_MILLIS: &str = "touchcode_timeout_millis";
        pub const VISION_ACTIONS_ENABLED: &str = "vision_actions_enabled";
        pub const VISION_CUSTOM_GESTURE_ENABLED: &str = "vision_custom_gesture_enabled";

        pub const ALL: &[&str] = &[
            ACCESSORY_FEATURE_FLAGS,
            CMU_ULTRA_CHIME_ENABLED,
            CMU_ULTRA_ENABLED,
            ESIM_QR_SCANNER_ENABLED,
            FEATURE_FLAG_SUPPRESS_SYNC_ON_STARTUP,
            FITNESS_TRACKER_ENABLED,
            FITNESS_TRACKER_EXTRA_DATA_ENABLED,
            LASER_FINDING_GUIDE,
            MUSIC_INTERSTITIALS_ENABLED,
            NETWORK_RESET_ENABLED,
            QUICK_ACTIONS_REMAPPING_ENABLED,
            SERVER_SIDE_SPEECH_SYNTHESIS_STREAMING_ENABLED,
            SERVER_SIDE_SPEECH_SYNTHESIS_TIMEOUT_MILLIS,
            SERVER_SIDE_SPEECH_SYNTHESIS_VOICE_NAME,
            SERVER_SIDE_TRANSCRIPTION_SAVE_ENABLED,
            SYNAPSE_BIDIRECTIONAL_STREAMING,
            TICKLE,
            TOUCHCODE_TIMEOUT_MILLIS,
            VISION_ACTIONS_ENABLED,
            VISION_CUSTOM_GESTURE_ENABLED,
        ];
    }

    pub mod settings_global {
        pub const CLOCK_ENABLED: &str = "humane_clock_enabled";
        pub const CMU_ULTRA_ENABLED: &str = "humane_cmu_ultra_enabled";
        pub const FOOD_ENABLED: &str = "humane_food_enabled";
        pub const HEALTH_TRACKER_ENABLED: &str = "humane_health_tracker_enabled";
        pub const PHOTO_SHARING_ENABLED: &str = "humane_photo_sharing_enabled";
        pub const PHOTOGRAPHY_JPG_ENABLED: &str = "humane_photography_jpg_enabled";

        pub const ALL: &[&str] = &[
            CLOCK_ENABLED,
            CMU_ULTRA_ENABLED,
            FOOD_ENABLED,
            HEALTH_TRACKER_ENABLED,
            PHOTO_SHARING_ENABLED,
            PHOTOGRAPHY_JPG_ENABLED,
        ];
    }

    pub mod penumbra_settings_global {
        pub const WEATHER_CELSIUS: &str = "penumbra_weather_celsius";

        pub const ALL: &[&str] = &[WEATHER_CELSIUS];
    }

    pub mod luma_settings_global {
        pub const ROOT_ACCESS_ENABLED: &str = "luma_root_access_enabled";

        pub const ALL: &[&str] = &[ROOT_ACCESS_ENABLED];
    }
}

pub mod operational_markers {
    pub const EXACT_CONTEXT_RESET_AUTHORIZED: &str = "Authorized exact context-reset action";
    pub const HAND_TRACKING_HELD_FOR_NARRATION: &str = "Hand tracking timeout held for narration";
    pub const MUSIC_INTENT_COMPATIBILITY_EMITTED: &str = "Music intent compatibility emitted";
    pub const MUSIC_RANKING_DEGRADED: &str =
        "<<< spotify artist ranking degraded to relevance search";
    pub const NARRATION_END_RELEASED_HOLD: &str = "NARRATION_END released narration hold";
    pub const NARRATION_END_WITHOUT_HAND_TRACKING: &str =
        "NARRATION_END ignored because no active hand tracking session";
    pub const NARRATION_START_WITHOUT_HAND_TRACKING: &str =
        "NARRATION_START ignored because no active hand tracking session";
    pub const NATIVE_ACTION_FOR_PHYSICAL_VERIFICATION: &str =
        "Observed native action for physical verification";
    pub const STOCK_RUN_FINAL_MESSAGE: &str =
        "New turn is a message, so final, allowing dispatch but ending current Run.";
    pub const STOCK_RUN_FINAL_OBSERVATION: &str =
        "New turn is final, allowing dispatch but ending current Run.";
    pub const STREAMING_SPEECH_FAILURE_RELEASED: &str =
        "Streaming speech playback failure released";

    pub const LIVE: &[&str] = &[
        EXACT_CONTEXT_RESET_AUTHORIZED,
        HAND_TRACKING_HELD_FOR_NARRATION,
        MUSIC_INTENT_COMPATIBILITY_EMITTED,
        MUSIC_RANKING_DEGRADED,
        NARRATION_END_RELEASED_HOLD,
        NATIVE_ACTION_FOR_PHYSICAL_VERIFICATION,
        STREAMING_SPEECH_FAILURE_RELEASED,
    ];

    pub const EXTERNAL: &[&str] = &[STOCK_RUN_FINAL_MESSAGE, STOCK_RUN_FINAL_OBSERVATION];

    pub const UNVERIFIED: &[&str] = &[
        NARRATION_END_WITHOUT_HAND_TRACKING,
        NARRATION_START_WITHOUT_HAND_TRACKING,
    ];
}

pub mod native_actions {
    pub const ACCEPT_CALL: &str = "AcceptCall";
    pub const ADD_IF_THEN_ENTRY: &str = "AddIfThenEntry";
    pub const ALARM: &str = "Alarm";
    pub const AM_I_ONLINE: &str = "AmIOnline";
    pub const ASK_CONFIRMATION_FOR_EMERGENCY_CALL: &str = "AskConfirmationForEmergencyCall";
    pub const ASK_CONFIRMATION_FOR_FACTORY_RESET: &str = "AskConfirmationForFactoryReset";
    pub const CALL_PERSON: &str = "CallPerson";
    pub const CANCEL_ALARM: &str = "CancelAlarm";
    pub const CANCEL_SEND_MESSAGE: &str = "CancelSendMessage";
    pub const CAPTURE_PHOTOGRAPH: &str = "CapturePhotograph";
    pub const CAPTURE_VIDEO: &str = "CaptureVideo";
    pub const CATCH_ME_UP: &str = "CatchMeUp";
    pub const CHANGE_QUICK_ACTION: &str = "ChangeQuickAction";
    pub const CLEAR_IF_THEN_MAP: &str = "ClearIfThenMap";
    pub const CLEAR_UNDERSTANDING_CONTEXT: &str = "ClearUnderstandingContext";
    pub const COMPOSE_MESSAGE: &str = "ComposeMessage";
    pub const CONFIRM_SEND_MESSAGE: &str = "ConfirmSendMessage";
    pub const CONNECT_TO_BLUETOOTH: &str = "ConnectToBluetooth";
    pub const CONNECT_TO_WIFI: &str = "ConnectToWifi";
    pub const CONTACTS: &str = "Contacts";
    pub const CREATE_CONTACT: &str = "CreateContact";
    pub const CREATE_MEMORY: &str = "CreateMemory";
    pub const DECREMENT_VOLUME: &str = "DecrementVolume";
    pub const DELETE_TIMER: &str = "DeleteTimer";
    pub const DEVICE_STATUS: &str = "DeviceStatus";
    pub const DEVICE_UNLOCKED: &str = "DeviceUnlocked";
    pub const DISCONNECT_BLUETOOTH: &str = "DisconnectBluetooth";
    pub const DISCONNECT_WIFI: &str = "DisconnectWifi";
    pub const DISPLAY_ALARM: &str = "DisplayAlarm";
    pub const DISPLAY_CONTACT: &str = "DisplayContact";
    pub const DISPLAY_MESSAGES: &str = "DisplayMessages";
    pub const DISPLAY_TIMER: &str = "DisplayTimer";
    pub const EDIT_TIMER: &str = "EditTimer";
    pub const END_CALL: &str = "EndCall";
    pub const ENTER_PRIVACY_MODE: &str = "EnterPrivacyMode";
    pub const EXPERIMENTAL_INTERFACE: &str = "ExperimentalInterface";
    pub const EXPLAIN_FAILURE: &str = "ExplainFailure";
    pub const FACTORY_RESET: &str = "FactoryReset";
    pub const GENERATE_MUSIC_PLAYLIST: &str = "GenerateMusicPlaylist";
    pub const GET_AIRPLANE_MODE_STATUS: &str = "GetAirplaneModeStatus";
    pub const GET_BATTERY_LEVEL: &str = "GetBatteryLevel";
    pub const GET_BLUETOOTH_STATUS: &str = "GetBluetoothStatus";
    pub const GET_CURRENT_LOCATION: &str = "GetCurrentLocation";
    pub const GET_CURRENT_TIME: &str = "GetCurrentTime";
    pub const GET_CURRENT_VOLUME: &str = "GetCurrentVolume";
    pub const GET_IF_THEN_MAP_SIZE: &str = "GetIfThenMapSize";
    pub const GET_MUSIC_QUEUE: &str = "GetMusicQueue";
    pub const GET_NEW_BLUETOOTH_ADDRESS: &str = "GetNewBluetoothAddress";
    pub const GET_PAIRED_BLUETOOTH_ADDRESS: &str = "GetPairedBluetoothAddress";
    pub const GET_PHONE_NUMBER: &str = "GetPhoneNumber";
    pub const GET_QUICK_MESSAGING_PARTICIPANTS: &str = "GetQuickMessagingParticipants";
    pub const GET_SERIAL_NUMBER: &str = "GetSerialNumber";
    pub const HARD_MODERATE: &str = "HardModerate";
    pub const INCREMENT_VOLUME: &str = "IncrementVolume";
    pub const INSTRUCT_UNLOCK: &str = "InstructUnlock";
    pub const INVALID_SUBSCRIPTION: &str = "InvalidSubscription";
    pub const LOCK_DEVICE: &str = "LockDevice";
    pub const MANAGE_MEMORY: &str = "ManageMemory";
    pub const MANAGE_NUTRITION: &str = "ManageNutrition";
    pub const MESSAGE_SEARCH: &str = "MessageSearch";
    pub const MODERATE: &str = "Moderate";
    pub const NARRATE: &str = "Narrate";
    pub const NEXT_TRACK: &str = "NextTrack";
    pub const OPEN_CONTACTS: &str = "OpenContacts";
    pub const OPEN_DIALER_HOME: &str = "OpenDialerHome";
    pub const OPEN_DIALPAD: &str = "OpenDialpad";
    pub const OPEN_MESSAGES_MAIN_MENU: &str = "OpenMessagesMainMenu";
    pub const OPEN_RECENT_CALLS: &str = "OpenRecentCalls";
    pub const OPEN_RECENT_PHOTOS: &str = "OpenRecentPhotos";
    pub const OPEN_TUTORIAL: &str = "OpenTutorial";
    pub const PAUSE_MUSIC: &str = "PauseMusic";
    pub const PAUSE_TIMER: &str = "PauseTimer";
    pub const PLAY_CURRENT_TRACK_RADIO: &str = "PlayCurrentTrackRadio";
    pub const PLAY_FAVORITE_TRACKS: &str = "PlayFavoriteTracks";
    pub const PLAY_FEATURED_MUSIC: &str = "PlayFeaturedMusic";
    pub const PLAY_MUSIC: &str = "PlayMusic";
    pub const PLAY_RECOMMENDATIONS_WITH_TRACK_ID: &str = "PlayRecommendationsWithTrackId";
    pub const PLAY_SOUND: &str = "PlaySound";
    pub const PRESENT_INCOMING_MESSAGE_ACTION: &str = "PresentIncomingMessageAction";
    pub const PREVIOUS_BUTTON: &str = "PreviousButton";
    pub const PREVIOUS_TRACK: &str = "PreviousTrack";
    pub const READ_ALL_MESSAGES: &str = "ReadAllMessages";
    pub const REBOOT: &str = "Reboot";
    pub const RESPOND: &str = "Respond";
    pub const RESTART_TRACK: &str = "RestartTrack";
    pub const RESUME_CALL: &str = "ResumeCall";
    pub const RESUME_MUSIC: &str = "ResumeMusic";
    pub const RESUME_TIMER: &str = "ResumeTimer";
    pub const SAVE_CURRENT_TRACK_TO_FAVORITES: &str = "SaveCurrentTrackToFavorites";
    pub const SEARCH_CONTACT: &str = "SearchContact";
    pub const SET_ALARM: &str = "SetAlarm";
    pub const SET_DEFAULT_TRANSLATE_LANGUAGE: &str = "SetDefaultTranslateLanguage";
    pub const SET_QUICK_MESSAGING_CONTACT: &str = "SetQuickMessagingContact";
    pub const SET_TIMER: &str = "SetTimer";
    pub const SET_UP_TOUCHCODE: &str = "SetUpTouchcode";
    pub const SET_VOLUME: &str = "SetVolume";
    pub const SETTINGS: &str = "Settings";
    pub const SHOW_ERROR: &str = "ShowError";
    pub const START_ACTIVITY_TRACKER: &str = "StartActivityTracker";
    pub const START_TRANSLATION: &str = "StartTranslation";
    pub const STOP_ACTIVITY_TRACKER: &str = "StopActivityTracker";
    pub const STOP_TRANSLATION: &str = "StopTranslation";
    pub const STOP_VIDEO: &str = "StopVideo";
    pub const SYSTEM_TRACE_START: &str = "SystemTraceStart";
    pub const SYSTEM_TRACE_STOP: &str = "SystemTraceStop";
    pub const THERMAL_WARNING: &str = "ThermalWarning";
    pub const TICKLE: &str = "Tickle";
    pub const TIMER: &str = "Timer";
    pub const TRANSLATE: &str = "Translate";
    pub const TRIGGER_BUG_REPORT: &str = "TriggerBugReport";
    pub const TRUST_LOCK: &str = "TrustLock";
    pub const TURN_OFF_AIRPLANE_MODE: &str = "TurnOffAirplaneMode";
    pub const TURN_OFF_AMBER_ALERT: &str = "TurnOffAmberAlert";
    pub const TURN_OFF_BLUETOOTH: &str = "TurnOffBluetooth";
    pub const TURN_OFF_CELLULAR_DATA: &str = "TurnOffCellularData";
    pub const TURN_OFF_CELLULAR_ROAMING: &str = "TurnOffCellularRoaming";
    pub const TURN_OFF_DEVICE: &str = "TurnOffDevice";
    pub const TURN_OFF_EMERGENCY_ALERT: &str = "TurnOffEmergencyAlert";
    pub const TURN_OFF_PUBLIC_SAFETY_ALERT: &str = "TurnOffPublicSafetyAlert";
    pub const TURN_OFF_WIFI: &str = "TurnOffWifi";
    pub const TURN_ON_AIRPLANE_MODE: &str = "TurnOnAirplaneMode";
    pub const TURN_ON_AMBER_ALERT: &str = "TurnOnAmberAlert";
    pub const TURN_ON_BLUETOOTH: &str = "TurnOnBluetooth";
    pub const TURN_ON_CELLULAR_DATA: &str = "TurnOnCellularData";
    pub const TURN_ON_CELLULAR_ROAMING: &str = "TurnOnCellularRoaming";
    pub const TURN_ON_EMERGENCY_ALERT: &str = "TurnOnEmergencyAlert";
    pub const TURN_ON_PUBLIC_SAFETY_ALERT: &str = "TurnOnPublicSafetyAlert";
    pub const TURN_ON_WIFI: &str = "TurnOnWifi";
    pub const UNAUTHORIZED_DEVICE: &str = "UnauthorizedDevice";
    pub const UNDERSTAND_SCENE: &str = "UnderstandScene";
    pub const UPDATE_CONTACT_TRUSTED: &str = "UpdateContactTrusted";
    pub const USER_CONFIRMED_EMERGENCY_CALL: &str = "UserConfirmedEmergencyCall";
    pub const USER_CONFIRMED_FACTORY_RESET: &str = "UserConfirmedFactoryReset";
    pub const USER_DENIED_EMERGENCY_CALL: &str = "UserDeniedEmergencyCall";
    pub const USER_DENIED_FACTORY_RESET: &str = "UserDeniedFactoryReset";
    pub const VIEW_CALL_LOG: &str = "ViewCallLog";
    pub const WIFI_QR_SCAN: &str = "WifiQrScan";
    pub const WORLD_CLOCK: &str = "WorldClock";

    pub const ALL: &[&str] = &[
        ACCEPT_CALL,
        ADD_IF_THEN_ENTRY,
        ALARM,
        AM_I_ONLINE,
        ASK_CONFIRMATION_FOR_EMERGENCY_CALL,
        ASK_CONFIRMATION_FOR_FACTORY_RESET,
        CALL_PERSON,
        CANCEL_ALARM,
        CANCEL_SEND_MESSAGE,
        CAPTURE_PHOTOGRAPH,
        CAPTURE_VIDEO,
        CATCH_ME_UP,
        CHANGE_QUICK_ACTION,
        CLEAR_IF_THEN_MAP,
        CLEAR_UNDERSTANDING_CONTEXT,
        COMPOSE_MESSAGE,
        CONFIRM_SEND_MESSAGE,
        CONNECT_TO_BLUETOOTH,
        CONNECT_TO_WIFI,
        CONTACTS,
        CREATE_CONTACT,
        CREATE_MEMORY,
        DECREMENT_VOLUME,
        DELETE_TIMER,
        DEVICE_STATUS,
        DEVICE_UNLOCKED,
        DISCONNECT_BLUETOOTH,
        DISCONNECT_WIFI,
        DISPLAY_ALARM,
        DISPLAY_CONTACT,
        DISPLAY_MESSAGES,
        DISPLAY_TIMER,
        EDIT_TIMER,
        END_CALL,
        ENTER_PRIVACY_MODE,
        EXPERIMENTAL_INTERFACE,
        EXPLAIN_FAILURE,
        FACTORY_RESET,
        GENERATE_MUSIC_PLAYLIST,
        GET_AIRPLANE_MODE_STATUS,
        GET_BATTERY_LEVEL,
        GET_BLUETOOTH_STATUS,
        GET_CURRENT_LOCATION,
        GET_CURRENT_TIME,
        GET_CURRENT_VOLUME,
        GET_IF_THEN_MAP_SIZE,
        GET_MUSIC_QUEUE,
        GET_NEW_BLUETOOTH_ADDRESS,
        GET_PAIRED_BLUETOOTH_ADDRESS,
        GET_PHONE_NUMBER,
        GET_QUICK_MESSAGING_PARTICIPANTS,
        GET_SERIAL_NUMBER,
        HARD_MODERATE,
        INCREMENT_VOLUME,
        INSTRUCT_UNLOCK,
        INVALID_SUBSCRIPTION,
        LOCK_DEVICE,
        MANAGE_MEMORY,
        MANAGE_NUTRITION,
        MESSAGE_SEARCH,
        MODERATE,
        NARRATE,
        NEXT_TRACK,
        OPEN_CONTACTS,
        OPEN_DIALER_HOME,
        OPEN_DIALPAD,
        OPEN_MESSAGES_MAIN_MENU,
        OPEN_RECENT_CALLS,
        OPEN_RECENT_PHOTOS,
        OPEN_TUTORIAL,
        PAUSE_MUSIC,
        PAUSE_TIMER,
        PLAY_CURRENT_TRACK_RADIO,
        PLAY_FAVORITE_TRACKS,
        PLAY_FEATURED_MUSIC,
        PLAY_MUSIC,
        PLAY_RECOMMENDATIONS_WITH_TRACK_ID,
        PLAY_SOUND,
        PRESENT_INCOMING_MESSAGE_ACTION,
        PREVIOUS_BUTTON,
        PREVIOUS_TRACK,
        READ_ALL_MESSAGES,
        REBOOT,
        RESPOND,
        RESTART_TRACK,
        RESUME_CALL,
        RESUME_MUSIC,
        RESUME_TIMER,
        SAVE_CURRENT_TRACK_TO_FAVORITES,
        SEARCH_CONTACT,
        SET_ALARM,
        SET_DEFAULT_TRANSLATE_LANGUAGE,
        SET_QUICK_MESSAGING_CONTACT,
        SET_TIMER,
        SET_UP_TOUCHCODE,
        SET_VOLUME,
        SETTINGS,
        SHOW_ERROR,
        START_ACTIVITY_TRACKER,
        START_TRANSLATION,
        STOP_ACTIVITY_TRACKER,
        STOP_TRANSLATION,
        STOP_VIDEO,
        SYSTEM_TRACE_START,
        SYSTEM_TRACE_STOP,
        THERMAL_WARNING,
        TICKLE,
        TIMER,
        TRANSLATE,
        TRIGGER_BUG_REPORT,
        TRUST_LOCK,
        TURN_OFF_AIRPLANE_MODE,
        TURN_OFF_AMBER_ALERT,
        TURN_OFF_BLUETOOTH,
        TURN_OFF_CELLULAR_DATA,
        TURN_OFF_CELLULAR_ROAMING,
        TURN_OFF_DEVICE,
        TURN_OFF_EMERGENCY_ALERT,
        TURN_OFF_PUBLIC_SAFETY_ALERT,
        TURN_OFF_WIFI,
        TURN_ON_AIRPLANE_MODE,
        TURN_ON_AMBER_ALERT,
        TURN_ON_BLUETOOTH,
        TURN_ON_CELLULAR_DATA,
        TURN_ON_CELLULAR_ROAMING,
        TURN_ON_EMERGENCY_ALERT,
        TURN_ON_PUBLIC_SAFETY_ALERT,
        TURN_ON_WIFI,
        UNAUTHORIZED_DEVICE,
        UNDERSTAND_SCENE,
        UPDATE_CONTACT_TRUSTED,
        USER_CONFIRMED_EMERGENCY_CALL,
        USER_CONFIRMED_FACTORY_RESET,
        USER_DENIED_EMERGENCY_CALL,
        USER_DENIED_FACTORY_RESET,
        VIEW_CALL_LOG,
        WIFI_QR_SCAN,
        WORLD_CLOCK,
    ];
}
