//! GENERATED — do not edit by hand.
//!
//! The stock device action interface: every `nameForModel` the pin's
//! `SchemaCatalog` resolves, with the model-facing parameter fields, their
//! types, and their required-ness, plus `@Action(enabledInKeyguard=…)` and the
//! owning experience.
//!
//! Regenerate with:
//!   node <operator-evidence-archive>/sew-action-catalog.mjs <evidence-dir> \
//!     --native <native-actions.tsv> --out crates/cosmos/src/assistant/catalog_generated.rs
//!
//! This table is INTERFACE ONLY — action/field names, types, required-ness.
//! It contains no prompt text and no description prose; every description the
//! model sees is authored by us in `catalog.rs`. A Pin only resolves an action
//! whose name and argument keys match this contract exactly, which is why the
//! clone mirrors it.
//!
//! Stats: 138 actions, 78 model-facing fields, 99 keyguard-enabled, 138 cross-validated against an independent recovery.

/// JSON-schema type of a model-facing parameter.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum FieldType {
    String,
    Number,
    Boolean,
    StringList,
}

/// One model-facing parameter of a device action.
#[derive(Clone, Copy, Debug)]
pub struct DeviceField {
    pub name: &'static str,
    pub ty: FieldType,
    pub required: bool,
    /// Values the device will deserialize this slot into, from the experience's
    /// own SerialName declarations. Anything else fails to parse on the pin.
    pub enum_values: &'static [&'static str],
}

/// A device action the pin can resolve and execute.
#[derive(Clone, Copy, Debug)]
pub struct DeviceAction {
    /// `nameForModel` — the exact string that rides in `SynapseActionContent.action`.
    pub name: &'static str,
    /// Owning experience (routing hint; not part of the wire contract).
    pub experience: &'static str,
    /// `@Action(enabledInKeyguard=…)` — runs while the pin is locked.
    pub keyguard: bool,
    /// Present in the pin's CENTRAL `SchemaCatalog`. Only these can be
    /// dispatched by the server; anything else belongs to a sub-agent and is
    /// rejected with "Unrecognized function name and/or arguments".
    pub central: bool,
    /// DEVICE_ONLY_BOOLEAN slots the device unboxes unguarded. The model never
    /// sees them, but the server must set them or the experience NPEs.
    pub device_booleans: &'static [&'static str],
    pub fields: &'static [DeviceField],
}

/// Every recovered device action, sorted by name.
pub const DEVICE_ACTIONS: &[DeviceAction] = &[
    DeviceAction {
        name: "AcceptCall",
        experience: "DIALER",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "AddIfThenEntry",
        experience: "CENTRAL",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[
            DeviceField {
                name: "If",
                ty: FieldType::String,
                required: false,
                enum_values: &[],
            },
            DeviceField {
                name: "Then",
                ty: FieldType::String,
                required: false,
                enum_values: &[],
            },
        ],
    },
    DeviceAction {
        name: "Alarm",
        experience: "CLOCK",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[
            DeviceField {
                name: "Request",
                ty: FieldType::String,
                required: false,
                enum_values: &[],
            },
            DeviceField {
                name: "Terminal",
                ty: FieldType::Boolean,
                required: false,
                enum_values: &[],
            },
        ],
    },
    DeviceAction {
        name: "AmIOnline",
        experience: "CENTRAL",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "AskConfirmationForEmergencyCall",
        experience: "DIALER",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "AskConfirmationForFactoryReset",
        experience: "CENTRAL",
        keyguard: false,
        central: false,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "CallPerson",
        experience: "DIALER",
        keyguard: false,
        central: true,
        device_booleans: &[],
        fields: &[DeviceField {
            name: "To",
            ty: FieldType::StringList,
            required: false,
            enum_values: &[],
        }],
    },
    DeviceAction {
        name: "CancelAlarm",
        experience: "CLOCK",
        keyguard: true,
        central: false,
        device_booleans: &[],
        fields: &[DeviceField {
            name: "id",
            ty: FieldType::String,
            required: false,
            enum_values: &[],
        }],
    },
    DeviceAction {
        name: "CancelSendMessage",
        experience: "MESSAGES",
        keyguard: false,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "CapturePhotograph",
        experience: "PHOTOGRAPHY",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "CaptureVideo",
        experience: "PHOTOGRAPHY",
        keyguard: true,
        central: true,
        device_booleans: &["TriggeredFromTouchpad"],
        fields: &[],
    },
    DeviceAction {
        name: "CatchMeUp",
        experience: "NOTIFICATIONS",
        keyguard: false,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "ChangeQuickAction",
        experience: "AGENT_SETTINGS",
        keyguard: true,
        central: true,
        device_booleans: &["shouldRespondToChange"],
        fields: &[DeviceField {
            name: "action",
            ty: FieldType::String,
            required: false,
            enum_values: &[],
        }],
    },
    DeviceAction {
        name: "ClearIfThenMap",
        experience: "CENTRAL",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "ClearUnderstandingContext",
        experience: "CENTRAL",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "ComposeMessage",
        experience: "MESSAGES",
        keyguard: false,
        central: true,
        device_booleans: &["EnableAutoSend"],
        fields: &[
            DeviceField {
                name: "To",
                ty: FieldType::StringList,
                required: false,
                enum_values: &[],
            },
            DeviceField {
                name: "Message",
                ty: FieldType::String,
                required: false,
                enum_values: &[],
            },
        ],
    },
    DeviceAction {
        name: "ConfirmSendMessage",
        experience: "MESSAGES",
        keyguard: false,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "ConnectToBluetooth",
        experience: "AGENT_SETTINGS",
        keyguard: true,
        central: false,
        device_booleans: &[],
        fields: &[DeviceField {
            name: "address",
            ty: FieldType::String,
            required: false,
            enum_values: &[],
        }],
    },
    DeviceAction {
        name: "ConnectToWifi",
        experience: "CENTRAL",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[DeviceField {
            name: "SSID",
            ty: FieldType::String,
            required: false,
            enum_values: &[],
        }],
    },
    DeviceAction {
        name: "Contacts",
        experience: "CONTACTS",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[
            DeviceField {
                name: "Request",
                ty: FieldType::String,
                required: false,
                enum_values: &[],
            },
            DeviceField {
                name: "Terminal",
                ty: FieldType::Boolean,
                required: false,
                enum_values: &[],
            },
        ],
    },
    DeviceAction {
        name: "CreateContact",
        experience: "CONTACTS",
        keyguard: false,
        central: true,
        device_booleans: &[],
        fields: &[
            DeviceField {
                name: "firstName",
                ty: FieldType::String,
                required: false,
                enum_values: &[],
            },
            DeviceField {
                name: "lastName",
                ty: FieldType::String,
                required: false,
                enum_values: &[],
            },
            DeviceField {
                name: "trusted",
                ty: FieldType::Boolean,
                required: false,
                enum_values: &[],
            },
            DeviceField {
                name: "phoneNumber",
                ty: FieldType::String,
                required: false,
                enum_values: &[],
            },
        ],
    },
    DeviceAction {
        name: "CreateMemory",
        experience: "CENTRAL",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[DeviceField {
            name: "Memory",
            ty: FieldType::String,
            required: false,
            enum_values: &[],
        }],
    },
    DeviceAction {
        name: "DecrementVolume",
        experience: "CENTRAL",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "DeleteTimer",
        experience: "CLOCK",
        keyguard: true,
        central: false,
        device_booleans: &[],
        fields: &[DeviceField {
            name: "id",
            ty: FieldType::String,
            required: false,
            enum_values: &[],
        }],
    },
    DeviceAction {
        name: "DeviceStatus",
        experience: "AGENT_SETTINGS",
        keyguard: false,
        central: false,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "DeviceUnlocked",
        experience: "CENTRAL",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "DisconnectBluetooth",
        experience: "AGENT_SETTINGS",
        keyguard: true,
        central: false,
        device_booleans: &[],
        fields: &[DeviceField {
            name: "address",
            ty: FieldType::String,
            required: false,
            enum_values: &[],
        }],
    },
    DeviceAction {
        name: "DisconnectWifi",
        experience: "CENTRAL",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "DisplayAlarm",
        experience: "CLOCK",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[DeviceField {
            name: "id",
            ty: FieldType::String,
            required: false,
            enum_values: &[],
        }],
    },
    DeviceAction {
        name: "DisplayContact",
        experience: "CONTACTS",
        keyguard: true,
        central: false,
        device_booleans: &[],
        fields: &[DeviceField {
            name: "id",
            ty: FieldType::String,
            required: false,
            enum_values: &[],
        }],
    },
    DeviceAction {
        name: "DisplayMessages",
        experience: "MESSAGES",
        keyguard: false,
        central: true,
        device_booleans: &[],
        fields: &[
            DeviceField {
                name: "IDs",
                ty: FieldType::StringList,
                required: false,
                enum_values: &[],
            },
            DeviceField {
                name: "Person",
                ty: FieldType::StringList,
                required: false,
                enum_values: &[],
            },
            DeviceField {
                name: "MessageCount",
                ty: FieldType::Number,
                required: false,
                enum_values: &[],
            },
        ],
    },
    DeviceAction {
        name: "DisplayTimer",
        experience: "CLOCK",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[DeviceField {
            name: "id",
            ty: FieldType::String,
            required: false,
            enum_values: &[],
        }],
    },
    DeviceAction {
        name: "EditTimer",
        experience: "CLOCK",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[
            DeviceField {
                name: "id",
                ty: FieldType::String,
                required: false,
                enum_values: &[],
            },
            DeviceField {
                name: "secondDuration",
                ty: FieldType::Number,
                required: false,
                enum_values: &[],
            },
            DeviceField {
                name: "minuteDuration",
                ty: FieldType::Number,
                required: false,
                enum_values: &[],
            },
            DeviceField {
                name: "hourDuration",
                ty: FieldType::Number,
                required: false,
                enum_values: &[],
            },
        ],
    },
    DeviceAction {
        name: "EndCall",
        experience: "DIALER",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "EnterPrivacyMode",
        experience: "CENTRAL",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "ExperimentalInterface",
        experience: "UI_GALLERY",
        keyguard: false,
        central: false,
        device_booleans: &[],
        fields: &[DeviceField {
            name: "Any",
            ty: FieldType::String,
            required: false,
            enum_values: &[],
        }],
    },
    DeviceAction {
        name: "ExplainFailure",
        experience: "ANSWERS",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[
            DeviceField {
                name: "Type",
                ty: FieldType::String,
                required: false,
                enum_values: &[],
            },
            DeviceField {
                name: "FailureExplanation",
                ty: FieldType::String,
                required: true,
                enum_values: &[],
            },
        ],
    },
    DeviceAction {
        name: "FactoryReset",
        experience: "CENTRAL",
        keyguard: false,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "GenerateMusicPlaylist",
        experience: "MUSIC",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[DeviceField {
            name: "Playlist",
            ty: FieldType::String,
            required: true,
            enum_values: &[],
        }],
    },
    DeviceAction {
        name: "GetAirplaneModeStatus",
        experience: "CENTRAL",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "GetBatteryLevel",
        experience: "CENTRAL",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "GetBluetoothStatus",
        experience: "CENTRAL",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "GetCurrentLocation",
        experience: "CENTRAL",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "GetCurrentTime",
        experience: "CENTRAL",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "GetCurrentVolume",
        experience: "CENTRAL",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "GetIfThenMapSize",
        experience: "CENTRAL",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "GetMusicQueue",
        experience: "MUSIC",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "GetNewBluetoothAddress",
        experience: "AGENT_SETTINGS",
        keyguard: true,
        central: false,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "GetPairedBluetoothAddress",
        experience: "AGENT_SETTINGS",
        keyguard: true,
        central: false,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "GetPhoneNumber",
        experience: "CENTRAL",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "GetQuickMessagingParticipants",
        experience: "CONTACTS",
        keyguard: false,
        central: false,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "GetSerialNumber",
        experience: "CENTRAL",
        keyguard: false,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "HardModerate",
        experience: "CENTRAL",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "IncrementVolume",
        experience: "CENTRAL",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "InstructUnlock",
        experience: "CENTRAL",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "InvalidSubscription",
        experience: "ANSWERS",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "LockDevice",
        experience: "AGENT_SETTINGS",
        keyguard: false,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "ManageMemory",
        experience: "CENTRAL",
        keyguard: false,
        central: false,
        device_booleans: &[],
        fields: &[DeviceField {
            name: "Task",
            ty: FieldType::String,
            required: false,
            enum_values: &[],
        }],
    },
    DeviceAction {
        name: "ManageNutrition",
        experience: "FOOD",
        keyguard: false,
        central: true,
        device_booleans: &[],
        fields: &[
            DeviceField {
                name: "Request",
                ty: FieldType::String,
                required: false,
                enum_values: &[],
            },
            DeviceField {
                name: "Terminal",
                ty: FieldType::Boolean,
                required: false,
                enum_values: &[],
            },
        ],
    },
    DeviceAction {
        name: "MessageSearch",
        experience: "MESSAGES_BACKGROUND",
        keyguard: false,
        central: true,
        device_booleans: &[],
        fields: &[
            DeviceField {
                name: "Person",
                ty: FieldType::StringList,
                required: false,
                enum_values: &[],
            },
            DeviceField {
                name: "Query",
                ty: FieldType::String,
                required: false,
                enum_values: &[],
            },
        ],
    },
    DeviceAction {
        name: "Moderate",
        experience: "ANSWERS",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[DeviceField {
            name: "Message",
            ty: FieldType::String,
            required: false,
            enum_values: &[],
        }],
    },
    DeviceAction {
        name: "Narrate",
        experience: "CENTRAL",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[DeviceField {
            name: "Narration",
            ty: FieldType::String,
            required: false,
            enum_values: &[],
        }],
    },
    DeviceAction {
        name: "NextTrack",
        experience: "MUSIC",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "OpenContacts",
        experience: "CONTACTS",
        keyguard: false,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "OpenDialerHome",
        experience: "DIALER",
        keyguard: false,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "OpenDialpad",
        experience: "DIALER",
        keyguard: false,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "OpenMessagesMainMenu",
        experience: "MESSAGES",
        keyguard: false,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "OpenRecentCalls",
        experience: "DIALER",
        keyguard: false,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "OpenRecentPhotos",
        experience: "PHOTOGRAPHY",
        keyguard: false,
        central: true,
        device_booleans: &["TriggeredFromTouchpad"],
        fields: &[],
    },
    DeviceAction {
        name: "OpenTutorial",
        experience: "SYSTEM_NAVIGATION",
        keyguard: false,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "PauseMusic",
        experience: "MUSIC",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "PauseTimer",
        experience: "CLOCK",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[DeviceField {
            name: "id",
            ty: FieldType::String,
            required: false,
            enum_values: &[],
        }],
    },
    DeviceAction {
        name: "PlayCurrentTrackRadio",
        experience: "MUSIC",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "PlayFavoriteTracks",
        experience: "MUSIC",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "PlayFeaturedMusic",
        experience: "MUSIC",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "PlayMusic",
        experience: "MUSIC",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[
            DeviceField {
                name: "Artist",
                ty: FieldType::String,
                required: false,
                enum_values: &[],
            },
            DeviceField {
                name: "Album",
                ty: FieldType::String,
                required: false,
                enum_values: &[],
            },
            DeviceField {
                name: "Track",
                ty: FieldType::String,
                required: false,
                enum_values: &[],
            },
            DeviceField {
                name: "Genre",
                ty: FieldType::String,
                required: false,
                enum_values: &[],
            },
            DeviceField {
                name: "Option",
                ty: FieldType::String,
                required: false,
                enum_values: &[],
            },
        ],
    },
    DeviceAction {
        name: "PlayRecommendationsWithTrackId",
        experience: "MUSIC",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[DeviceField {
            name: "TrackID",
            ty: FieldType::String,
            required: true,
            enum_values: &[],
        }],
    },
    DeviceAction {
        name: "PlaySound",
        experience: "CENTRAL",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[DeviceField {
            name: "Reason",
            ty: FieldType::String,
            required: false,
            enum_values: &[],
        }],
    },
    DeviceAction {
        name: "PresentIncomingMessageAction",
        experience: "MESSAGES",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[DeviceField {
            name: "IDs",
            ty: FieldType::StringList,
            required: false,
            enum_values: &[],
        }],
    },
    DeviceAction {
        name: "PreviousButton",
        experience: "MUSIC",
        keyguard: true,
        central: false,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "PreviousTrack",
        experience: "MUSIC",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "ReadAllMessages",
        experience: "MESSAGES",
        keyguard: false,
        central: false,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "Reboot",
        experience: "AGENT_SETTINGS",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "Respond",
        experience: "ANSWERS",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[DeviceField {
            name: "Response",
            ty: FieldType::String,
            required: false,
            enum_values: &[],
        }],
    },
    DeviceAction {
        name: "RestartTrack",
        experience: "MUSIC",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "ResumeCall",
        experience: "DIALER",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "ResumeMusic",
        experience: "MUSIC",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "ResumeTimer",
        experience: "CLOCK",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[DeviceField {
            name: "id",
            ty: FieldType::String,
            required: false,
            enum_values: &[],
        }],
    },
    DeviceAction {
        name: "SaveCurrentTrackToFavorites",
        experience: "MUSIC",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "SearchContact",
        experience: "CONTACTS",
        keyguard: true,
        central: false,
        device_booleans: &[],
        fields: &[
            DeviceField {
                name: "query",
                ty: FieldType::String,
                required: true,
                enum_values: &[],
            },
            DeviceField {
                name: "resolutionType",
                ty: FieldType::String,
                required: false,
                enum_values: &[],
            },
        ],
    },
    DeviceAction {
        name: "SetAlarm",
        experience: "CLOCK",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[
            DeviceField {
                name: "time",
                ty: FieldType::String,
                required: false,
                enum_values: &[],
            },
            DeviceField {
                name: "recurringDays",
                ty: FieldType::StringList,
                required: false,
                enum_values: &[
                    "monday",
                    "tuesday",
                    "wednesday",
                    "thursday",
                    "friday",
                    "saturday",
                    "sunday",
                ],
            },
            DeviceField {
                name: "ampm",
                ty: FieldType::String,
                required: false,
                enum_values: &[],
            },
            DeviceField {
                name: "onceDay",
                ty: FieldType::String,
                required: false,
                enum_values: &["today", "tomorrow"],
            },
        ],
    },
    DeviceAction {
        name: "SetDefaultTranslateLanguage",
        experience: "TRANSLATION",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[DeviceField {
            name: "Language",
            ty: FieldType::String,
            required: true,
            enum_values: &[],
        }],
    },
    DeviceAction {
        name: "SetQuickMessagingContact",
        experience: "CONTACTS",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[DeviceField {
            name: "ids",
            ty: FieldType::StringList,
            required: true,
            enum_values: &[],
        }],
    },
    DeviceAction {
        name: "SetTimer",
        experience: "CLOCK",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[
            DeviceField {
                name: "secondDuration",
                ty: FieldType::Number,
                required: false,
                enum_values: &[],
            },
            DeviceField {
                name: "minuteDuration",
                ty: FieldType::Number,
                required: false,
                enum_values: &[],
            },
            DeviceField {
                name: "hourDuration",
                ty: FieldType::Number,
                required: false,
                enum_values: &[],
            },
            DeviceField {
                name: "name",
                ty: FieldType::String,
                required: false,
                enum_values: &[],
            },
        ],
    },
    DeviceAction {
        name: "Settings",
        experience: "AGENT_SETTINGS",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[
            DeviceField {
                name: "Request",
                ty: FieldType::String,
                required: false,
                enum_values: &[],
            },
            DeviceField {
                name: "Terminal",
                ty: FieldType::Boolean,
                required: false,
                enum_values: &[],
            },
        ],
    },
    DeviceAction {
        name: "SetUpTouchcode",
        experience: "CENTRAL",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "SetVolume",
        experience: "AGENT_SETTINGS",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[DeviceField {
            name: "level",
            ty: FieldType::Number,
            required: false,
            enum_values: &[],
        }],
    },
    DeviceAction {
        name: "ShowError",
        experience: "MUSIC",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[DeviceField {
            name: "Reason",
            ty: FieldType::String,
            required: true,
            enum_values: &[],
        }],
    },
    DeviceAction {
        name: "StartActivityTracker",
        experience: "CENTRAL",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "StartTranslation",
        experience: "TRANSLATION",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "StopActivityTracker",
        experience: "CENTRAL",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "StopTranslation",
        experience: "TRANSLATION",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "StopVideo",
        experience: "PHOTOGRAPHY",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "SystemTraceStart",
        experience: "CENTRAL",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "SystemTraceStop",
        experience: "CENTRAL",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "ThermalWarning",
        experience: "CENTRAL",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "Tickle",
        experience: "TICKLE_PROTOTYPE",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "Timer",
        experience: "CLOCK",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[
            DeviceField {
                name: "Request",
                ty: FieldType::String,
                required: false,
                enum_values: &[],
            },
            DeviceField {
                name: "Terminal",
                ty: FieldType::Boolean,
                required: false,
                enum_values: &[],
            },
        ],
    },
    DeviceAction {
        name: "Translate",
        experience: "TRANSLATION",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[
            DeviceField {
                name: "Text",
                ty: FieldType::String,
                required: false,
                enum_values: &[],
            },
            DeviceField {
                name: "Source",
                ty: FieldType::String,
                required: false,
                enum_values: &[],
            },
            DeviceField {
                name: "Target",
                ty: FieldType::String,
                required: false,
                enum_values: &[],
            },
        ],
    },
    DeviceAction {
        name: "TriggerBugReport",
        experience: "CENTRAL",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[DeviceField {
            name: "Text",
            ty: FieldType::String,
            required: false,
            enum_values: &[],
        }],
    },
    DeviceAction {
        name: "TrustLock",
        experience: "CENTRAL",
        keyguard: false,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "TurnOffAirplaneMode",
        experience: "AGENT_SETTINGS",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "TurnOffAmberAlert",
        experience: "CENTRAL",
        keyguard: false,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "TurnOffBluetooth",
        experience: "AGENT_SETTINGS",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "TurnOffCellularData",
        experience: "CENTRAL",
        keyguard: false,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "TurnOffCellularRoaming",
        experience: "CENTRAL",
        keyguard: false,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "TurnOffDevice",
        experience: "AGENT_SETTINGS",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "TurnOffEmergencyAlert",
        experience: "CENTRAL",
        keyguard: false,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "TurnOffPublicSafetyAlert",
        experience: "CENTRAL",
        keyguard: false,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "TurnOffWifi",
        experience: "AGENT_SETTINGS",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "TurnOnAirplaneMode",
        experience: "AGENT_SETTINGS",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "TurnOnAmberAlert",
        experience: "CENTRAL",
        keyguard: false,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "TurnOnBluetooth",
        experience: "AGENT_SETTINGS",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "TurnOnCellularData",
        experience: "CENTRAL",
        keyguard: false,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "TurnOnCellularRoaming",
        experience: "CENTRAL",
        keyguard: false,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "TurnOnEmergencyAlert",
        experience: "CENTRAL",
        keyguard: false,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "TurnOnPublicSafetyAlert",
        experience: "CENTRAL",
        keyguard: false,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "TurnOnWifi",
        experience: "AGENT_SETTINGS",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "UnauthorizedDevice",
        experience: "ANSWERS",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "UnderstandScene",
        experience: "ANSWERS",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[DeviceField {
            name: "Question",
            ty: FieldType::String,
            required: true,
            enum_values: &[],
        }],
    },
    DeviceAction {
        name: "UpdateContactTrusted",
        experience: "CONTACTS",
        keyguard: true,
        central: false,
        device_booleans: &[],
        fields: &[
            DeviceField {
                name: "id",
                ty: FieldType::String,
                required: false,
                enum_values: &[],
            },
            DeviceField {
                name: "trusted",
                ty: FieldType::Boolean,
                required: false,
                enum_values: &[],
            },
        ],
    },
    DeviceAction {
        name: "UserConfirmedEmergencyCall",
        experience: "DIALER",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "UserConfirmedFactoryReset",
        experience: "CENTRAL",
        keyguard: false,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "UserDeniedEmergencyCall",
        experience: "DIALER",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "UserDeniedFactoryReset",
        experience: "CENTRAL",
        keyguard: false,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "ViewCallLog",
        experience: "DIALER",
        keyguard: false,
        central: false,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "WifiQrScan",
        experience: "CENTRAL",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[],
    },
    DeviceAction {
        name: "WorldClock",
        experience: "CLOCK",
        keyguard: true,
        central: true,
        device_booleans: &[],
        fields: &[DeviceField {
            name: "Location",
            ty: FieldType::String,
            required: false,
            enum_values: &[],
        }],
    },
];

/// Every action the server may dispatch directly.
pub fn central_actions() -> impl Iterator<Item = &'static DeviceAction> {
    DEVICE_ACTIONS.iter().filter(|a| a.central)
}

/// Look up a device action by its `nameForModel`.
pub fn find(name: &str) -> Option<&'static DeviceAction> {
    DEVICE_ACTIONS.iter().find(|a| a.name == name)
}
