@file:Suppress("unused")

package com.penumbraos.stockaibus.contract

/** @generated by platform/containers/pin-builder/tier-a-registry.mjs. Do not edit. */
object TierASymbols {
    object Packages {
        const val BORT = "hu.ma.ne.bort"
        const val BORT_OTA = "hu.ma.ne.bort.ota"
        const val DIALER = "humane.experience.dialer"
        const val ESIM_LPA = "humane.connectivity.esimlpa"
        const val FOOD = "humane.experience.food"
        const val IRONMAN = "hu.ma.ne.ironman"
        const val KRYPTO = "hu.ma.ne.krypto"
        const val MEMFAULT_USAGE_REPORTER = "com.memfault.usagereporter"
        const val MESSAGES = "humane.experience.messages"
        const val METRIC_REPORTER = "hu.ma.ne.metricreporter"
        const val MUSIC = "humane.experience.music"
        const val ONBOARDING = "humane.experience.onboarding"
        const val OTA = "humane.ota"
        const val PHOTOGRAPHY = "humane.experience.photography"
        const val SETTINGS = "humane.experience.settings"
        const val SYSTEM_NAVIGATION = "humane.experience.systemnavigation"
        const val TICKLE = "humane.experience.tickle"
        const val VOICE_TTS = "humane.voice.tts"

        val ALL: Set<String> = setOf(
            BORT,
            BORT_OTA,
            DIALER,
            ESIM_LPA,
            FOOD,
            IRONMAN,
            KRYPTO,
            MEMFAULT_USAGE_REPORTER,
            MESSAGES,
            METRIC_REPORTER,
            MUSIC,
            ONBOARDING,
            OTA,
            PHOTOGRAPHY,
            SETTINGS,
            SYSTEM_NAVIGATION,
            TICKLE,
            VOICE_TTS,
        )
    }

    object RpcPaths {
        const val AIBUS_ENCRYPTED_LOADING_MESSAGE = "/humane.aibus.AIBusService/EncryptedLoadingMessage"
        const val AIBUS_ENCRYPTED_UNDERSTAND = "/humane.aibus.AIBusService/EncryptedUnderstand"
        const val AIBUS_UNDERSTAND = "/humane.aibus.AIBusService/Understand"
        const val AIBUS_UPLOAD_FILE = "/humane.aibus.AIBusService/UploadFile"
        const val CAPTURE_UPLOAD_FILE = "/humane.capture.CaptureService/UploadFile"

        val ALL: Set<String> = setOf(
            AIBUS_ENCRYPTED_LOADING_MESSAGE,
            AIBUS_ENCRYPTED_UNDERSTAND,
            AIBUS_UNDERSTAND,
            AIBUS_UPLOAD_FILE,
            CAPTURE_UPLOAD_FILE,
        )
    }

    object ProtoKids {
        const val ACTION_BASED_INTERSTITIAL_REQUEST = "humane.aibus.ActionBasedInterstitialRequest"
        const val ACTION_BASED_INTERSTITIAL_RESPONSE = "humane.aibus.ActionBasedInterstitialResponse"
        const val AI_REQUEST = "humane.aibus.AIRequest"
        const val AI_RESPONSE = "humane.aibus.AIResponse"
        const val ANALYZE_FOOD_IMAGE_REQUEST = "humane.aibus.AnalyzeFoodImageRequest"
        const val ANALYZE_FOOD_IMAGE_RESPONSE = "humane.aibus.AnalyzeFoodImageResponse"
        const val ANALYZE_IMAGE_RESPONSE = "humane.aibus.AnalyzeImageResponse"
        const val CAN_TRANSLATE_REQUEST = "humane.aibus.CanTranslateRequest"
        const val CAN_TRANSLATE_RESPONSE = "humane.aibus.CanTranslateResponse"
        const val CHAT_COMPLETION_REQUEST = "humane.aibus.ChatCompletionRequest"
        const val CHAT_COMPLETION_RESPONSE = "humane.aibus.ChatCompletionResponse"
        const val COMPLETION_REQUEST = "humane.aibus.CompletionRequest"
        const val COMPLETION_RESPONSE = "humane.aibus.CompletionResponse"
        const val CONTACT = "humane.contacts.Contact"
        const val FOOD_LOG_SUMMARY = "humane.common.food.FoodLogSummary"
        const val FUNCTION_CALL = "humane.aibus.FunctionCall"
        const val FUNCTION_RESPONSE = "humane.aibus.FunctionResponse"
        const val GEO_LOCATE_REQUEST = "humane.aibus.GeoLocateRequest"
        const val GEO_LOCATE_RESPONSE = "humane.aibus.GeoLocateResponse"
        const val GET_FOOD_ITEM_REQUEST = "humane.aibus.GetFoodItemRequest"
        const val GET_FOOD_ITEM_RESPONSE = "humane.aibus.GetFoodItemResponse"
        const val LOADING_MESSAGE_REQUEST = "humane.aibus.LoadingMessageRequest"
        const val LOADING_MESSAGE_RESPONSE = "humane.aibus.LoadingMessageResponse"
        const val LOCATION_ENVELOPE = "humane.common.encryption.LocationEnvelope"
        const val MESSAGE_COMPOSITION_REQUEST = "humane.aibus.MessageCompositionRequest"
        const val MESSAGE_COMPOSITION_RESPONSE = "humane.aibus.MessageCompositionResponse"
        const val NAVIGATION_DIRECTIONS_REQUEST = "humane.aibus.NavigationDirectionsRequest"
        const val NAVIGATION_DIRECTIONS_RESPONSE = "humane.aibus.NavigationDirectionsResponse"
        const val NEARBY_SEARCH_REQUEST = "humane.aibus.NearbySearchRequest"
        const val NEARBY_SEARCH_RESPONSE = "humane.aibus.NearbySearchResponse"
        const val REVERSE_GEOCODE_RESPONSE = "humane.aibus.ReverseGeocodeResponse"
        const val SERVER_STATEFUL_UNDERSTAND_REQUEST = "humane.aibus.ServerStatefulUnderstandRequest"
        const val SERVER_STATEFUL_UNDERSTAND_RESPONSE = "humane.aibus.ServerStatefulUnderstandResponse"
        const val SMART_PLAYLIST_REQUEST = "humane.aibus.SmartPlaylistRequest"
        const val SMART_PLAYLIST_RESPONSE = "humane.aibus.SmartPlaylistResponse"
        const val STREAMING_UNDERSTAND_REQUEST = "humane.aibus.StreamingUnderstandRequest"
        const val STREAMING_UNDERSTAND_RESPONSE = "humane.aibus.StreamingUnderstandResponse"
        const val SUMMARIZATION_NETWORK_REQUEST = "humane.aibus.SummarizationNetworkRequest"
        const val SUMMARIZATION_NETWORK_RESPONSE = "humane.aibus.SummarizationNetworkResponse"
        const val SYNAPSE_UNDERSTANDING_REQUEST = "humane.aibus.SynapseUnderstandingRequest"
        const val SYNAPSE_UNDERSTANDING_RESPONSE = "humane.aibus.SynapseUnderstandingResponse"
        const val TEXT_TO_SPEECH_REQUEST = "humane.aibus.TextToSpeechRequest"
        const val TEXT_TO_SPEECH_RESPONSE = "humane.aibus.TextToSpeechResponse"
        const val TRANSLATE_CONVERSATION_REQUEST = "humane.aibus.TranslateConversationRequest"
        const val TRANSLATE_CONVERSATION_RESPONSE = "humane.aibus.TranslateConversationResponse"
        const val TRANSLATE_RESPONSE = "humane.aibus.TranslateResponse"
        const val TRANSLATE_TEXT_REQUEST = "humane.aibus.TranslateTextRequest"
        const val TRANSLATE_TEXT_RESPONSE = "humane.aibus.TranslateTextResponse"
        const val WEATHER_RESPONSE = "humane.aibus.WeatherResponse"

        val ALL: Set<String> = setOf(
            ACTION_BASED_INTERSTITIAL_REQUEST,
            ACTION_BASED_INTERSTITIAL_RESPONSE,
            AI_REQUEST,
            AI_RESPONSE,
            ANALYZE_FOOD_IMAGE_REQUEST,
            ANALYZE_FOOD_IMAGE_RESPONSE,
            ANALYZE_IMAGE_RESPONSE,
            CAN_TRANSLATE_REQUEST,
            CAN_TRANSLATE_RESPONSE,
            CHAT_COMPLETION_REQUEST,
            CHAT_COMPLETION_RESPONSE,
            COMPLETION_REQUEST,
            COMPLETION_RESPONSE,
            CONTACT,
            FOOD_LOG_SUMMARY,
            FUNCTION_CALL,
            FUNCTION_RESPONSE,
            GEO_LOCATE_REQUEST,
            GEO_LOCATE_RESPONSE,
            GET_FOOD_ITEM_REQUEST,
            GET_FOOD_ITEM_RESPONSE,
            LOADING_MESSAGE_REQUEST,
            LOADING_MESSAGE_RESPONSE,
            LOCATION_ENVELOPE,
            MESSAGE_COMPOSITION_REQUEST,
            MESSAGE_COMPOSITION_RESPONSE,
            NAVIGATION_DIRECTIONS_REQUEST,
            NAVIGATION_DIRECTIONS_RESPONSE,
            NEARBY_SEARCH_REQUEST,
            NEARBY_SEARCH_RESPONSE,
            REVERSE_GEOCODE_RESPONSE,
            SERVER_STATEFUL_UNDERSTAND_REQUEST,
            SERVER_STATEFUL_UNDERSTAND_RESPONSE,
            SMART_PLAYLIST_REQUEST,
            SMART_PLAYLIST_RESPONSE,
            STREAMING_UNDERSTAND_REQUEST,
            STREAMING_UNDERSTAND_RESPONSE,
            SUMMARIZATION_NETWORK_REQUEST,
            SUMMARIZATION_NETWORK_RESPONSE,
            SYNAPSE_UNDERSTANDING_REQUEST,
            SYNAPSE_UNDERSTANDING_RESPONSE,
            TEXT_TO_SPEECH_REQUEST,
            TEXT_TO_SPEECH_RESPONSE,
            TRANSLATE_CONVERSATION_REQUEST,
            TRANSLATE_CONVERSATION_RESPONSE,
            TRANSLATE_RESPONSE,
            TRANSLATE_TEXT_REQUEST,
            TRANSLATE_TEXT_RESPONSE,
            WEATHER_RESPONSE,
        )
    }

    object WireSentinels {
        const val PLAINTEXT_ENVELOPE = "plaintext"

        val ALL: Set<String> = setOf(
            PLAINTEXT_ENVELOPE,
        )
    }

    object Binder {
        object AiBusBridge {
            const val DESCRIPTOR = "humane.aibus.IAiBusBridge"
            const val TRANSACTION_ANALYZE_IMAGE = 1
            const val WIRE_NAME_ANALYZE_IMAGE = "analyzeImage"
            const val TRANSACTION_SYNAPSE_UNDERSTANDING = 2
            const val WIRE_NAME_SYNAPSE_UNDERSTANDING = "synapseUnderstanding"
            const val TRANSACTION_ENCRYPTED_SMART_PLAYLIST = 3
            const val WIRE_NAME_ENCRYPTED_SMART_PLAYLIST = "encryptedSmartPlaylist"
            const val TRANSACTION_CAN_TRANSLATE = 4
            const val WIRE_NAME_CAN_TRANSLATE = "canTranslate"
            const val TRANSACTION_TRANSLATE_TEXT = 5
            const val WIRE_NAME_TRANSLATE_TEXT = "translateText"
            const val TRANSACTION_TRANSLATE_CONVERSATION = 6
            const val WIRE_NAME_TRANSLATE_CONVERSATION = "translateConversation"
            const val TRANSACTION_STREAM_AI_BUS = 7
            const val WIRE_NAME_STREAM_AI_BUS = "streamAIBus"
            const val TRANSACTION_FETCH_HOME_SCREEN_WEATHER = 8
            const val WIRE_NAME_FETCH_HOME_SCREEN_WEATHER = "fetchHomeScreenWeather"
            const val TRANSACTION_ENCRYPTED_NEARBY_SEARCH = 9
            const val WIRE_NAME_ENCRYPTED_NEARBY_SEARCH = "encryptedNearbySearch"
            const val TRANSACTION_ENCRYPTED_GEO_LOCATE_REQUEST = 10
            const val WIRE_NAME_ENCRYPTED_GEO_LOCATE_REQUEST = "encryptedGeoLocateRequest"
            const val TRANSACTION_CHAT_COMPLETION = 11
            const val WIRE_NAME_CHAT_COMPLETION = "chatCompletion"
            const val TRANSACTION_GENERATE_INTERSTITIAL = 12
            const val WIRE_NAME_GENERATE_INTERSTITIAL = "generateInterstitial"
            const val TRANSACTION_NAVIGATION_DIRECTIONS = 13
            const val WIRE_NAME_NAVIGATION_DIRECTIONS = "navigationDirections"
            const val TRANSACTION_TEXT_TO_SPEECH = 14
            const val WIRE_NAME_TEXT_TO_SPEECH = "textToSpeech"
            const val TRANSACTION_STREAMING_TEXT_TO_SPEECH = 15
            const val WIRE_NAME_STREAMING_TEXT_TO_SPEECH = "streamingTextToSpeech"
            const val TRANSACTION_EXECUTE_FUNCTION_CALL = 16
            const val WIRE_NAME_EXECUTE_FUNCTION_CALL = "executeFunctionCall"
            const val TRANSACTION_SERVER_STATEFUL_UNDERSTAND = 17
            const val WIRE_NAME_SERVER_STATEFUL_UNDERSTAND = "serverStatefulUnderstand"
            const val TRANSACTION_BIDIRECTIONAL_STREAMING_UNDERSTAND = 18
            const val WIRE_NAME_BIDIRECTIONAL_STREAMING_UNDERSTAND = "bidirectionalStreamingUnderstand"
        }

        object PenumbraFeatureFlagApplyAck {
            const val DESCRIPTOR = "com.penumbraos.server.feature-flag-apply-ack.bridge.v1"
            const val TRANSACTION_RECORD_APPLIED = 1
            const val WIRE_NAME_RECORD_APPLIED = "recordApplied"
        }

        object PenumbraFitness {
            const val DESCRIPTOR = "com.penumbraos.server.fitness.bridge.v2"
            const val TRANSACTION_BEGIN_SESSION = 1
            const val WIRE_NAME_BEGIN_SESSION = "beginSession"
            const val TRANSACTION_FINISH_SESSION = 2
            const val WIRE_NAME_FINISH_SESSION = "finishSession"
            const val TRANSACTION_ABORT_SESSION = 3
            const val WIRE_NAME_ABORT_SESSION = "abortSession"
        }

        object PenumbraMessageStatus {
            const val DESCRIPTOR = "com.penumbraos.server.message-status.bridge.v1"
            const val TRANSACTION_RECORD_DELIVERED = 1
            const val WIRE_NAME_RECORD_DELIVERED = "recordDelivered"
        }

        object PenumbraSpotify {
            const val DESCRIPTOR = "com.penumbraos.server.spotify.bridge.v1"
            const val TRANSACTION_QUERY = 1
            const val WIRE_NAME_QUERY = "query"
            const val TRANSACTION_PLAYBACK = 2
            const val WIRE_NAME_PLAYBACK = "playback"
            const val TRANSACTION_SAVE = 3
            const val WIRE_NAME_SAVE = "save"
        }

        object StreamObserver {
            const val DESCRIPTOR = "humane.grpc.IStreamObserver"
            const val TRANSACTION_ON_NEXT = 1
            const val WIRE_NAME_ON_NEXT = "onNext"
            const val TRANSACTION_ON_ERROR = 2
            const val WIRE_NAME_ON_ERROR = "onError"
            const val TRANSACTION_ON_COMPLETED = 3
            const val WIRE_NAME_ON_COMPLETED = "onCompleted"
        }

    }

    object FeatureFlags {
        object Cloud {
            const val ACCESSORY_FEATURE_FLAGS = "accessory_feature_flags"
            const val CMU_ULTRA_CHIME_ENABLED = "cmu_ultra_chime_enabled"
            const val CMU_ULTRA_ENABLED = "cmu_ultra_enabled"
            const val ESIM_QR_SCANNER_ENABLED = "esim_qr_scanner_enabled"
            const val FEATURE_FLAG_SUPPRESS_SYNC_ON_STARTUP = "feature_flag_suppress_sync_on_startup"
            const val FITNESS_TRACKER_ENABLED = "fitness_tracker_enabled"
            const val FITNESS_TRACKER_EXTRA_DATA_ENABLED = "fitness_tracker_extra_data_enabled"
            const val LASER_FINDING_GUIDE = "laser_finding_guide"
            const val MUSIC_INTERSTITIALS_ENABLED = "music_interstitials_enabled"
            const val NETWORK_RESET_ENABLED = "network_reset_enabled"
            const val QUICK_ACTIONS_REMAPPING_ENABLED = "quick_actions_remapping_enabled"
            const val SERVER_SIDE_SPEECH_SYNTHESIS_STREAMING_ENABLED = "server_side_speech_synthesis_streaming_enabled"
            const val SERVER_SIDE_SPEECH_SYNTHESIS_TIMEOUT_MILLIS = "server_side_speech_synthesis_timeout_millis"
            const val SERVER_SIDE_SPEECH_SYNTHESIS_VOICE_NAME = "server_side_speech_synthesis_voice_name"
            const val SERVER_SIDE_TRANSCRIPTION_SAVE_ENABLED = "server_side_transcription_save_enabled"
            const val SYNAPSE_BIDIRECTIONAL_STREAMING = "synapse_bidirectional_streaming"
            const val TICKLE = "tickle"
            const val TOUCHCODE_TIMEOUT_MILLIS = "touchcode_timeout_millis"
            const val VISION_ACTIONS_ENABLED = "vision_actions_enabled"
            const val VISION_CUSTOM_GESTURE_ENABLED = "vision_custom_gesture_enabled"

            val ALL: Set<String> = setOf(
                ACCESSORY_FEATURE_FLAGS,
                CMU_ULTRA_CHIME_ENABLED,
                CMU_ULTRA_ENABLED,
                ESIM_QR_SCANNER_ENABLED,
                FEATURE_FLAG_SUPPRESS_SYNC_ON_STARTUP,
                FITNESS_TRACKER_ENABLED,
                FITNESS_TRACKER_EXTRA_DATA_ENABLED,
                LASER_FINDING_GUIDE,
                MUSIC_INTERSTITIALS_ENABLED,
                NETWORK_RESET_ENABLED,
                QUICK_ACTIONS_REMAPPING_ENABLED,
                SERVER_SIDE_SPEECH_SYNTHESIS_STREAMING_ENABLED,
                SERVER_SIDE_SPEECH_SYNTHESIS_TIMEOUT_MILLIS,
                SERVER_SIDE_SPEECH_SYNTHESIS_VOICE_NAME,
                SERVER_SIDE_TRANSCRIPTION_SAVE_ENABLED,
                SYNAPSE_BIDIRECTIONAL_STREAMING,
                TICKLE,
                TOUCHCODE_TIMEOUT_MILLIS,
                VISION_ACTIONS_ENABLED,
                VISION_CUSTOM_GESTURE_ENABLED,
            )
        }

        object SettingsGlobal {
            const val CLOCK_ENABLED = "humane_clock_enabled"
            const val CMU_ULTRA_ENABLED = "humane_cmu_ultra_enabled"
            const val FOOD_ENABLED = "humane_food_enabled"
            const val HEALTH_TRACKER_ENABLED = "humane_health_tracker_enabled"
            const val PHOTO_SHARING_ENABLED = "humane_photo_sharing_enabled"
            const val PHOTOGRAPHY_JPG_ENABLED = "humane_photography_jpg_enabled"

            val ALL: Set<String> = setOf(
                CLOCK_ENABLED,
                CMU_ULTRA_ENABLED,
                FOOD_ENABLED,
                HEALTH_TRACKER_ENABLED,
                PHOTO_SHARING_ENABLED,
                PHOTOGRAPHY_JPG_ENABLED,
            )
        }

        object PenumbraSettingsGlobal {
            const val WEATHER_CELSIUS = "penumbra_weather_celsius"

            val ALL: Set<String> = setOf(
                WEATHER_CELSIUS,
            )
        }
    }

    object OperationalMarkers {
        const val AGENTIC_PHYSICAL_TRACE = "<<< Agentic physical proof trace"
        const val ARTIST_SCOPED_COMPLETION = "<<< hermes completing on the artist-scoped observation"
        const val BACKEND_UNAVAILABLE = "backend_unavailable"
        const val BOUNDED_LOADING_MESSAGE = "<<< Returning bounded stock loading message"
        const val CATEGORIZE_NOTIFICATIONS = ">>> CategorizeNotifications"
        const val DECLINE = "<<< hermes decline"
        const val DETERMINISTIC_COMPLETION = "<<< completing device control deterministically"
        const val ENCRYPTED_SUMMARIZE_MESSAGES = ">>> EncryptedSummarizeMessages"
        const val EXACT_CONTEXT_RESET_AUTHORIZED = "Authorized exact context-reset action"
        const val FINAL_ANSWER = "<<< hermes final answer"
        const val FIRST_STEP_RETRY = "<<< hermes retrying the first model step"
        const val FORCING_DETERMINISTIC_TERMINAL_ACTION = "<<< hermes forcing deterministic terminal action"
        const val HAND_TRACKING_HELD_FOR_NARRATION = "Hand tracking timeout held for narration"
        const val LOCAL_WEATHER_PHYSICAL_TRACE = "<<< Deterministic local weather physical proof trace"
        const val MUSIC_INTENT_COMPATIBILITY_EMITTED = "Music intent compatibility emitted"
        const val MUSIC_RANKING_DEGRADED = "<<< spotify artist ranking degraded to relevance search"
        const val MUTATION = "<<< hermes mutation"
        const val MUTATION_REJECTED = "<<< hermes mutation rejected: not grounded in this turn"
        const val NARRATION_END_RELEASED_HOLD = "NARRATION_END released narration hold"
        const val NARRATION_END_WITHOUT_HAND_TRACKING = "NARRATION_END ignored because no active hand tracking session"
        const val NARRATION_START_WITHOUT_HAND_TRACKING = "NARRATION_START ignored because no active hand tracking session"
        const val NATIVE_ACTION_FOR_PHYSICAL_VERIFICATION = "Observed native action for physical verification"
        const val NLU_ENTRY_INTENT = "<<< nlu entry intent"
        const val NLU_MUSIC_SLOTS = "<<< nlu music slots"
        const val NLU_SEMANTIC_HIT = "<<< nlu semantic hit"
        const val OBSERVATION_REPLAYED = "<<< hermes replaying identical observation from this turn"
        const val SLOW_MODEL_STEP = "<<< hermes slow model step threshold reached"
        const val STEP_BACKEND_ERROR = "<<< hermes step backend error"
        const val STEP_COMPLETED = "<<< hermes step completed"
        const val STOCK_RUN_FINAL_MESSAGE = "New turn is a message, so final, allowing dispatch but ending current Run."
        const val STOCK_RUN_FINAL_OBSERVATION = "New turn is final, allowing dispatch but ending current Run."
        const val STREAMING_SPEECH_FAILURE_RELEASED = "Streaming speech playback failure released"
        const val STREAMING_UNDERSTAND_COMPLETED = "<<< BidirectionalStreamingUnderstand completed after final observation"
        const val STREAMING_UNDERSTAND_REQUEST = ">>> BidirectionalStreamingUnderstand (content redacted)"
        const val TERMINAL_NATIVE_ACTION = "<<< hermes terminal native action"
        const val TIME_BUDGET_GRACE = "<<< hermes time budget nearly spent; forcing the grace answer"
        const val TOOL_EXECUTED = "<<< hermes tool executed"
        const val VERIFICATION_GATE_REJECTED = "<<< hermes final answer rejected by verification gate"

        val LIVE: Set<String> = setOf(
            AGENTIC_PHYSICAL_TRACE,
            ARTIST_SCOPED_COMPLETION,
            BACKEND_UNAVAILABLE,
            BOUNDED_LOADING_MESSAGE,
            CATEGORIZE_NOTIFICATIONS,
            DECLINE,
            DETERMINISTIC_COMPLETION,
            ENCRYPTED_SUMMARIZE_MESSAGES,
            EXACT_CONTEXT_RESET_AUTHORIZED,
            FINAL_ANSWER,
            FIRST_STEP_RETRY,
            FORCING_DETERMINISTIC_TERMINAL_ACTION,
            HAND_TRACKING_HELD_FOR_NARRATION,
            LOCAL_WEATHER_PHYSICAL_TRACE,
            MUSIC_INTENT_COMPATIBILITY_EMITTED,
            MUSIC_RANKING_DEGRADED,
            MUTATION,
            MUTATION_REJECTED,
            NARRATION_END_RELEASED_HOLD,
            NATIVE_ACTION_FOR_PHYSICAL_VERIFICATION,
            NLU_ENTRY_INTENT,
            NLU_MUSIC_SLOTS,
            NLU_SEMANTIC_HIT,
            OBSERVATION_REPLAYED,
            SLOW_MODEL_STEP,
            STEP_BACKEND_ERROR,
            STEP_COMPLETED,
            STREAMING_SPEECH_FAILURE_RELEASED,
            STREAMING_UNDERSTAND_COMPLETED,
            STREAMING_UNDERSTAND_REQUEST,
            TERMINAL_NATIVE_ACTION,
            TIME_BUDGET_GRACE,
            TOOL_EXECUTED,
            VERIFICATION_GATE_REJECTED,
        )

        val EXTERNAL: Set<String> = setOf(
            STOCK_RUN_FINAL_MESSAGE,
            STOCK_RUN_FINAL_OBSERVATION,
        )

        val UNVERIFIED: Set<String> = setOf(
            NARRATION_END_WITHOUT_HAND_TRACKING,
            NARRATION_START_WITHOUT_HAND_TRACKING,
        )
    }

    object NativeActions {
        const val ACCEPT_CALL = "AcceptCall"
        const val ADD_IF_THEN_ENTRY = "AddIfThenEntry"
        const val ALARM = "Alarm"
        const val AM_I_ONLINE = "AmIOnline"
        const val ASK_CONFIRMATION_FOR_EMERGENCY_CALL = "AskConfirmationForEmergencyCall"
        const val ASK_CONFIRMATION_FOR_FACTORY_RESET = "AskConfirmationForFactoryReset"
        const val CALL_PERSON = "CallPerson"
        const val CANCEL_ALARM = "CancelAlarm"
        const val CANCEL_SEND_MESSAGE = "CancelSendMessage"
        const val CAPTURE_PHOTOGRAPH = "CapturePhotograph"
        const val CAPTURE_VIDEO = "CaptureVideo"
        const val CATCH_ME_UP = "CatchMeUp"
        const val CHANGE_QUICK_ACTION = "ChangeQuickAction"
        const val CLEAR_IF_THEN_MAP = "ClearIfThenMap"
        const val CLEAR_UNDERSTANDING_CONTEXT = "ClearUnderstandingContext"
        const val COMPOSE_MESSAGE = "ComposeMessage"
        const val CONFIRM_SEND_MESSAGE = "ConfirmSendMessage"
        const val CONNECT_TO_BLUETOOTH = "ConnectToBluetooth"
        const val CONNECT_TO_WIFI = "ConnectToWifi"
        const val CONTACTS = "Contacts"
        const val CREATE_CONTACT = "CreateContact"
        const val CREATE_MEMORY = "CreateMemory"
        const val DECREMENT_VOLUME = "DecrementVolume"
        const val DELETE_TIMER = "DeleteTimer"
        const val DEVICE_STATUS = "DeviceStatus"
        const val DEVICE_UNLOCKED = "DeviceUnlocked"
        const val DISCONNECT_BLUETOOTH = "DisconnectBluetooth"
        const val DISCONNECT_WIFI = "DisconnectWifi"
        const val DISPLAY_ALARM = "DisplayAlarm"
        const val DISPLAY_CONTACT = "DisplayContact"
        const val DISPLAY_MESSAGES = "DisplayMessages"
        const val DISPLAY_TIMER = "DisplayTimer"
        const val EDIT_TIMER = "EditTimer"
        const val END_CALL = "EndCall"
        const val ENTER_PRIVACY_MODE = "EnterPrivacyMode"
        const val EXPERIMENTAL_INTERFACE = "ExperimentalInterface"
        const val EXPLAIN_FAILURE = "ExplainFailure"
        const val FACTORY_RESET = "FactoryReset"
        const val GENERATE_MUSIC_PLAYLIST = "GenerateMusicPlaylist"
        const val GET_AIRPLANE_MODE_STATUS = "GetAirplaneModeStatus"
        const val GET_BATTERY_LEVEL = "GetBatteryLevel"
        const val GET_BLUETOOTH_STATUS = "GetBluetoothStatus"
        const val GET_CURRENT_LOCATION = "GetCurrentLocation"
        const val GET_CURRENT_TIME = "GetCurrentTime"
        const val GET_CURRENT_VOLUME = "GetCurrentVolume"
        const val GET_IF_THEN_MAP_SIZE = "GetIfThenMapSize"
        const val GET_MUSIC_QUEUE = "GetMusicQueue"
        const val GET_NEW_BLUETOOTH_ADDRESS = "GetNewBluetoothAddress"
        const val GET_PAIRED_BLUETOOTH_ADDRESS = "GetPairedBluetoothAddress"
        const val GET_PHONE_NUMBER = "GetPhoneNumber"
        const val GET_QUICK_MESSAGING_PARTICIPANTS = "GetQuickMessagingParticipants"
        const val GET_SERIAL_NUMBER = "GetSerialNumber"
        const val HARD_MODERATE = "HardModerate"
        const val INCREMENT_VOLUME = "IncrementVolume"
        const val INSTRUCT_UNLOCK = "InstructUnlock"
        const val INVALID_SUBSCRIPTION = "InvalidSubscription"
        const val LOCK_DEVICE = "LockDevice"
        const val MANAGE_MEMORY = "ManageMemory"
        const val MANAGE_NUTRITION = "ManageNutrition"
        const val MESSAGE_SEARCH = "MessageSearch"
        const val MODERATE = "Moderate"
        const val NARRATE = "Narrate"
        const val NEXT_TRACK = "NextTrack"
        const val OPEN_CONTACTS = "OpenContacts"
        const val OPEN_DIALER_HOME = "OpenDialerHome"
        const val OPEN_DIALPAD = "OpenDialpad"
        const val OPEN_MESSAGES_MAIN_MENU = "OpenMessagesMainMenu"
        const val OPEN_RECENT_CALLS = "OpenRecentCalls"
        const val OPEN_RECENT_PHOTOS = "OpenRecentPhotos"
        const val OPEN_TUTORIAL = "OpenTutorial"
        const val PAUSE_MUSIC = "PauseMusic"
        const val PAUSE_TIMER = "PauseTimer"
        const val PLAY_CURRENT_TRACK_RADIO = "PlayCurrentTrackRadio"
        const val PLAY_FAVORITE_TRACKS = "PlayFavoriteTracks"
        const val PLAY_FEATURED_MUSIC = "PlayFeaturedMusic"
        const val PLAY_MUSIC = "PlayMusic"
        const val PLAY_RECOMMENDATIONS_WITH_TRACK_ID = "PlayRecommendationsWithTrackId"
        const val PLAY_SOUND = "PlaySound"
        const val PRESENT_INCOMING_MESSAGE_ACTION = "PresentIncomingMessageAction"
        const val PREVIOUS_BUTTON = "PreviousButton"
        const val PREVIOUS_TRACK = "PreviousTrack"
        const val READ_ALL_MESSAGES = "ReadAllMessages"
        const val REBOOT = "Reboot"
        const val RESPOND = "Respond"
        const val RESTART_TRACK = "RestartTrack"
        const val RESUME_CALL = "ResumeCall"
        const val RESUME_MUSIC = "ResumeMusic"
        const val RESUME_TIMER = "ResumeTimer"
        const val SAVE_CURRENT_TRACK_TO_FAVORITES = "SaveCurrentTrackToFavorites"
        const val SEARCH_CONTACT = "SearchContact"
        const val SET_ALARM = "SetAlarm"
        const val SET_DEFAULT_TRANSLATE_LANGUAGE = "SetDefaultTranslateLanguage"
        const val SET_QUICK_MESSAGING_CONTACT = "SetQuickMessagingContact"
        const val SET_TIMER = "SetTimer"
        const val SET_UP_TOUCHCODE = "SetUpTouchcode"
        const val SET_VOLUME = "SetVolume"
        const val SETTINGS = "Settings"
        const val SHOW_ERROR = "ShowError"
        const val START_ACTIVITY_TRACKER = "StartActivityTracker"
        const val START_TRANSLATION = "StartTranslation"
        const val STOP_ACTIVITY_TRACKER = "StopActivityTracker"
        const val STOP_TRANSLATION = "StopTranslation"
        const val STOP_VIDEO = "StopVideo"
        const val SYSTEM_TRACE_START = "SystemTraceStart"
        const val SYSTEM_TRACE_STOP = "SystemTraceStop"
        const val THERMAL_WARNING = "ThermalWarning"
        const val TICKLE = "Tickle"
        const val TIMER = "Timer"
        const val TRANSLATE = "Translate"
        const val TRIGGER_BUG_REPORT = "TriggerBugReport"
        const val TRUST_LOCK = "TrustLock"
        const val TURN_OFF_AIRPLANE_MODE = "TurnOffAirplaneMode"
        const val TURN_OFF_AMBER_ALERT = "TurnOffAmberAlert"
        const val TURN_OFF_BLUETOOTH = "TurnOffBluetooth"
        const val TURN_OFF_CELLULAR_DATA = "TurnOffCellularData"
        const val TURN_OFF_CELLULAR_ROAMING = "TurnOffCellularRoaming"
        const val TURN_OFF_DEVICE = "TurnOffDevice"
        const val TURN_OFF_EMERGENCY_ALERT = "TurnOffEmergencyAlert"
        const val TURN_OFF_PUBLIC_SAFETY_ALERT = "TurnOffPublicSafetyAlert"
        const val TURN_OFF_WIFI = "TurnOffWifi"
        const val TURN_ON_AIRPLANE_MODE = "TurnOnAirplaneMode"
        const val TURN_ON_AMBER_ALERT = "TurnOnAmberAlert"
        const val TURN_ON_BLUETOOTH = "TurnOnBluetooth"
        const val TURN_ON_CELLULAR_DATA = "TurnOnCellularData"
        const val TURN_ON_CELLULAR_ROAMING = "TurnOnCellularRoaming"
        const val TURN_ON_EMERGENCY_ALERT = "TurnOnEmergencyAlert"
        const val TURN_ON_PUBLIC_SAFETY_ALERT = "TurnOnPublicSafetyAlert"
        const val TURN_ON_WIFI = "TurnOnWifi"
        const val UNAUTHORIZED_DEVICE = "UnauthorizedDevice"
        const val UNDERSTAND_SCENE = "UnderstandScene"
        const val UPDATE_CONTACT_TRUSTED = "UpdateContactTrusted"
        const val USER_CONFIRMED_EMERGENCY_CALL = "UserConfirmedEmergencyCall"
        const val USER_CONFIRMED_FACTORY_RESET = "UserConfirmedFactoryReset"
        const val USER_DENIED_EMERGENCY_CALL = "UserDeniedEmergencyCall"
        const val USER_DENIED_FACTORY_RESET = "UserDeniedFactoryReset"
        const val VIEW_CALL_LOG = "ViewCallLog"
        const val WIFI_QR_SCAN = "WifiQrScan"
        const val WORLD_CLOCK = "WorldClock"

        val ALL: Set<String> = setOf(
            ACCEPT_CALL,
            ADD_IF_THEN_ENTRY,
            ALARM,
            AM_I_ONLINE,
            ASK_CONFIRMATION_FOR_EMERGENCY_CALL,
            ASK_CONFIRMATION_FOR_FACTORY_RESET,
            CALL_PERSON,
            CANCEL_ALARM,
            CANCEL_SEND_MESSAGE,
            CAPTURE_PHOTOGRAPH,
            CAPTURE_VIDEO,
            CATCH_ME_UP,
            CHANGE_QUICK_ACTION,
            CLEAR_IF_THEN_MAP,
            CLEAR_UNDERSTANDING_CONTEXT,
            COMPOSE_MESSAGE,
            CONFIRM_SEND_MESSAGE,
            CONNECT_TO_BLUETOOTH,
            CONNECT_TO_WIFI,
            CONTACTS,
            CREATE_CONTACT,
            CREATE_MEMORY,
            DECREMENT_VOLUME,
            DELETE_TIMER,
            DEVICE_STATUS,
            DEVICE_UNLOCKED,
            DISCONNECT_BLUETOOTH,
            DISCONNECT_WIFI,
            DISPLAY_ALARM,
            DISPLAY_CONTACT,
            DISPLAY_MESSAGES,
            DISPLAY_TIMER,
            EDIT_TIMER,
            END_CALL,
            ENTER_PRIVACY_MODE,
            EXPERIMENTAL_INTERFACE,
            EXPLAIN_FAILURE,
            FACTORY_RESET,
            GENERATE_MUSIC_PLAYLIST,
            GET_AIRPLANE_MODE_STATUS,
            GET_BATTERY_LEVEL,
            GET_BLUETOOTH_STATUS,
            GET_CURRENT_LOCATION,
            GET_CURRENT_TIME,
            GET_CURRENT_VOLUME,
            GET_IF_THEN_MAP_SIZE,
            GET_MUSIC_QUEUE,
            GET_NEW_BLUETOOTH_ADDRESS,
            GET_PAIRED_BLUETOOTH_ADDRESS,
            GET_PHONE_NUMBER,
            GET_QUICK_MESSAGING_PARTICIPANTS,
            GET_SERIAL_NUMBER,
            HARD_MODERATE,
            INCREMENT_VOLUME,
            INSTRUCT_UNLOCK,
            INVALID_SUBSCRIPTION,
            LOCK_DEVICE,
            MANAGE_MEMORY,
            MANAGE_NUTRITION,
            MESSAGE_SEARCH,
            MODERATE,
            NARRATE,
            NEXT_TRACK,
            OPEN_CONTACTS,
            OPEN_DIALER_HOME,
            OPEN_DIALPAD,
            OPEN_MESSAGES_MAIN_MENU,
            OPEN_RECENT_CALLS,
            OPEN_RECENT_PHOTOS,
            OPEN_TUTORIAL,
            PAUSE_MUSIC,
            PAUSE_TIMER,
            PLAY_CURRENT_TRACK_RADIO,
            PLAY_FAVORITE_TRACKS,
            PLAY_FEATURED_MUSIC,
            PLAY_MUSIC,
            PLAY_RECOMMENDATIONS_WITH_TRACK_ID,
            PLAY_SOUND,
            PRESENT_INCOMING_MESSAGE_ACTION,
            PREVIOUS_BUTTON,
            PREVIOUS_TRACK,
            READ_ALL_MESSAGES,
            REBOOT,
            RESPOND,
            RESTART_TRACK,
            RESUME_CALL,
            RESUME_MUSIC,
            RESUME_TIMER,
            SAVE_CURRENT_TRACK_TO_FAVORITES,
            SEARCH_CONTACT,
            SET_ALARM,
            SET_DEFAULT_TRANSLATE_LANGUAGE,
            SET_QUICK_MESSAGING_CONTACT,
            SET_TIMER,
            SET_UP_TOUCHCODE,
            SET_VOLUME,
            SETTINGS,
            SHOW_ERROR,
            START_ACTIVITY_TRACKER,
            START_TRANSLATION,
            STOP_ACTIVITY_TRACKER,
            STOP_TRANSLATION,
            STOP_VIDEO,
            SYSTEM_TRACE_START,
            SYSTEM_TRACE_STOP,
            THERMAL_WARNING,
            TICKLE,
            TIMER,
            TRANSLATE,
            TRIGGER_BUG_REPORT,
            TRUST_LOCK,
            TURN_OFF_AIRPLANE_MODE,
            TURN_OFF_AMBER_ALERT,
            TURN_OFF_BLUETOOTH,
            TURN_OFF_CELLULAR_DATA,
            TURN_OFF_CELLULAR_ROAMING,
            TURN_OFF_DEVICE,
            TURN_OFF_EMERGENCY_ALERT,
            TURN_OFF_PUBLIC_SAFETY_ALERT,
            TURN_OFF_WIFI,
            TURN_ON_AIRPLANE_MODE,
            TURN_ON_AMBER_ALERT,
            TURN_ON_BLUETOOTH,
            TURN_ON_CELLULAR_DATA,
            TURN_ON_CELLULAR_ROAMING,
            TURN_ON_EMERGENCY_ALERT,
            TURN_ON_PUBLIC_SAFETY_ALERT,
            TURN_ON_WIFI,
            UNAUTHORIZED_DEVICE,
            UNDERSTAND_SCENE,
            UPDATE_CONTACT_TRUSTED,
            USER_CONFIRMED_EMERGENCY_CALL,
            USER_CONFIRMED_FACTORY_RESET,
            USER_DENIED_EMERGENCY_CALL,
            USER_DENIED_FACTORY_RESET,
            VIEW_CALL_LOG,
            WIFI_QR_SCAN,
            WORLD_CLOCK,
        )
    }
}
