//! Clean-room contract tests for the optional quantized intent head.
//!
//! - `implemented`: every class, weight, and embedding below is generated by
//!   this test module and exists only to exercise parsing and decision logic.
//! - `unknown`: no trained head has sufficient provenance and licensing to be
//!   stored in canonical source.

use super::classifier::IntentHead;
use serde_json::{json, Value};
use sha2::{Digest, Sha256};
use std::io::Write as _;

const SYNTHETIC_DIM: usize = 512;

fn synthetic_artifact() -> Value {
    let mut selected = vec![0_i8; SYNTHETIC_DIM];
    let mut rejected = vec![0_i8; SYNTHETIC_DIM];
    selected[0] = 8;
    rejected[0] = -8;
    json!({
        "classes": ["SYNTHETIC_ACTION", "OTHER"],
        "scale": [1.0, 1.0],
        "bias": [0.0, 0.0],
        "weight_i8": [selected, rejected],
        "dim": SYNTHETIC_DIM,
        "reject_threshold": 0.75
    })
}

fn artifact_bytes() -> Vec<u8> {
    serde_json::to_vec(&synthetic_artifact()).expect("synthetic artifact serializes")
}

fn sha256_hex(bytes: &[u8]) -> String {
    Sha256::digest(bytes)
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect()
}

#[test]
fn programmatic_head_exercises_selection_rejection_and_dimension_checks() {
    let bytes = artifact_bytes();
    let head = IntentHead::from_json(std::str::from_utf8(&bytes).unwrap())
        .expect("independently authored artifact parses");

    let mut selected = vec![0.0_f32; SYNTHETIC_DIM];
    selected[0] = 1.0;
    let prediction = head
        .classify(&selected)
        .expect("synthetic selected class clears the threshold");
    assert_eq!(prediction.intent, "SYNTHETIC_ACTION");
    assert!(prediction.confidence > 0.99);

    selected[0] = -1.0;
    assert!(head.classify(&selected).is_none(), "OTHER is fail-open");
    assert!(head.classify(&selected[..SYNTHETIC_DIM - 1]).is_none());
}

#[test]
fn malformed_programmatic_shapes_are_rejected() {
    let mut artifact = synthetic_artifact();
    artifact["weight_i8"][0] = json!(vec![0_i8; SYNTHETIC_DIM - 1]);
    let json = serde_json::to_string(&artifact).unwrap();
    let error = IntentHead::from_json(&json)
        .err()
        .expect("a short weight row must fail");
    assert_eq!(error, "intent head weight row dimension mismatch");

    let mut artifact = synthetic_artifact();
    artifact["classes"] = json!(["SYNTHETIC_ACTION", "SYNTHETIC_ACTION"]);
    let json = serde_json::to_string(&artifact).unwrap();
    assert!(IntentHead::from_json(&json).is_err());
}

#[test]
fn external_head_requires_an_absolute_path_and_matching_digest() {
    let bytes = artifact_bytes();
    let digest = sha256_hex(&bytes);
    let mut file = tempfile::NamedTempFile::new().expect("create external test asset");
    file.write_all(&bytes).expect("write external test asset");

    let head = IntentHead::from_external_file(file.path(), &digest)
        .expect("digest-bound external artifact loads");
    let mut embedding = vec![0.0_f32; SYNTHETIC_DIM];
    embedding[0] = 1.0;
    assert_eq!(
        head.classify(&embedding).unwrap().intent,
        "SYNTHETIC_ACTION"
    );

    let mismatch = "0".repeat(64);
    assert!(IntentHead::from_external_file(file.path(), &mismatch).is_err());
    assert!(IntentHead::from_external_file(std::path::Path::new("head.json"), &digest).is_err());
    assert!(IntentHead::from_external_file(file.path(), &digest.to_uppercase()).is_err());
}

#[test]
fn external_head_bytes_are_bounded_before_hashing_or_parsing() {
    let oversized = vec![b' '; 256 * 1024 + 1];
    let error = IntentHead::from_verified_json(&oversized, &"0".repeat(64))
        .err()
        .expect("oversized external asset must fail");
    assert_eq!(error, "intent head external asset exceeds size limit");
}
