#!/usr/bin/env python3
"""Generate the C compatibility gate from a validated target profile."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from ghostlock_profile import ProfileError, TargetProfile, load_profile  # noqa: E402


TARGET_LAYOUT_RE = re.compile(
    r'^#define TARGET_LAYOUT_IMAGE_SHA256 "([0-9a-f]{64})"$', re.MULTILINE
)


def validate_target_layout(profile: TargetProfile, target_header: Path) -> None:
    try:
        source = target_header.read_text(encoding="utf-8")
    except OSError as exc:
        raise ProfileError(f"cannot read target header {target_header}: {exc}") from exc
    matches = TARGET_LAYOUT_RE.findall(source)
    if len(matches) != 1:
        raise ProfileError(
            f"{target_header} must define exactly one TARGET_LAYOUT_IMAGE_SHA256"
        )
    if matches[0] != profile.kernel_image_sha256:
        raise ProfileError(
            "target layout Image hash mismatch: "
            f"profile declares {profile.kernel_image_sha256}, "
            f"target layout declares {matches[0]}"
        )


def c_string(value: str) -> str:
    escaped: list[str] = ['"']
    for byte in value.encode("utf-8"):
        if byte == 0x22:
            escaped.append(r"\"")
        elif byte == 0x5C:
            escaped.append(r"\\")
        elif 0x20 <= byte <= 0x7E:
            escaped.append(chr(byte))
        else:
            escaped.append(f"\\{byte:03o}")
    escaped.append('"')
    return "".join(escaped)


def c_array(values: tuple[str, ...]) -> str:
    return "{ " + ", ".join(c_string(value) for value in values) + " }"


def render_header(profile: TargetProfile) -> str:
    geometry = profile.allocator_geometry
    return f"""/* Generated by scripts/generate_profile_header.py. Do not edit. */
#ifndef GHOSTLOCK_PROFILE_GENERATED_H
#define GHOSTLOCK_PROFILE_GENERATED_H

#define BUILD_VARIANT_LABEL {c_string(profile.profile_id)}
#define BUILD_FINGERPRINT {c_string(profile.fingerprint)}
#define BUILD_SLOTS {c_array(profile.accepted_slots)}
#define BUILD_SLOT_COUNT {len(profile.accepted_slots)}
#define BUILD_ABIS {c_array(profile.accepted_abis)}
#define BUILD_ABI_COUNT {len(profile.accepted_abis)}
#define PROFILE_KERNEL_RELEASE {c_string(profile.kernel_release)}
#define PROFILE_KERNEL_BUILD_MARKER {c_string(profile.kernel_build_marker)}
#define PROFILE_KERNEL_MACHINE {c_string(profile.kernel_machine)}
#define TARGET_KERNEL_IMAGE_SHA256 {c_string(profile.kernel_image_sha256)}
#define PROFILE_MANIFEST_SHA256 {c_string(profile.manifest_sha256)}
#define PROFILE_SYMBOLS_SHA256 {c_string(profile.symbols_sha256)}
#define PROFILE_MM_OBJECT_SIZE {geometry.object_size}
#define PROFILE_MM_SLAB_SIZE {geometry.slab_size}
#define PROFILE_MM_ORDER {geometry.order}
#define PROFILE_MM_OBJECTS_PER_SLAB {geometry.objects_per_slab}
#define PROFILE_MM_CPU_PARTIAL {geometry.cpu_partial}

#endif
"""


def write_if_changed(path: Path, content: str) -> None:
    try:
        if path.read_text(encoding="utf-8") == content:
            return
    except FileNotFoundError:
        pass
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(path)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--profile", type=Path, required=True)
    parser.add_argument("--project", required=True)
    parser.add_argument("--target-header", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args(argv)
    try:
        profile = load_profile(args.profile)
        if profile.project != args.project:
            raise ProfileError(
                f"profile {profile.profile_id!r} targets project "
                f"{profile.project!r}, not {args.project!r}"
            )
        validate_target_layout(profile, args.target_header)
        write_if_changed(args.output, render_header(profile))
    except (OSError, ProfileError) as exc:
        parser.error(str(exc))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
