import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";

import {
  GENERATED_OUTPUT_PATHS,
  REPOSITORY_ROOT,
  loadAndResolveTierARegistry,
  scanTierAProductionFiles,
} from "./tier-a-registry.mjs";

const PRODUCTION_SOURCE_EXTENSIONS = new Set([
  ".cjs",
  ".cts",
  ".gradle",
  ".js",
  ".jsx",
  ".kt",
  ".kts",
  ".mjs",
  ".mts",
  ".rs",
  ".sh",
  ".toml",
  ".ts",
  ".tsx",
  ".xml",
]);

const GENERATED_PATHS = new Set(Object.values(GENERATED_OUTPUT_PATHS));
const REGISTRY_IMPLEMENTATION_PATH = "platform/containers/pin-builder/tier-a-registry.mjs";
const GENERATED_BANNER =
  /(?:@generated\b|\bgenerated by\b[\s\S]{0,160}\bdo not edit\b)/i;
const EXCLUDED_DIRECTORY_NAMES = new Set([
  ".cache",
  ".cxx",
  ".externalNativeBuild",
  ".git",
  ".gradle",
  ".idea",
  ".kotlin",
  "__pycache__",
  "dist",
  "node_modules",
  "out",
  "target",
]);
const EXCLUDED_DIRECTORY_PATHS = new Set([
  ".claude",
  ".codex",
  ".secrets",
  "captures",
  "data",
  "decompile-workspace",
  "device-dumps",
  "logs",
  "private",
  "release-assets",
  "releases",
  "rollback",
  "runtime-state",
  "runtime/core/data",
  "runtime/core/media",
  "secrets",
  "test-runs",
]);

function isTestSource(relativePath) {
  const segments = relativePath.split("/");
  if (
    segments.some((segment) =>
      ["test", "tests", "__tests__"].includes(segment.toLowerCase()),
    )
  ) {
    return true;
  }

  const basename = path.basename(relativePath);
  return (
    /(?:^|[._-])tests?(?:[._-]|$)/i.test(basename) ||
    /(?:^|[._-])spec(?:[._-]|$)/i.test(basename) ||
    /(?:Test|Tests)\.kt$/.test(basename)
  );
}

function hasGeneratedBanner(absolutePath) {
  return GENERATED_BANNER.test(
    fs.readFileSync(absolutePath, "utf8").slice(0, 2_048),
  );
}

function sourceFilesFromFilesystem(root) {
  const files = [];

  function visit(absoluteDirectory, relativeDirectory = "") {
    const entries = fs
      .readdirSync(absoluteDirectory, { withFileTypes: true })
      .sort((left, right) => left.name.localeCompare(right.name));

    for (const entry of entries) {
      const relativePath = relativeDirectory
        ? `${relativeDirectory}/${entry.name}`
        : entry.name;

      if (entry.isDirectory()) {
        // The repository-level build/ directory is authored tooling. Nested
        // build/ directories are generated by Gradle and other toolchains.
        if (
          EXCLUDED_DIRECTORY_NAMES.has(entry.name) ||
          EXCLUDED_DIRECTORY_PATHS.has(relativePath) ||
          (entry.name === "build" && relativeDirectory !== "")
        ) {
          continue;
        }
        visit(path.join(absoluteDirectory, entry.name), relativePath);
      } else if (entry.isFile()) {
        files.push(relativePath);
      }
      // Do not follow symlinks: an inventory must stay inside its root.
    }
  }

  visit(root);
  return files;
}

function productionSourceFiles(root = REPOSITORY_ROOT) {
  return sourceFilesFromFilesystem(root)
    .filter((relativePath) =>
      PRODUCTION_SOURCE_EXTENSIONS.has(path.extname(relativePath)),
    )
    .filter((relativePath) => !/(^|\/)\.env(?:\.|$)/.test(relativePath))
    .filter((relativePath) => !/(^|\/)config\.local\.toml$/.test(relativePath))
    .filter((relativePath) => relativePath !== REGISTRY_IMPLEMENTATION_PATH)
    .filter((relativePath) => !GENERATED_PATHS.has(relativePath))
    .filter((relativePath) => !/(^|\/)generated\//i.test(relativePath))
    .filter((relativePath) => !isTestSource(relativePath))
    .filter(
      (relativePath) =>
        !hasGeneratedBanner(path.join(root, relativePath)),
    )
    .sort((left, right) => left.localeCompare(right));
}

function formatViolations(violations) {
  return violations
    .map(
      ({ path: relativePath, line, value, symbols }) =>
        `${relativePath}:${line}: ${JSON.stringify(value)} (${symbols.join(", ")})`,
    )
    .join("\n");
}

function sha256(contents) {
  return createHash("sha256").update(contents).digest("hex");
}

test("production sources consume Tier-A symbols through generated bindings", () => {
  const files = productionSourceFiles();
  assert.ok(files.length > 0, "production source inventory must not be empty");
  assert.deepEqual(
    files,
    [...files].sort((left, right) => left.localeCompare(right)),
    "production source inventory must remain deterministic",
  );

  const violations = scanTierAProductionFiles({
    registry: loadAndResolveTierARegistry(),
    files,
  });
  assert.equal(
    violations.length,
    0,
    `raw Tier-A literals found in production sources:\n${formatViolations(violations)}`,
  );
});

test("a reversible production-file mutation makes the literal guard red, then green", () => {
  const registry = loadAndResolveTierARegistry();
  const relativePath = "runtime/core/src/main.rs";
  const original = fs.readFileSync(
    path.join(REPOSITORY_ROOT, relativePath),
    "utf8",
  );
  const originalDigest = sha256(original);
  const temporaryRoot = fs.mkdtempSync(
    path.join(os.tmpdir(), "penumbra-tier-a-literal-"),
  );
  const temporaryPath = path.join(temporaryRoot, relativePath);

  try {
    fs.mkdirSync(path.dirname(temporaryPath), { recursive: true });
    fs.writeFileSync(temporaryPath, original, "utf8");
    assert.deepEqual(
      scanTierAProductionFiles({
        registry,
        files: [relativePath],
        root: temporaryRoot,
      }),
      [],
      "the real production source starts green",
    );

    fs.appendFileSync(
      temporaryPath,
      '\nconst RAW_TIER_A_RPC: &str = "/humane.aibus.AIBusService/Understand";\n',
      "utf8",
    );
    const red = scanTierAProductionFiles({
      registry,
      files: [relativePath],
      root: temporaryRoot,
    });
    assert.equal(red.length, 1, "the injected raw RPC path must make the guard red");
    assert.equal(red[0].value, "/humane.aibus.AIBusService/Understand");
    assert.deepEqual(red[0].symbols, ["rpc_path:aibus_understand"]);

    fs.writeFileSync(temporaryPath, original, "utf8");
    assert.equal(
      sha256(fs.readFileSync(temporaryPath)),
      originalDigest,
      "fixture restoration must be byte-identical",
    );
    assert.deepEqual(
      scanTierAProductionFiles({
        registry,
        files: [relativePath],
        root: temporaryRoot,
      }),
      [],
      "restoring the production source makes the guard green again",
    );
  } finally {
    fs.rmSync(temporaryRoot, { recursive: true, force: true });
  }
});
