#!/usr/bin/env -S bun --no-env-file

/**
 * Project canonical setup inputs into Center's build context.
 *
 * Center's Docker context is `./center`, so it cannot import the root contract
 * at build time. This generator is the one deliberate copy boundary: the
 * committed TypeScript projection is checked for drift with `--check`.
 */

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repositoryRoot = fileURLToPath(new URL("../../", import.meta.url));
const contractUrl = new URL("../../contracts/operator-setup.json", import.meta.url);
const outputUrl = new URL(
  "../../center/src/lib/pin-setup/generated/journey.ts",
  import.meta.url,
);
const bootstrapUrl = new URL("../../bootstrap", import.meta.url);
const bootstrapOutputUrl = new URL(
  "../../center/src/lib/pin-setup/generated/bootstrap.ts",
  import.meta.url,
);
const updateSourceUrl = new URL("../../platform/distribution/update-source.json", import.meta.url);
const cloudInitUrl = new URL("../../platform/setup/cloud-init.yaml", import.meta.url);
const cloudInitOutputUrl = new URL(
  "../../center/src/lib/pin-setup/generated/cloud-init.ts",
  import.meta.url,
);

function fail(message) {
  throw new Error(`setup projection: ${message}`);
}

function commandText(command) {
  if (!Array.isArray(command.tokens) || command.tokens.length === 0) {
    fail(`command ${command.id} has no token path`);
  }
  return `./luma ${command.tokens.join(" ")}`;
}

export function projectPinJourney(contract) {
  if (contract?.schemaVersion !== 1 || contract?.contractId !== "operator-setup") {
    fail("contracts/operator-setup.json is not a supported operator setup contract");
  }

  const commands = new Map();
  for (const command of contract.commands ?? []) {
    if (commands.has(command.id)) fail(`duplicate command id ${command.id}`);
    commands.set(command.id, command);
  }

  const journeys = (contract.journeys ?? []).filter((journey) => journey.id === "pin");
  if (journeys.length !== 1) fail("the contract must contain exactly one pin journey");
  const journey = journeys[0];
  const ids = new Set();

  // Each pin step is one owner-facing stage of Guided setup, in order, so its
  // title and summary are the labels Center shows. `commandId` names the CLI
  // equivalent when one exists. A step Center alone performs has none.
  const steps = journey.steps.map((step) => {
    if (ids.has(step.id)) fail(`duplicate pin step id ${step.id}`);
    ids.add(step.id);
    for (const field of ["title", "summary"]) {
      if (typeof step[field] !== "string" || step[field].trim() === "") {
        fail(`pin step ${step.id} has no ${field}`);
      }
    }
    if (step.centerRoute !== null && !/^\/[a-z0-9/-]*$/u.test(step.centerRoute ?? "")) {
      fail(`pin step ${step.id} has an invalid Center route`);
    }

    let command = null;
    if (step.commandId !== null) {
      const entry = commands.get(step.commandId);
      if (!entry) fail(`pin step ${step.id} references missing command ${step.commandId}`);
      if (entry.lifecycle !== "current") {
        fail(`pin step ${step.id} references non-current command ${step.commandId}`);
      }
      command = commandText(entry);
    }

    return {
      id: step.id,
      title: step.title,
      summary: step.summary,
      commandId: step.commandId,
      command,
      centerRoute: step.centerRoute,
      surface: step.surface,
      verification: step.verification,
      documentationAnchor: step.documentationAnchor,
    };
  });

  return {
    contractVersion: contract.contractVersion,
    id: journey.id,
    label: journey.label,
    steps,
  };
}

export function renderPinJourney(projection) {
  return `// @generated by platform/setup/generate.mjs from contracts/operator-setup.json. Do not edit.\n\nexport const PIN_SETUP_JOURNEY = ${JSON.stringify(projection, null, 2)} as const;\n\nexport type GeneratedPinSetupStep = (typeof PIN_SETUP_JOURNEY.steps)[number];\n`;
}

async function generatedText() {
  const contract = JSON.parse(await readFile(contractUrl, "utf8"));
  return renderPinJourney(projectPinJourney(contract));
}

// The installer as every Center serves it at /install.sh: bootstrap offers the
// serving Center's own origin as the new server's update source. The raw copy
// names platform/distribution/update-source.json's origin on one line, which
// bootstrapForOrigin replaces (the same substitution as cloud-init's
// REPLACE_ME_CENTER_HOST).
async function generatedBootstrapText() {
  const source = await readFile(bootstrapUrl, "utf8");
  const { origin } = JSON.parse(await readFile(updateSourceUrl, "utf8"));
  const line = `LUMA_UPDATE_SOURCE_DEFAULT="${origin}"`;
  if (source.split("\n").filter((entry) => entry.startsWith("LUMA_UPDATE_SOURCE_DEFAULT=")).join("\n") !== line) {
    fail(`bootstrap must set exactly one ${line}, the origin in platform/distribution/update-source.json`);
  }
  return [
    "// @generated by platform/setup/generate.mjs from /bootstrap. Do not edit.",
    "",
    `export const LUMA_BOOTSTRAP = ${JSON.stringify(source)};`,
    "",
    "// The committed default update source line of LUMA_BOOTSTRAP.",
    `const UPDATE_SOURCE_LINE = ${JSON.stringify(line)};`,
    "const SERVING_ORIGIN = /^(?:https:\\/\\/[A-Za-z0-9.-]+|http:\\/\\/(?:localhost|127\\.0\\.0\\.1|\\[::1\\]))(?::[0-9]{1,5})?$/u;",
    "",
    "// LUMA_BOOTSTRAP with ORIGIN, the serving Center, as the update source it",
    "// offers the new server.",
    "export function bootstrapForOrigin(origin: string): string {",
    "  if (!SERVING_ORIGIN.test(origin)) throw new Error(`not a Center origin: ${origin}`);",
    "  return LUMA_BOOTSTRAP.replace(UPDATE_SOURCE_LINE, `LUMA_UPDATE_SOURCE_DEFAULT=\"${origin}\"`);",
    "}",
    "",
  ].join("\n");
}

// The cloud-init template Center serves at /cloud-init.yaml beside /install.sh.
async function generatedCloudInitText() {
  const source = await readFile(cloudInitUrl, "utf8");
  if (!source.startsWith("#cloud-config\n")) fail("platform/setup/cloud-init.yaml must start with #cloud-config");
  return `// @generated by platform/setup/generate.mjs from platform/setup/cloud-init.yaml. Do not edit.\n\nexport const LUMA_CLOUD_INIT = ${JSON.stringify(source)};\n`;
}

async function main(argv) {
  if (argv.length !== 1 || !["--write", "--check", "--help"].includes(argv[0])) {
    fail("usage: bun platform/setup/generate.mjs --write|--check");
  }
  if (argv[0] === "--help") {
    process.stdout.write("Usage: bun platform/setup/generate.mjs --write|--check\n");
    return;
  }

  const expected = await generatedText();
  const expectedBootstrap = await generatedBootstrapText();
  const expectedCloudInit = await generatedCloudInitText();
  if (argv[0] === "--write") {
    await mkdir(new URL("../../center/src/lib/pin-setup/generated/", import.meta.url), {
      recursive: true,
    });
    await writeFile(outputUrl, expected, "utf8");
    await writeFile(bootstrapOutputUrl, expectedBootstrap, "utf8");
    await writeFile(cloudInitOutputUrl, expectedCloudInit, "utf8");
    process.stdout.write(
      `Wrote Center setup projections from contracts/operator-setup.json, bootstrap, and platform/setup/cloud-init.yaml\n`,
    );
    return;
  }

  let actual = null;
  try {
    actual = await readFile(outputUrl, "utf8");
  } catch (error) {
    if (error?.code !== "ENOENT") throw error;
  }
  if (actual !== expected) {
    fail("Center setup projection is stale; run bun platform/setup/generate.mjs --write");
  }
  let actualBootstrap = null;
  try {
    actualBootstrap = await readFile(bootstrapOutputUrl, "utf8");
  } catch (error) {
    if (error?.code !== "ENOENT") throw error;
  }
  if (actualBootstrap !== expectedBootstrap) {
    fail("Center bootstrap projection is stale; run bun platform/setup/generate.mjs --write");
  }
  let actualCloudInit = null;
  try {
    actualCloudInit = await readFile(cloudInitOutputUrl, "utf8");
  } catch (error) {
    if (error?.code !== "ENOENT") throw error;
  }
  if (actualCloudInit !== expectedCloudInit) {
    fail("Center cloud-init projection is stale; run bun platform/setup/generate.mjs --write");
  }
  process.stdout.write("Center setup projection is in sync\n");
}

const invokedPath = process.argv[1] ? resolve(process.argv[1]) : null;
if (invokedPath === fileURLToPath(import.meta.url)) {
  main(process.argv.slice(2)).catch((error) => {
    process.stderr.write(`${error.message}\n`);
    process.exitCode = 1;
  });
}
