#!/usr/bin/env node

/**
 * Project canonical setup inputs into Center's build context.
 *
 * Center's Docker context is `./center`, so it cannot import the root contract
 * at build time. This generator is the one deliberate copy boundary: the
 * committed TypeScript projection is checked for drift with `--check`.
 */

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repositoryRoot = fileURLToPath(new URL("../../", import.meta.url));
const contractUrl = new URL("../../contracts/operator-setup.json", import.meta.url);
const outputUrl = new URL(
  "../../center/src/lib/pin-setup/generated/journey.ts",
  import.meta.url,
);
const bootstrapUrl = new URL("../../bootstrap", import.meta.url);
const bootstrapOutputUrl = new URL(
  "../../center/src/lib/pin-setup/generated/bootstrap.ts",
  import.meta.url,
);

function fail(message) {
  throw new Error(`setup projection: ${message}`);
}

function commandText(command) {
  if (!Array.isArray(command.tokens) || command.tokens.length === 0) {
    fail(`command ${command.id} has no token path`);
  }
  return `./revival ${command.tokens.join(" ")}`;
}

export function projectPinJourney(contract) {
  if (contract?.schemaVersion !== 1 || contract?.contractId !== "operator-setup") {
    fail("contracts/operator-setup.json is not a supported operator setup contract");
  }

  const commands = new Map();
  for (const command of contract.commands ?? []) {
    if (commands.has(command.id)) fail(`duplicate command id ${command.id}`);
    commands.set(command.id, command);
  }

  const journeys = (contract.journeys ?? []).filter((journey) => journey.id === "pin");
  if (journeys.length !== 1) fail("the contract must contain exactly one pin journey");
  const journey = journeys[0];
  const ids = new Set();

  const steps = journey.steps.map((step) => {
    if (ids.has(step.id)) fail(`duplicate pin step id ${step.id}`);
    ids.add(step.id);

    const command = commands.get(step.commandId);
    if (!command) fail(`pin step ${step.id} references missing command ${step.commandId}`);
    if (command.lifecycle !== "current") {
      fail(`pin step ${step.id} references non-current command ${step.commandId}`);
    }

    return {
      id: step.id,
      title: step.title,
      commandId: step.commandId,
      command: commandText(command),
      centerRoute: step.centerRoute,
      surface: step.surface,
      verification: step.verification,
      documentationAnchor: step.documentationAnchor,
    };
  });

  return {
    contractVersion: contract.contractVersion,
    id: journey.id,
    label: journey.label,
    steps,
  };
}

export function renderPinJourney(projection) {
  return `// @generated by platform/setup/generate.mjs from contracts/operator-setup.json. Do not edit.\n\nexport const PIN_SETUP_JOURNEY = ${JSON.stringify(projection, null, 2)} as const;\n\nexport type GeneratedPinSetupStep = (typeof PIN_SETUP_JOURNEY.steps)[number];\n`;
}

async function generatedText() {
  const contract = JSON.parse(await readFile(contractUrl, "utf8"));
  return renderPinJourney(projectPinJourney(contract));
}

async function generatedBootstrapText() {
  const source = await readFile(bootstrapUrl, "utf8");
  return `// @generated by platform/setup/generate.mjs from /bootstrap. Do not edit.\n\nexport const REVIVAL_BOOTSTRAP = ${JSON.stringify(source)};\n`;
}

async function main(argv) {
  if (argv.length !== 1 || !["--write", "--check", "--help"].includes(argv[0])) {
    fail("usage: node platform/setup/generate.mjs --write|--check");
  }
  if (argv[0] === "--help") {
    process.stdout.write("Usage: node platform/setup/generate.mjs --write|--check\n");
    return;
  }

  const expected = await generatedText();
  const expectedBootstrap = await generatedBootstrapText();
  if (argv[0] === "--write") {
    await mkdir(new URL("../../center/src/lib/pin-setup/generated/", import.meta.url), {
      recursive: true,
    });
    await writeFile(outputUrl, expected, "utf8");
    await writeFile(bootstrapOutputUrl, expectedBootstrap, "utf8");
    process.stdout.write(
      `Wrote Center setup projections from contracts/operator-setup.json and bootstrap\n`,
    );
    return;
  }

  let actual = null;
  try {
    actual = await readFile(outputUrl, "utf8");
  } catch (error) {
    if (error?.code !== "ENOENT") throw error;
  }
  if (actual !== expected) {
    fail("Center setup projection is stale; run node platform/setup/generate.mjs --write");
  }
  let actualBootstrap = null;
  try {
    actualBootstrap = await readFile(bootstrapOutputUrl, "utf8");
  } catch (error) {
    if (error?.code !== "ENOENT") throw error;
  }
  if (actualBootstrap !== expectedBootstrap) {
    fail("Center bootstrap projection is stale; run node platform/setup/generate.mjs --write");
  }
  process.stdout.write("Center setup projection is in sync\n");
}

const invokedPath = process.argv[1] ? resolve(process.argv[1]) : null;
if (invokedPath === fileURLToPath(import.meta.url)) {
  main(process.argv.slice(2)).catch((error) => {
    process.stderr.write(`${error.message}\n`);
    process.exitCode = 1;
  });
}
