// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod carry {

    #[allow(unused_imports, dead_code)]
    pub mod krypton {

        #[deprecated(
            since = "2.0.0",
            note = "Use associated constants instead. This will no longer be generated in 2021."
        )]
        pub const ENUM_MIN_KR_ALGORITHM: i8 = 0;
        #[deprecated(
            since = "2.0.0",
            note = "Use associated constants instead. This will no longer be generated in 2021."
        )]
        pub const ENUM_MAX_KR_ALGORITHM: i8 = 2;
        #[deprecated(
            since = "2.0.0",
            note = "Use associated constants instead. This will no longer be generated in 2021."
        )]
        #[allow(non_camel_case_types)]
        pub const ENUM_VALUES_KR_ALGORITHM: [KrAlgorithm; 2] =
            [KrAlgorithm::AES_GCM, KrAlgorithm::RSA_OAEP];

        #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
        #[repr(transparent)]
        pub struct KrAlgorithm(pub i8);
        #[allow(non_upper_case_globals)]
        impl KrAlgorithm {
            pub const AES_GCM: Self = Self(0);
            pub const RSA_OAEP: Self = Self(2);

            pub const ENUM_MIN: i8 = 0;
            pub const ENUM_MAX: i8 = 2;
            pub const ENUM_VALUES: &'static [Self] = &[Self::AES_GCM, Self::RSA_OAEP];
            /// Returns the variant's name or "" if unknown.
            pub fn variant_name(self) -> Option<&'static str> {
                match self {
                    Self::AES_GCM => Some("AES_GCM"),
                    Self::RSA_OAEP => Some("RSA_OAEP"),
                    _ => None,
                }
            }
        }
        impl ::core::fmt::Debug for KrAlgorithm {
            fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
                if let Some(name) = self.variant_name() {
                    f.write_str(name)
                } else {
                    f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
                }
            }
        }
        impl<'a> ::flatbuffers::Follow<'a> for KrAlgorithm {
            type Inner = Self;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                let b = unsafe { ::flatbuffers::read_scalar_at::<i8>(buf, loc) };
                Self(b)
            }
        }

        impl ::flatbuffers::Push for KrAlgorithm {
            type Output = KrAlgorithm;
            #[inline]
            unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
                unsafe { ::flatbuffers::emplace_scalar::<i8>(dst, self.0) };
            }
        }

        impl ::flatbuffers::EndianScalar for KrAlgorithm {
            type Scalar = i8;
            #[inline]
            fn to_little_endian(self) -> i8 {
                self.0.to_le()
            }
            #[inline]
            #[allow(clippy::wrong_self_convention)]
            fn from_little_endian(v: i8) -> Self {
                let b = i8::from_le(v);
                Self(b)
            }
        }

        impl<'a> ::flatbuffers::Verifiable for KrAlgorithm {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                i8::run_verifier(v, pos)
            }
        }

        impl ::flatbuffers::SimpleToVerifyInSlice for KrAlgorithm {}
        pub enum CiphertextEnvelopeOffset {}
        #[derive(Copy, Clone, PartialEq)]

        pub struct CiphertextEnvelope<'a> {
            pub _tab: ::flatbuffers::Table<'a>,
        }

        impl<'a> ::flatbuffers::Follow<'a> for CiphertextEnvelope<'a> {
            type Inner = CiphertextEnvelope<'a>;
            #[inline]
            unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                Self {
                    _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                }
            }
        }

        impl<'a> CiphertextEnvelope<'a> {
            pub const VT_KID: ::flatbuffers::VOffsetT = 4;
            pub const VT_ALGO: ::flatbuffers::VOffsetT = 6;
            pub const VT_AAD: ::flatbuffers::VOffsetT = 8;
            pub const VT_IV: ::flatbuffers::VOffsetT = 10;
            pub const VT_AUTHTAG: ::flatbuffers::VOffsetT = 12;
            pub const VT_CIPHERTEXT: ::flatbuffers::VOffsetT = 14;

            #[inline]
            pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                CiphertextEnvelope { _tab: table }
            }
            #[allow(unused_mut)]
            pub fn create<
                'bldr: 'args,
                'args: 'mut_bldr,
                'mut_bldr,
                A: ::flatbuffers::Allocator + 'bldr,
            >(
                _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                args: &'args CiphertextEnvelopeArgs<'args>,
            ) -> ::flatbuffers::WIPOffset<CiphertextEnvelope<'bldr>> {
                let mut builder = CiphertextEnvelopeBuilder::new(_fbb);
                if let Some(x) = args.ciphertext {
                    builder.add_ciphertext(x);
                }
                if let Some(x) = args.authTag {
                    builder.add_authTag(x);
                }
                if let Some(x) = args.iv {
                    builder.add_iv(x);
                }
                if let Some(x) = args.aad {
                    builder.add_aad(x);
                }
                if let Some(x) = args.kid {
                    builder.add_kid(x);
                }
                builder.add_algo(args.algo);
                builder.finish()
            }

            #[inline]
            pub fn kid(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(
                            CiphertextEnvelope::VT_KID,
                            None,
                        )
                }
            }
            #[inline]
            pub fn algo(&self) -> KrAlgorithm {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<KrAlgorithm>(CiphertextEnvelope::VT_ALGO, Some(KrAlgorithm::AES_GCM))
                        .unwrap()
                }
            }
            #[inline]
            pub fn aad(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(
                            CiphertextEnvelope::VT_AAD,
                            None,
                        )
                }
            }
            #[inline]
            pub fn iv(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(
                            CiphertextEnvelope::VT_IV,
                            None,
                        )
                }
            }
            #[inline]
            pub fn authTag(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(
                            CiphertextEnvelope::VT_AUTHTAG,
                            None,
                        )
                }
            }
            #[inline]
            pub fn ciphertext(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
                // Safety:
                // Created from valid Table for this object
                // which contains a valid value in this slot
                unsafe {
                    self._tab
                        .get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(
                            CiphertextEnvelope::VT_CIPHERTEXT,
                            None,
                        )
                }
            }
        }

        impl ::flatbuffers::Verifiable for CiphertextEnvelope<'_> {
            #[inline]
            fn run_verifier(
                v: &mut ::flatbuffers::Verifier,
                pos: usize,
            ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                v.visit_table(pos)?
                    .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>(
                        "kid",
                        Self::VT_KID,
                        false,
                    )?
                    .visit_field::<KrAlgorithm>("algo", Self::VT_ALGO, false)?
                    .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>(
                        "aad",
                        Self::VT_AAD,
                        false,
                    )?
                    .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>(
                        "iv",
                        Self::VT_IV,
                        false,
                    )?
                    .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>(
                        "authTag",
                        Self::VT_AUTHTAG,
                        false,
                    )?
                    .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>(
                        "ciphertext",
                        Self::VT_CIPHERTEXT,
                        false,
                    )?
                    .finish();
                Ok(())
            }
        }
        pub struct CiphertextEnvelopeArgs<'a> {
            pub kid: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
            pub algo: KrAlgorithm,
            pub aad: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
            pub iv: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
            pub authTag: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
            pub ciphertext: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
        }
        impl<'a> Default for CiphertextEnvelopeArgs<'a> {
            #[inline]
            fn default() -> Self {
                CiphertextEnvelopeArgs {
                    kid: None,
                    algo: KrAlgorithm::AES_GCM,
                    aad: None,
                    iv: None,
                    authTag: None,
                    ciphertext: None,
                }
            }
        }

        pub struct CiphertextEnvelopeBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
            fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
        }
        impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> CiphertextEnvelopeBuilder<'a, 'b, A> {
            #[inline]
            pub fn add_kid(
                &mut self,
                kid: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b, u8>>,
            ) {
                self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                    CiphertextEnvelope::VT_KID,
                    kid,
                );
            }
            #[inline]
            pub fn add_algo(&mut self, algo: KrAlgorithm) {
                self.fbb_.push_slot::<KrAlgorithm>(
                    CiphertextEnvelope::VT_ALGO,
                    algo,
                    KrAlgorithm::AES_GCM,
                );
            }
            #[inline]
            pub fn add_aad(
                &mut self,
                aad: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b, u8>>,
            ) {
                self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                    CiphertextEnvelope::VT_AAD,
                    aad,
                );
            }
            #[inline]
            pub fn add_iv(&mut self, iv: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b, u8>>) {
                self.fbb_
                    .push_slot_always::<::flatbuffers::WIPOffset<_>>(CiphertextEnvelope::VT_IV, iv);
            }
            #[inline]
            pub fn add_authTag(
                &mut self,
                authTag: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b, u8>>,
            ) {
                self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                    CiphertextEnvelope::VT_AUTHTAG,
                    authTag,
                );
            }
            #[inline]
            pub fn add_ciphertext(
                &mut self,
                ciphertext: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b, u8>>,
            ) {
                self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                    CiphertextEnvelope::VT_CIPHERTEXT,
                    ciphertext,
                );
            }
            #[inline]
            pub fn new(
                _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            ) -> CiphertextEnvelopeBuilder<'a, 'b, A> {
                let start = _fbb.start_table();
                CiphertextEnvelopeBuilder {
                    fbb_: _fbb,
                    start_: start,
                }
            }
            #[inline]
            pub fn finish(self) -> ::flatbuffers::WIPOffset<CiphertextEnvelope<'a>> {
                let o = self.fbb_.end_table(self.start_);
                ::flatbuffers::WIPOffset::new(o.value())
            }
        }

        impl ::core::fmt::Debug for CiphertextEnvelope<'_> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                let mut ds = f.debug_struct("CiphertextEnvelope");
                ds.field("kid", &self.kid());
                ds.field("algo", &self.algo());
                ds.field("aad", &self.aad());
                ds.field("iv", &self.iv());
                ds.field("authTag", &self.authTag());
                ds.field("ciphertext", &self.ciphertext());
                ds.finish()
            }
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a `CiphertextEnvelope`
        /// and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_ciphertext_envelope_unchecked`.
        pub fn root_as_ciphertext_envelope(
            buf: &[u8],
        ) -> Result<CiphertextEnvelope<'_>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::root::<CiphertextEnvelope>(buf)
        }
        #[inline]
        /// Verifies that a buffer of bytes contains a size prefixed
        /// `CiphertextEnvelope` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `size_prefixed_root_as_ciphertext_envelope_unchecked`.
        pub fn size_prefixed_root_as_ciphertext_envelope(
            buf: &[u8],
        ) -> Result<CiphertextEnvelope<'_>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::size_prefixed_root::<CiphertextEnvelope>(buf)
        }
        #[inline]
        /// Verifies, with the given options, that a buffer of bytes
        /// contains a `CiphertextEnvelope` and returns it.
        /// Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_ciphertext_envelope_unchecked`.
        pub fn root_as_ciphertext_envelope_with_opts<'b, 'o>(
            opts: &'o ::flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<CiphertextEnvelope<'b>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::root_with_opts::<CiphertextEnvelope<'b>>(opts, buf)
        }
        #[inline]
        /// Verifies, with the given verifier options, that a buffer of
        /// bytes contains a size prefixed `CiphertextEnvelope` and returns
        /// it. Note that verification is still experimental and may not
        /// catch every error, or be maximally performant. For the
        /// previous, unchecked, behavior use
        /// `root_as_ciphertext_envelope_unchecked`.
        pub fn size_prefixed_root_as_ciphertext_envelope_with_opts<'b, 'o>(
            opts: &'o ::flatbuffers::VerifierOptions,
            buf: &'b [u8],
        ) -> Result<CiphertextEnvelope<'b>, ::flatbuffers::InvalidFlatbuffer> {
            ::flatbuffers::size_prefixed_root_with_opts::<CiphertextEnvelope<'b>>(opts, buf)
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a CiphertextEnvelope and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid `CiphertextEnvelope`.
        pub unsafe fn root_as_ciphertext_envelope_unchecked(buf: &[u8]) -> CiphertextEnvelope<'_> {
            unsafe { ::flatbuffers::root_unchecked::<CiphertextEnvelope>(buf) }
        }
        #[inline]
        /// Assumes, without verification, that a buffer of bytes contains a size prefixed CiphertextEnvelope and returns it.
        /// # Safety
        /// Callers must trust the given bytes do indeed contain a valid size prefixed `CiphertextEnvelope`.
        pub unsafe fn size_prefixed_root_as_ciphertext_envelope_unchecked(
            buf: &[u8],
        ) -> CiphertextEnvelope<'_> {
            unsafe { ::flatbuffers::size_prefixed_root_unchecked::<CiphertextEnvelope>(buf) }
        }
        pub const CIPHERTEXT_ENVELOPE_IDENTIFIER: &str = "HMCT";

        #[inline]
        pub fn ciphertext_envelope_buffer_has_identifier(buf: &[u8]) -> bool {
            ::flatbuffers::buffer_has_identifier(buf, CIPHERTEXT_ENVELOPE_IDENTIFIER, false)
        }

        #[inline]
        pub fn ciphertext_envelope_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
            ::flatbuffers::buffer_has_identifier(buf, CIPHERTEXT_ENVELOPE_IDENTIFIER, true)
        }

        #[inline]
        pub fn finish_ciphertext_envelope_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
            fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            root: ::flatbuffers::WIPOffset<CiphertextEnvelope<'a>>,
        ) {
            fbb.finish(root, Some(CIPHERTEXT_ENVELOPE_IDENTIFIER));
        }

        #[inline]
        pub fn finish_size_prefixed_ciphertext_envelope_buffer<
            'a,
            'b,
            A: ::flatbuffers::Allocator + 'a,
        >(
            fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
            root: ::flatbuffers::WIPOffset<CiphertextEnvelope<'a>>,
        ) {
            fbb.finish_size_prefixed(root, Some(CIPHERTEXT_ENVELOPE_IDENTIFIER));
        }
    } // pub mod krypton
} // pub mod carry
