// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;

#[allow(unused_imports, dead_code)]
pub mod cosmos {

    #[allow(unused_imports, dead_code)]
    pub mod krypton {

        #[allow(unused_imports, dead_code)]
        pub mod secureasset {

            pub enum HeaderOffset {}
            #[derive(Copy, Clone, PartialEq)]

            pub struct Header<'a> {
                pub _tab: ::flatbuffers::Table<'a>,
            }

            impl<'a> ::flatbuffers::Follow<'a> for Header<'a> {
                type Inner = Header<'a>;
                #[inline]
                unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                    Self {
                        _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                    }
                }
            }

            impl<'a> Header<'a> {
                pub const VT_KID: ::flatbuffers::VOffsetT = 4;
                pub const VT_ALGORITHM: ::flatbuffers::VOffsetT = 6;

                #[inline]
                pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                    Header { _tab: table }
                }
                #[allow(unused_mut)]
                pub fn create<
                    'bldr: 'args,
                    'args: 'mut_bldr,
                    'mut_bldr,
                    A: ::flatbuffers::Allocator + 'bldr,
                >(
                    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                    args: &'args HeaderArgs<'args>,
                ) -> ::flatbuffers::WIPOffset<Header<'bldr>> {
                    let mut builder = HeaderBuilder::new(_fbb);
                    if let Some(x) = args.kid {
                        builder.add_kid(x);
                    }
                    builder.add_algorithm(args.algorithm);
                    builder.finish()
                }

                #[inline]
                pub fn kid(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
                    // Safety:
                    // Created from valid Table for this object
                    // which contains a valid value in this slot
                    unsafe {
                        self._tab
                            .get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(
                                Header::VT_KID,
                                None,
                            )
                    }
                }
                #[inline]
                pub fn algorithm(&self) -> u8 {
                    // Safety:
                    // Created from valid Table for this object
                    // which contains a valid value in this slot
                    unsafe { self._tab.get::<u8>(Header::VT_ALGORITHM, Some(1)).unwrap() }
                }
            }

            impl ::flatbuffers::Verifiable for Header<'_> {
                #[inline]
                fn run_verifier(
                    v: &mut ::flatbuffers::Verifier,
                    pos: usize,
                ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("kid", Self::VT_KID, false)?
     .visit_field::<u8>("algorithm", Self::VT_ALGORITHM, false)?
     .finish();
                    Ok(())
                }
            }
            pub struct HeaderArgs<'a> {
                pub kid: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
                pub algorithm: u8,
            }
            impl<'a> Default for HeaderArgs<'a> {
                #[inline]
                fn default() -> Self {
                    HeaderArgs {
                        kid: None,
                        algorithm: 1,
                    }
                }
            }

            pub struct HeaderBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
                fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
                start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
            }
            impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> HeaderBuilder<'a, 'b, A> {
                #[inline]
                pub fn add_kid(
                    &mut self,
                    kid: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b, u8>>,
                ) {
                    self.fbb_
                        .push_slot_always::<::flatbuffers::WIPOffset<_>>(Header::VT_KID, kid);
                }
                #[inline]
                pub fn add_algorithm(&mut self, algorithm: u8) {
                    self.fbb_
                        .push_slot::<u8>(Header::VT_ALGORITHM, algorithm, 1);
                }
                #[inline]
                pub fn new(
                    _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
                ) -> HeaderBuilder<'a, 'b, A> {
                    let start = _fbb.start_table();
                    HeaderBuilder {
                        fbb_: _fbb,
                        start_: start,
                    }
                }
                #[inline]
                pub fn finish(self) -> ::flatbuffers::WIPOffset<Header<'a>> {
                    let o = self.fbb_.end_table(self.start_);
                    ::flatbuffers::WIPOffset::new(o.value())
                }
            }

            impl ::core::fmt::Debug for Header<'_> {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    let mut ds = f.debug_struct("Header");
                    ds.field("kid", &self.kid());
                    ds.field("algorithm", &self.algorithm());
                    ds.finish()
                }
            }
            pub enum AssetBindingOffset {}
            #[derive(Copy, Clone, PartialEq)]

            pub struct AssetBinding<'a> {
                pub _tab: ::flatbuffers::Table<'a>,
            }

            impl<'a> ::flatbuffers::Follow<'a> for AssetBinding<'a> {
                type Inner = AssetBinding<'a>;
                #[inline]
                unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                    Self {
                        _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                    }
                }
            }

            impl<'a> AssetBinding<'a> {
                pub const VT_ENCODING: ::flatbuffers::VOffsetT = 4;
                pub const VT_DOMAIN: ::flatbuffers::VOffsetT = 6;
                pub const VT_OBJECT_ID: ::flatbuffers::VOffsetT = 8;
                pub const VT_METADATA: ::flatbuffers::VOffsetT = 10;

                #[inline]
                pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                    AssetBinding { _tab: table }
                }
                #[allow(unused_mut)]
                pub fn create<
                    'bldr: 'args,
                    'args: 'mut_bldr,
                    'mut_bldr,
                    A: ::flatbuffers::Allocator + 'bldr,
                >(
                    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                    args: &'args AssetBindingArgs<'args>,
                ) -> ::flatbuffers::WIPOffset<AssetBinding<'bldr>> {
                    let mut builder = AssetBindingBuilder::new(_fbb);
                    if let Some(x) = args.metadata {
                        builder.add_metadata(x);
                    }
                    builder.add_object_id(args.object_id);
                    builder.add_domain(args.domain);
                    builder.add_encoding(args.encoding);
                    builder.finish()
                }

                #[inline]
                pub fn encoding(&self) -> u8 {
                    // Safety:
                    // Created from valid Table for this object
                    // which contains a valid value in this slot
                    unsafe {
                        self._tab
                            .get::<u8>(AssetBinding::VT_ENCODING, Some(0))
                            .unwrap()
                    }
                }
                #[inline]
                pub fn domain(&self) -> i32 {
                    // Safety:
                    // Created from valid Table for this object
                    // which contains a valid value in this slot
                    unsafe {
                        self._tab
                            .get::<i32>(AssetBinding::VT_DOMAIN, Some(0))
                            .unwrap()
                    }
                }
                #[inline]
                pub fn object_id(&self) -> i32 {
                    // Safety:
                    // Created from valid Table for this object
                    // which contains a valid value in this slot
                    unsafe {
                        self._tab
                            .get::<i32>(AssetBinding::VT_OBJECT_ID, Some(0))
                            .unwrap()
                    }
                }
                #[inline]
                pub fn metadata(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
                    // Safety:
                    // Created from valid Table for this object
                    // which contains a valid value in this slot
                    unsafe {
                        self._tab
                            .get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(
                                AssetBinding::VT_METADATA,
                                None,
                            )
                    }
                }
            }

            impl ::flatbuffers::Verifiable for AssetBinding<'_> {
                #[inline]
                fn run_verifier(
                    v: &mut ::flatbuffers::Verifier,
                    pos: usize,
                ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                    v.visit_table(pos)?
     .visit_field::<u8>("encoding", Self::VT_ENCODING, false)?
     .visit_field::<i32>("domain", Self::VT_DOMAIN, false)?
     .visit_field::<i32>("object_id", Self::VT_OBJECT_ID, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("metadata", Self::VT_METADATA, false)?
     .finish();
                    Ok(())
                }
            }
            pub struct AssetBindingArgs<'a> {
                pub encoding: u8,
                pub domain: i32,
                pub object_id: i32,
                pub metadata: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
            }
            impl<'a> Default for AssetBindingArgs<'a> {
                #[inline]
                fn default() -> Self {
                    AssetBindingArgs {
                        encoding: 0,
                        domain: 0,
                        object_id: 0,
                        metadata: None,
                    }
                }
            }

            pub struct AssetBindingBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
                fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
                start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
            }
            impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> AssetBindingBuilder<'a, 'b, A> {
                #[inline]
                pub fn add_encoding(&mut self, encoding: u8) {
                    self.fbb_
                        .push_slot::<u8>(AssetBinding::VT_ENCODING, encoding, 0);
                }
                #[inline]
                pub fn add_domain(&mut self, domain: i32) {
                    self.fbb_
                        .push_slot::<i32>(AssetBinding::VT_DOMAIN, domain, 0);
                }
                #[inline]
                pub fn add_object_id(&mut self, object_id: i32) {
                    self.fbb_
                        .push_slot::<i32>(AssetBinding::VT_OBJECT_ID, object_id, 0);
                }
                #[inline]
                pub fn add_metadata(
                    &mut self,
                    metadata: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b, u8>>,
                ) {
                    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                        AssetBinding::VT_METADATA,
                        metadata,
                    );
                }
                #[inline]
                pub fn new(
                    _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
                ) -> AssetBindingBuilder<'a, 'b, A> {
                    let start = _fbb.start_table();
                    AssetBindingBuilder {
                        fbb_: _fbb,
                        start_: start,
                    }
                }
                #[inline]
                pub fn finish(self) -> ::flatbuffers::WIPOffset<AssetBinding<'a>> {
                    let o = self.fbb_.end_table(self.start_);
                    ::flatbuffers::WIPOffset::new(o.value())
                }
            }

            impl ::core::fmt::Debug for AssetBinding<'_> {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    let mut ds = f.debug_struct("AssetBinding");
                    ds.field("encoding", &self.encoding());
                    ds.field("domain", &self.domain());
                    ds.field("object_id", &self.object_id());
                    ds.field("metadata", &self.metadata());
                    ds.finish()
                }
            }
            pub enum SecureAssetOffset {}
            #[derive(Copy, Clone, PartialEq)]

            pub struct SecureAsset<'a> {
                pub _tab: ::flatbuffers::Table<'a>,
            }

            impl<'a> ::flatbuffers::Follow<'a> for SecureAsset<'a> {
                type Inner = SecureAsset<'a>;
                #[inline]
                unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
                    Self {
                        _tab: unsafe { ::flatbuffers::Table::new(buf, loc) },
                    }
                }
            }

            impl<'a> SecureAsset<'a> {
                pub const VT_HEADER: ::flatbuffers::VOffsetT = 4;
                pub const VT_AAD: ::flatbuffers::VOffsetT = 6;
                pub const VT_WRAPPED_CEK: ::flatbuffers::VOffsetT = 8;
                pub const VT_IV: ::flatbuffers::VOffsetT = 10;
                pub const VT_AUTH_TAG: ::flatbuffers::VOffsetT = 12;
                pub const VT_CIPHERTEXT: ::flatbuffers::VOffsetT = 14;

                #[inline]
                pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
                    SecureAsset { _tab: table }
                }
                #[allow(unused_mut)]
                pub fn create<
                    'bldr: 'args,
                    'args: 'mut_bldr,
                    'mut_bldr,
                    A: ::flatbuffers::Allocator + 'bldr,
                >(
                    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
                    args: &'args SecureAssetArgs<'args>,
                ) -> ::flatbuffers::WIPOffset<SecureAsset<'bldr>> {
                    let mut builder = SecureAssetBuilder::new(_fbb);
                    if let Some(x) = args.ciphertext {
                        builder.add_ciphertext(x);
                    }
                    if let Some(x) = args.auth_tag {
                        builder.add_auth_tag(x);
                    }
                    if let Some(x) = args.iv {
                        builder.add_iv(x);
                    }
                    if let Some(x) = args.wrapped_cek {
                        builder.add_wrapped_cek(x);
                    }
                    if let Some(x) = args.aad {
                        builder.add_aad(x);
                    }
                    if let Some(x) = args.header {
                        builder.add_header(x);
                    }
                    builder.finish()
                }

                #[inline]
                pub fn header(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
                    // Safety:
                    // Created from valid Table for this object
                    // which contains a valid value in this slot
                    unsafe {
                        self._tab
                            .get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(
                                SecureAsset::VT_HEADER,
                                None,
                            )
                    }
                }
                #[inline]
                pub fn aad(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
                    // Safety:
                    // Created from valid Table for this object
                    // which contains a valid value in this slot
                    unsafe {
                        self._tab
                            .get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(
                                SecureAsset::VT_AAD,
                                None,
                            )
                    }
                }
                #[inline]
                pub fn wrapped_cek(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
                    // Safety:
                    // Created from valid Table for this object
                    // which contains a valid value in this slot
                    unsafe {
                        self._tab
                            .get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(
                                SecureAsset::VT_WRAPPED_CEK,
                                None,
                            )
                    }
                }
                #[inline]
                pub fn iv(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
                    // Safety:
                    // Created from valid Table for this object
                    // which contains a valid value in this slot
                    unsafe {
                        self._tab
                            .get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(
                                SecureAsset::VT_IV,
                                None,
                            )
                    }
                }
                #[inline]
                pub fn auth_tag(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
                    // Safety:
                    // Created from valid Table for this object
                    // which contains a valid value in this slot
                    unsafe {
                        self._tab
                            .get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(
                                SecureAsset::VT_AUTH_TAG,
                                None,
                            )
                    }
                }
                #[inline]
                pub fn ciphertext(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
                    // Safety:
                    // Created from valid Table for this object
                    // which contains a valid value in this slot
                    unsafe {
                        self._tab
                            .get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(
                                SecureAsset::VT_CIPHERTEXT,
                                None,
                            )
                    }
                }
            }

            impl ::flatbuffers::Verifiable for SecureAsset<'_> {
                #[inline]
                fn run_verifier(
                    v: &mut ::flatbuffers::Verifier,
                    pos: usize,
                ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
                    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("header", Self::VT_HEADER, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("aad", Self::VT_AAD, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("wrapped_cek", Self::VT_WRAPPED_CEK, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("iv", Self::VT_IV, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("auth_tag", Self::VT_AUTH_TAG, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("ciphertext", Self::VT_CIPHERTEXT, false)?
     .finish();
                    Ok(())
                }
            }
            pub struct SecureAssetArgs<'a> {
                pub header: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
                pub aad: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
                pub wrapped_cek: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
                pub iv: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
                pub auth_tag: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
                pub ciphertext: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
            }
            impl<'a> Default for SecureAssetArgs<'a> {
                #[inline]
                fn default() -> Self {
                    SecureAssetArgs {
                        header: None,
                        aad: None,
                        wrapped_cek: None,
                        iv: None,
                        auth_tag: None,
                        ciphertext: None,
                    }
                }
            }

            pub struct SecureAssetBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
                fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
                start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
            }
            impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> SecureAssetBuilder<'a, 'b, A> {
                #[inline]
                pub fn add_header(
                    &mut self,
                    header: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b, u8>>,
                ) {
                    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                        SecureAsset::VT_HEADER,
                        header,
                    );
                }
                #[inline]
                pub fn add_aad(
                    &mut self,
                    aad: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b, u8>>,
                ) {
                    self.fbb_
                        .push_slot_always::<::flatbuffers::WIPOffset<_>>(SecureAsset::VT_AAD, aad);
                }
                #[inline]
                pub fn add_wrapped_cek(
                    &mut self,
                    wrapped_cek: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b, u8>>,
                ) {
                    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                        SecureAsset::VT_WRAPPED_CEK,
                        wrapped_cek,
                    );
                }
                #[inline]
                pub fn add_iv(
                    &mut self,
                    iv: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b, u8>>,
                ) {
                    self.fbb_
                        .push_slot_always::<::flatbuffers::WIPOffset<_>>(SecureAsset::VT_IV, iv);
                }
                #[inline]
                pub fn add_auth_tag(
                    &mut self,
                    auth_tag: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b, u8>>,
                ) {
                    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                        SecureAsset::VT_AUTH_TAG,
                        auth_tag,
                    );
                }
                #[inline]
                pub fn add_ciphertext(
                    &mut self,
                    ciphertext: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b, u8>>,
                ) {
                    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(
                        SecureAsset::VT_CIPHERTEXT,
                        ciphertext,
                    );
                }
                #[inline]
                pub fn new(
                    _fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
                ) -> SecureAssetBuilder<'a, 'b, A> {
                    let start = _fbb.start_table();
                    SecureAssetBuilder {
                        fbb_: _fbb,
                        start_: start,
                    }
                }
                #[inline]
                pub fn finish(self) -> ::flatbuffers::WIPOffset<SecureAsset<'a>> {
                    let o = self.fbb_.end_table(self.start_);
                    ::flatbuffers::WIPOffset::new(o.value())
                }
            }

            impl ::core::fmt::Debug for SecureAsset<'_> {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    let mut ds = f.debug_struct("SecureAsset");
                    ds.field("header", &self.header());
                    ds.field("aad", &self.aad());
                    ds.field("wrapped_cek", &self.wrapped_cek());
                    ds.field("iv", &self.iv());
                    ds.field("auth_tag", &self.auth_tag());
                    ds.field("ciphertext", &self.ciphertext());
                    ds.finish()
                }
            }
            #[inline]
            /// Verifies that a buffer of bytes contains a `SecureAsset`
            /// and returns it.
            /// Note that verification is still experimental and may not
            /// catch every error, or be maximally performant. For the
            /// previous, unchecked, behavior use
            /// `root_as_secure_asset_unchecked`.
            pub fn root_as_secure_asset(
                buf: &[u8],
            ) -> Result<SecureAsset<'_>, ::flatbuffers::InvalidFlatbuffer> {
                ::flatbuffers::root::<SecureAsset>(buf)
            }
            #[inline]
            /// Verifies that a buffer of bytes contains a size prefixed
            /// `SecureAsset` and returns it.
            /// Note that verification is still experimental and may not
            /// catch every error, or be maximally performant. For the
            /// previous, unchecked, behavior use
            /// `size_prefixed_root_as_secure_asset_unchecked`.
            pub fn size_prefixed_root_as_secure_asset(
                buf: &[u8],
            ) -> Result<SecureAsset<'_>, ::flatbuffers::InvalidFlatbuffer> {
                ::flatbuffers::size_prefixed_root::<SecureAsset>(buf)
            }
            #[inline]
            /// Verifies, with the given options, that a buffer of bytes
            /// contains a `SecureAsset` and returns it.
            /// Note that verification is still experimental and may not
            /// catch every error, or be maximally performant. For the
            /// previous, unchecked, behavior use
            /// `root_as_secure_asset_unchecked`.
            pub fn root_as_secure_asset_with_opts<'b, 'o>(
                opts: &'o ::flatbuffers::VerifierOptions,
                buf: &'b [u8],
            ) -> Result<SecureAsset<'b>, ::flatbuffers::InvalidFlatbuffer> {
                ::flatbuffers::root_with_opts::<SecureAsset<'b>>(opts, buf)
            }
            #[inline]
            /// Verifies, with the given verifier options, that a buffer of
            /// bytes contains a size prefixed `SecureAsset` and returns
            /// it. Note that verification is still experimental and may not
            /// catch every error, or be maximally performant. For the
            /// previous, unchecked, behavior use
            /// `root_as_secure_asset_unchecked`.
            pub fn size_prefixed_root_as_secure_asset_with_opts<'b, 'o>(
                opts: &'o ::flatbuffers::VerifierOptions,
                buf: &'b [u8],
            ) -> Result<SecureAsset<'b>, ::flatbuffers::InvalidFlatbuffer> {
                ::flatbuffers::size_prefixed_root_with_opts::<SecureAsset<'b>>(opts, buf)
            }
            #[inline]
            /// Assumes, without verification, that a buffer of bytes contains a SecureAsset and returns it.
            /// # Safety
            /// Callers must trust the given bytes do indeed contain a valid `SecureAsset`.
            pub unsafe fn root_as_secure_asset_unchecked(buf: &[u8]) -> SecureAsset<'_> {
                unsafe { ::flatbuffers::root_unchecked::<SecureAsset>(buf) }
            }
            #[inline]
            /// Assumes, without verification, that a buffer of bytes contains a size prefixed SecureAsset and returns it.
            /// # Safety
            /// Callers must trust the given bytes do indeed contain a valid size prefixed `SecureAsset`.
            pub unsafe fn size_prefixed_root_as_secure_asset_unchecked(
                buf: &[u8],
            ) -> SecureAsset<'_> {
                unsafe { ::flatbuffers::size_prefixed_root_unchecked::<SecureAsset>(buf) }
            }
            pub const SECURE_ASSET_IDENTIFIER: &str = "HMSA";

            #[inline]
            pub fn secure_asset_buffer_has_identifier(buf: &[u8]) -> bool {
                ::flatbuffers::buffer_has_identifier(buf, SECURE_ASSET_IDENTIFIER, false)
            }

            #[inline]
            pub fn secure_asset_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
                ::flatbuffers::buffer_has_identifier(buf, SECURE_ASSET_IDENTIFIER, true)
            }

            #[inline]
            pub fn finish_secure_asset_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
                fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
                root: ::flatbuffers::WIPOffset<SecureAsset<'a>>,
            ) {
                fbb.finish(root, Some(SECURE_ASSET_IDENTIFIER));
            }

            #[inline]
            pub fn finish_size_prefixed_secure_asset_buffer<
                'a,
                'b,
                A: ::flatbuffers::Allocator + 'a,
            >(
                fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
                root: ::flatbuffers::WIPOffset<SecureAsset<'a>>,
            ) {
                fbb.finish_size_prefixed(root, Some(SECURE_ASSET_IDENTIFIER));
            }
        } // pub mod secureasset
    } // pub mod krypton
} // pub mod cosmos
